# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [4]:
# %run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2270588361616
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [8]:
print(f"Total memory size: {x.nbytes} bytes")

Total memory size: 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
x = np.arange(10,49)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
a = x[::-1]
a

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
x = np.arange(0, 9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
a = np.array([1,2,0,0,4,0])
non_zero = np.nonzero(a)
non_zero

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [22]:
a = np.random.random((3, 3, 3))
a

array([[[0.77198097, 0.65484761, 0.91831333],
        [0.32932159, 0.23700858, 0.23236188],
        [0.64472192, 0.79351706, 0.87318221]],

       [[0.10058775, 0.72128208, 0.09891277],
        [0.73769837, 0.59127169, 0.75672457],
        [0.27205454, 0.75969164, 0.97531199]],

       [[0.20208199, 0.0880426 , 0.6034944 ],
        [0.05909651, 0.70935742, 0.40364482],
        [0.21464313, 0.12180655, 0.98707644]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [27]:
arr = np.random.random((10,10))
print(arr)
print(f"Max: {arr.max()} \nMin: {arr.min()}")

[[0.85937933 0.94696397 0.23103202 0.01565587 0.14956667 0.23387285
  0.34883562 0.91947816 0.25222785 0.50992293]
 [0.23182557 0.96510388 0.64347133 0.2642862  0.78425921 0.79162058
  0.03675447 0.16723772 0.33329387 0.52443077]
 [0.74346278 0.33109318 0.46043929 0.07945109 0.13384674 0.83566319
  0.39868872 0.30964628 0.1468845  0.25875144]
 [0.79479549 0.79004397 0.88112392 0.32597142 0.49934802 0.14461043
  0.60647066 0.31131879 0.09595839 0.31187036]
 [0.95053377 0.27960144 0.53479848 0.35842791 0.53346777 0.38460142
  0.05787942 0.3504689  0.3140151  0.51017331]
 [0.05389706 0.28862098 0.09766856 0.6917576  0.26456487 0.4295025
  0.1376906  0.70096949 0.56161133 0.89056963]
 [0.42348511 0.03938718 0.26129737 0.72967698 0.54290886 0.19092373
  0.52259653 0.31513605 0.54822586 0.27924306]
 [0.16576206 0.32503087 0.78836903 0.63797001 0.9131536  0.20709533
  0.44724677 0.83341271 0.36084625 0.9677495 ]
 [0.09955793 0.43638454 0.0946857  0.21977088 0.8113641  0.51485561
  0.169434   

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [29]:
a1 = np.random.random(30)
a1.mean()

0.464669444120506

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [32]:
x = np.ones((5, 5))
x[1:-1, 1:-1] = 0

print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [35]:
arr = np.ones((3, 3))
print(arr)
print("0 on the border and 1 inside in the array")
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [38]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [42]:
import numpy as np
np.diag((1+np.arange(4)),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [43]:
x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1  
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [56]:
a = np.arange(336).reshape(6,7,8)
np.unravel_index(100, a.shape)

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [59]:
base = np.array([[0, 1],
                [1, 0]])
board = np.tile(base, (4, 4))
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [19]:
arr = np.random.randint(10,20,(5,5))
norm = np.linalg.norm(arr)
print(arr / norm)

[[0.15204629 0.15204629 0.24880302 0.15204629 0.23498063]
 [0.17969107 0.1382239  0.16586868 0.17969107 0.19351346]
 [0.19351346 0.26262541 0.20733585 0.17969107 0.15204629]
 [0.15204629 0.24880302 0.23498063 0.24880302 0.1382239 ]
 [0.19351346 0.16586868 0.26262541 0.20733585 0.24880302]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [20]:
custom_dtype = np.dtype([
        ('R', np.float64),
        ('G', np.float64),
        ('B', np.float64),
        ('A', np.float64)
    ])
custom_dtype

dtype([('R', '<f8'), ('G', '<f8'), ('B', '<f8'), ('A', '<f8')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
a1 = np.random.randint(1,8,(5,3))
a2 = np.random.randint(1,8,(3,2))
print(f"Array 1: {a1} \n Array 2: {a2}")
a3 = np.dot(a1,a2)
print(f"Product: {a3}")

Array 1: [[7 4 3]
 [3 1 5]
 [1 6 4]
 [6 2 1]
 [5 5 2]] 
 Array 2: [[1 5]
 [2 7]
 [7 1]]
Product: [[36 66]
 [40 27]
 [41 51]
 [17 45]
 [29 62]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [36]:
a1 = np.array([1, 5, 2, 7, 9, 4, 6, 0])
print(a1)
mask = (a1>=3) & (a1<=8)
a1[mask] = -a1[mask]
print(a1)

[1 5 2 7 9 4 6 0]
[ 1 -5  2 -7  9 -4 -6  0]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [71]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z              LEGAL
2 << Z >> 2      NOT LEGAL
Z <- Z            LEGAL
1j*Z              LEGAL
Z/1/1             LEGAL
Z<Z>Z           NOT LEGAL
```

In [86]:
Z = np.random.random((3,3))*10
Z = np.around(Z,2)
print(Z**Z)
print(Z<Z>Z)

[[6.49790792e+06 9.36708745e+06 3.17649612e+02]
 [1.64781733e+01 8.27419025e+02 1.08603910e+05]
 [1.19423161e+09 2.53563451e+01 2.39901799e+04]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [37]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\DELL\AppData\Local\Temp\ipykernel_18148\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\DELL\AppData\Local\Temp\ipykernel_18148\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\DELL\AppData\Local\Temp\ipykernel_18148\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [40]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.round(Z))

[-1.58842116  3.41979376 -8.34307985  5.25162359 -7.81993598 -4.87541808
  0.2651535  -9.05505379 -7.60603799  8.2745871 ]
[-2.  3. -8.  5. -8. -5.  0. -9. -8.  8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [45]:
a1 = np.random.randint(1,8,(5))
a2 = np.random.randint(1,8,(5))
print(a1,a2)
print(np.intersect1d(a1,a2))

[4 6 2 7 4] [3 5 5 4 5]
[4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [49]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

## It is False

In [50]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [61]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print(f"Yesterday: {yesterday}")
print(f"Today: {today}")
print(f"Tomorrow: {tomorrow}")

Yesterday: 2025-06-17
Today: 2025-06-18
Tomorrow: 2025-06-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [62]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [88]:
A = np.random.random((3,3))*10
B = np.random.random((3,3))*10
print(A,B)
A = ((A+B)*(-A/2))
A

[[0.98458191 0.49854567 2.66882437]
 [5.39049461 6.51896041 9.78738065]
 [1.45169505 6.72944062 1.70460304]] [[1.84100488 6.95053793 9.4621913 ]
 [9.69592521 3.30974741 7.63313252]
 [5.95333058 6.97308714 7.30351707]]


array([[ -1.39101081,  -1.85685417, -16.18777511],
       [-40.66163239, -32.03647859, -85.25059676],
       [ -5.37491954, -46.10517346,  -7.67763447]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [98]:
arr = np.random.rand(5) * 10
print(np.floor(arr))
print(np.array([int(x) for x in arr]))
print(np.ceil(arr-1))
print(arr.astype(int))

[9. 4. 5. 8. 1.]
[9 4 5 8 1]
[9. 4. 5. 8. 1.]
[9 4 5 8 1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [101]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [111]:
def generator():
    for i in range(1,11):
        yield i
arr = np.fromiter(generator(), dtype=int)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [114]:
vector = np.linspace(0, 1, 12)[1:-1]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [119]:
arr = np.random.random(10)*10
arr.sort()
arr

array([0.03429126, 0.4878635 , 0.6911976 , 1.28790952, 4.25161305,
       4.60270802, 8.13809743, 8.37127211, 8.53598058, 9.96071912])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [120]:
arr = np.add.reduce(arr)
arr

46.361652183128236

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [121]:
A = np.random.random(3)
B = np.random.random(3)
print(A)
print(B)
print(A==B)

[0.08678369 0.59492472 0.2940795 ]
[0.30135708 0.79617769 0.4942383 ]
[False False False]


#### 43. Make an array immutable (read-only) (★★☆)

In [126]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

arr[0] = 7
print(arr)

arr.flags.writeable = False
arr[0] = 6

[1 2 3 4 5]
[7 2 3 4 5]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [128]:
z = np.random.random((10, 2))
print(z)
x, y = z[:, 0], z[:, 1]

r = np.sqrt(x**2 + y**2)
t = np.arctan2(y, x)
print(r)
print(t)

[[0.43022765 0.51830647]
 [0.03615052 0.43881883]
 [0.01802924 0.89944051]
 [0.41565855 0.03383542]
 [0.58823934 0.75599316]
 [0.44459286 0.02164302]
 [0.94121292 0.47114029]
 [0.62600922 0.2655474 ]
 [0.81262243 0.31547875]
 [0.55961513 0.01553785]]
[0.67360035 0.44030538 0.89962119 0.41703341 0.95788892 0.44511934
 1.05254688 0.68000218 0.87171214 0.55983079]
[0.87799047 1.48860052 1.55075406 0.08122286 0.90955154 0.04864214
 0.46410124 0.40118511 0.37031278 0.02775811]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [130]:
arr = np.random.random(10)*10
print(arr)
arr[arr.argmax()] = 0
print(arr)

[8.60242074 4.6705806  8.53709767 7.60916448 4.65961083 6.48371307
 8.15521187 4.48949061 6.96250894 0.310476  ]
[0.         4.6705806  8.53709767 7.60916448 4.65961083 6.48371307
 8.15521187 4.48949061 6.96250894 0.310476  ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [134]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [136]:
x = np.array([3,4,5,2,9,14])
y = np.array([11,5,2,9,7,6])
cauchy_matrix = 1.0 / (x[:, np.newaxis] - y)
print(cauchy_matrix)

[[-0.125      -0.5         1.         -0.16666667 -0.25       -0.33333333]
 [-0.14285714 -1.          0.5        -0.2        -0.33333333 -0.5       ]
 [-0.16666667         inf  0.33333333 -0.25       -0.5        -1.        ]
 [-0.11111111 -0.33333333         inf -0.14285714 -0.2        -0.25      ]
 [-0.5         0.25        0.14285714         inf  0.5         0.33333333]
 [ 0.33333333  0.11111111  0.08333333  0.2         0.14285714  0.125     ]]


C:\Users\DELL\AppData\Local\Temp\ipykernel_24056\2628026925.py:3: RuntimeWarning: divide by zero encountered in divide
  cauchy_matrix = 1.0 / (x[:, np.newaxis] - y)


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [137]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [149]:
import sys
arr = np.arange(100)
np.set_printoptions(threshold=sys.maxsize)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [153]:
vector = np.random.random(5)*10
print(vector)
scalar = 7
differences = np.abs(vector - scalar)
closest_index = np.argmin(differences)
print(vector[closest_index])

[9.56005381 7.53302441 9.9407108  4.12762814 4.74776022]
7.533024405321074


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [53]:
a = np.ones(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [159]:
Z = np.random.random((10,2))
print(Z)
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.03247117 0.21518325]
 [0.60034089 0.7045573 ]
 [0.15413589 0.61944603]
 [0.90890599 0.46367311]
 [0.30862435 0.40639678]
 [0.70326052 0.64956699]
 [0.20783608 0.59824945]
 [0.7066768  0.9654476 ]
 [0.79167622 0.88521826]
 [0.07642287 0.17220393]]
[[0.         0.7496419  0.42217377 0.91098035 0.33589164 0.7991543
  0.42129867 1.00868717 1.01259035 0.06147336]
 [0.7496419  0.         0.45424975 0.39145575 0.41713096 0.11668926
  0.40664651 0.28172872 0.26314937 0.74692048]
 [0.42217377 0.45424975 0.         0.77067705 0.26316662 0.54995012
  0.05773219 0.65193446 0.69071887 0.45394362]
 [0.91098035 0.39145575 0.77067705 0.         0.60300798 0.27721218
  0.7138696  0.54099379 0.43754215 0.88203312]
 [0.33589164 0.41713096 0.26316662 0.60300798 0.         0.46354014
  0.21671577 0.68628242 0.68015374 0.3297936 ]
 [0.7991543  0.11668926 0.54995012 0.27721218 0.46354014 0.
  0.49807516 0.31589908 0.25169199 0.78790922]
 [0.42129867 0.40664651 0.05773219 0.7138696  0.21671577 0.49807516


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [162]:
a = np.arange(10, dtype=np.float32)
a1 = a.astype(np.int32)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [164]:
from io import StringIO
 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [166]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
    print(index, value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [169]:
n = 10
p = 3
Z = np.zeros((10,10))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [61]:
arr = np.array([[4, 2, 3],
                [2, 5, 4],
                [9, 7, 1]])

row_means = np.round(np.mean(arr, axis=1))
for i in range(len(row_means)):
    arr[i] = arr[i] - row_means[i]
print(row_means)
print(arr)


[3. 4. 6.]
[[ 1 -1  0]
 [-2  1  0]
 [ 3  1 -5]]


#### 59. How to sort an array by the nth column? (★★☆)

In [75]:
arr = np.random.randint(1,9,(4,4))

n = 2
indices = arr[:, n].argsort()
sorted_arr = arr[indices]

print("Original array:")
print(arr)
print("\nSorted array by column", n, ":")
print(sorted_arr)

Original array:
[[7 4 4 7]
 [4 3 2 3]
 [6 4 1 2]
 [7 5 3 1]]

Sorted array by column 2 :
[[6 4 1 2]
 [4 3 2 3]
 [7 5 3 1]
 [7 4 4 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [79]:
arr = np.array([[1, 2, np.nan],
                [4, 5, np.nan],
                [7, 8, np.nan]])

flag = np.isnan(arr).all(axis=0)
print(flag)
a = flag.any()

print(a)

[False False  True]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [87]:
arr = np.array([[1, 2, 9],
                [4, 5, 10],
                [7, 8, 1]])
val = 6
diff = np.abs(arr-val)
m = np.argmin(diff)
i = np.unravel_index(m,(3,3))
print(i)
print(arr.flatten()[m])


(1, 1)
5


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [89]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A,B)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0]
 [1]
 [2]] [[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [94]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

Z = NamedArray(np.arange(10), "Array")
print (Z.name)

Array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [177]:
import numpy as np

my_array = np.ones(5)
indices = np.array([0, 1, 2, 4])
np.add.at(my_array, indices, 1)
print(my_array)

[2. 2. 2. 1. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [183]:
a = [1,2,3,4,5,6]
i = [1,3,9,3,4,1]
f = np.bincount(i,a)
print(f)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [187]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
a = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(a))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [199]:
a = np.random.randint(0,10,(4,3,4,3))
sum = a.sum(axis=(-1,-2))
print(sum)

[[43 43 55]
 [65 44 64]
 [48 63 53]
 [54 48 64]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [97]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.54265986 0.63955262 0.40407572 0.51944468 0.44263628 0.38089258
 0.25768926 0.45236486 0.46928043 0.44446363]


#### 69. How to get the diagonal of a dot product? (★★★)

In [202]:
a = np.random.uniform(0,1,(5,5))
b = np.random.uniform(0,1,(5,5))
c = np.diag(np.dot(a, b))
print(c)

[1.51923521 0.26406179 0.81066549 1.68365563 0.57724543]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [204]:
vector = np.array([1,2,3,4,5])
nz = 3
a = np.zeros(len(vector) + (len(vector)-1)*(nz))
a[::nz+1] = vector
print(a)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [6]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
c = (A * B[:,:,None])
print(c)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [8]:
A = np.arange(25).reshape(5,5)
print(A)
A[[1,0]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [10]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [99]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
window_size = 3

window = np.ones(window_size) / window_size
moving_averages = np.convolve(data, window, mode='valid')

print(moving_averages)

[2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [106]:
Z = np.array([1,2,3,4,5,6,7,8,9])
a = np.reshape(Z,(3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [112]:
bool1 = np.array([True,False])
np.logical_not(bool1, out=bool1)
print(bool1)
f = np.random.uniform(-1.0,1.0,100)
np.negative(f, out=f)
print(f)

[False  True]
[-2.31482426e-01  6.61182649e-04 -4.31924089e-01  5.19173256e-01
  8.02421229e-01 -8.20236899e-01  2.11077771e-01 -9.98045937e-02
 -5.46674281e-01 -1.11771049e-01 -2.68380733e-01  5.77784370e-01
  5.28292017e-01 -5.30804714e-01  1.14997725e-02  4.98951578e-01
 -2.16886907e-01 -6.66706737e-01  6.70673029e-01 -5.00120165e-02
 -2.06207630e-01 -3.56833659e-01 -4.10234823e-02 -8.80289293e-01
 -5.13497956e-01  1.49210096e-01 -9.03930613e-03  5.91697510e-01
  3.97277329e-01  8.17511416e-01  4.14235970e-01 -3.66923300e-03
 -4.86040232e-01 -5.16842114e-01 -6.61008426e-01 -4.69937542e-01
 -6.51868386e-01 -9.10963069e-01  5.95906179e-01 -2.29768601e-02
 -9.58321272e-01 -1.09392899e-01  7.78482628e-01  2.97363490e-01
  1.76767621e-01 -7.82154607e-01  9.23817866e-01  2.92246069e-01
  8.27898462e-01  7.21176205e-01 -3.89034972e-01  3.10194749e-01
  9.07756561e-01  5.72624898e-01  9.65525781e-01  4.40982510e-01
  2.44086666e-01  4.10136662e-01  1.60126796e-01 -7.27685397e-01
  7.2776715

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [114]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[13.37670399  1.0989913  14.44480204  4.76896318  4.18812789  8.82403474
  9.09013473  5.31702501  9.10563963  8.87043334]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [115]:
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_j) for p_j in p]))

[[ 0.60294577 18.68228287  0.22073063 10.13711532 12.24339518 10.54715003
   0.82027979  0.31982842  5.16504398  9.57317743]
 [ 3.08029227 11.52296149  3.92351911  2.55163964  0.6822494   1.82536065
   0.62540583  3.15866206  1.38206115  2.84896933]
 [ 4.03780121  7.52940168  5.95055504 10.66098968  8.86387316  9.42575714
   1.11507176  5.54213665  0.41221546  1.90501217]
 [ 1.71623287 14.15668532  0.20722125  7.32607796  4.8214777   3.67171835
   6.17505024  9.43760562  5.66589805  3.86086941]
 [ 0.69259197 11.30752619  2.39654693  8.91756104  6.70796072  6.25235164
   4.09122106  7.88524598  3.10115635  3.17345523]
 [ 0.05012415 16.03026313  0.32800421  1.86301381  4.08898023  3.54247841
   2.82144763  4.14320543  4.85838004  3.60646911]
 [17.01529951  1.25581473 16.83119977  4.48388671  4.54897527  2.47183359
  14.29266579 12.33998597 11.77179116 17.74664376]
 [11.80194986  5.71497164 11.7878974   3.46685134  4.19724498  0.80976397
   8.99623875  7.18981047  6.68331982 13.25909976]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [119]:
arr = np.random.randint(1,10,(4,4))
print(arr)
print(np.linalg.matrix_rank(arr))

[[9 8 5 9]
 [1 8 2 5]
 [7 4 4 7]
 [1 7 7 5]]
4


#### 83. How to find the most frequent value in an array?

In [129]:
arr = np.random.randint(1,10,(10))
print(arr)
bins = np.bincount(arr)
print(arr[max(bins)])

[1 2 6 4 5 4 3 2 2 3]
4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)