# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
# %run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

2.1.3


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [3]:
np.empty(10).size * np.empty(10).itemsize
np.empty(10).nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [4]:
np.add?

Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\aaa\appdata\roaming\python\python310\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condit

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
a=np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [5]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [6]:
np.arange(10,49,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
vec=np.arange(10,49,2)
reversed=vec[::-1]
print(reversed)

[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
vec=np.arange(0,9)
vec.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
list=[1,2,0,0,4,0]
vec=np.array(list)
non_zero=np.nonzero(vec)
print(non_zero)


(array([0, 1, 4]),)


In [19]:
list=[1,2,0,0,4,0]
vec=np.array(list)
non_zero=np.where(vec==0)
print(non_zero)


(array([2, 3, 5]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [20]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [25]:
np.random.rand(3,3)

array([[0.39483917, 0.0715104 , 0.00409453],
       [0.89059032, 0.41333397, 0.36829254],
       [0.44181771, 0.5295987 , 0.50545723]])

In [27]:
np.random.randint(2,20,size=(3,3))

array([[ 7,  4,  9],
       [18, 13, 11],
       [15, 12, 15]], dtype=int32)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [34]:
matric=np.random.randint(2,20,size=(10,10))
print(matric)
print("Minimum from matic===",np.min(matric))
print("Maximum from matic===",np.max(matric))

[[18  8 18 19  5  5  3 17 17  2]
 [ 8 12  5 10 17  4  9 11 17 19]
 [13 15 17  3 19  3 10  4 15 16]
 [13  5 12  4 16 17 17 15  9  5]
 [ 4 12 18 17 11 19 19  2  4  8]
 [ 2 11 15 18 15 13  2 17 11 10]
 [13  8  8 10 17  9 11 13  9 11]
 [ 3 16 11  4  5  3 18  6 12 14]
 [ 2  3 17  8  8 16  6 14 14  5]
 [ 3  6 10 14 12 16 11  3 10  7]]
Minimum from matic=== 2
Maximum from matic=== 19


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [38]:
vec=np.random.randint(1,100,size=(1,30))
print (vec)
print("Mean of 30 random numbers===",np.mean(vec))

[[42 90 41 88  6 91 28 74 60 36 81 27 14 98 30 80 95 19 61 88 23 74 94 31
  70 93 64 29 13 74]]
Mean of 30 random numbers=== 57.13333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [40]:
n = 5  
arr = np.zeros((n, n), dtype=int)
arr[0, :] = 1       
arr[-1, :] = 1      
arr[:, 0] = 1       
arr[:, -1] = 1      

print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [41]:
arr = np.array([[1, 2], [3, 4]])
padded_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(padded_arr)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [42]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [54]:
v=[1,2,3,4]
matric=np.diag(v,k=-1)
print(matric)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [56]:
n = 8
checkerboard = np.zeros((n, n), dtype=int)


In [57]:
checkerboard

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
checkerboard[1::2, ::2] = 1  # fill 1s in odd rows, even columns


In [59]:
checkerboard 

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [60]:
checkerboard[::2, 1::2] = 1 

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [6]:
shape = (6, 7, 8)
total_elements = np.prod(shape)
index_100th_element = 99
indices = np.unravel_index(index_100th_element, shape)
print("Index (x, y, z) of the 100th element:", indices)

Index (x, y, z) of the 100th element: (1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [65]:

matric = np.array([[0, 1],
                    [1, 0]])
checkerboard = np.tile(matric, (4,4))

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [67]:
matric=np.random.rand(5,5)
print(matric)

[[0.81677578 0.90149438 0.91258104 0.34061729 0.69436125]
 [0.80909255 0.53171029 0.93619525 0.39465186 0.03236958]
 [0.9551383  0.67022668 0.42095636 0.72295169 0.77532567]
 [0.29459072 0.75143855 0.36200203 0.91649907 0.58897908]
 [0.83477429 0.40737182 0.36702438 0.91473575 0.93326814]]


In [71]:

min_val = matric.min()
print(min_val)
max_val = matric.max()
print(max_val)
normalized_matric = (matric - min_val) / (max_val - min_val)

print(normalized_matric)


0.03236957814962982
0.9551382998352935
[[0.8500572  0.94186634 0.9538809  0.33404655 0.71739717]
 [0.84173092 0.54113312 0.97947151 0.39260355 0.        ]
 [1.         0.69124266 0.42110962 0.7483805  0.80513793]
 [0.28416778 0.77925156 0.35722109 0.95812686 0.60319502]
 [0.86956211 0.40638812 0.36266379 0.95621595 0.97629941]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [7]:
rgba_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

color = np.array((255, 0, 0, 128), dtype=rgba_dtype)

red = color['R']
green = color['G']
blue = color['B']
alpha = color['A']

print(f"RGBA Color: ({red}, {green}, {blue}, {alpha})")


RGBA Color: (255, 0, 0, 128)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [78]:
print("Matrix 01")
m1=np.random.randint(1,4,size=(5,3))
print(m1)
print("Matrix 02")
m2=np.random.randint(1,6,size=(3,2))
print(m2)
print ("Multiplication ")
product=np.dot(m1,m2)
print(product)

Matrix 01
[[3 1 1]
 [1 2 3]
 [1 1 2]
 [1 3 2]
 [2 2 1]]
Matrix 02
[[1 1]
 [2 1]
 [5 2]]
Multiplication 
[[10  6]
 [20  9]
 [13  6]
 [17  8]
 [11  6]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [89]:
import numpy as np

arr = np.arange(20)
print("Original array:")
print(arr)
np.random.shuffle(arr)
print("\nShuffled array:")
print(arr)
arr[(arr > 3) & (arr < 8)] *= -1
print("\nModified array (values between 3 and 8 negated):")
print(arr)


Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Shuffled array:
[11  9  1 17  2  4  8 14  0  7  5 13 16  6 12 10 19 15 18  3]

Modified array (values between 3 and 8 negated):
[11  9  1 17  2 -4  8 14  0 -7 -5 13 16 -6 12 10 19 15 18  3]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [90]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [91]:
Z=np.arange(10)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [93]:
print("Legal")
Z*Z

Legal


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [95]:
print("Legal")
2<<Z>>2

Legal


array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256])

In [96]:
Z<-Z

array([False, False, False, False, False, False, False, False, False,
       False])

In [97]:
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [98]:
Z/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [99]:
Z<Z>

SyntaxError: invalid syntax (343232640.py, line 1)

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [100]:
np.array(0) / np.array(0)

C:\Users\aaa\AppData\Local\Temp\ipykernel_21248\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

#### 29. How to round away from zero a float array ? (★☆☆)

In [103]:
arr = np.array([1.2, -1.7, 0.5, -0.3])
rounded = np.where(arr > 0, np.ceil(arr), np.floor(arr))

print("Original:", arr)
print("Rounded away from zero:", rounded)


Original: [ 1.2 -1.7  0.5 -0.3]
Rounded away from zero: [ 2. -2.  1. -1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [114]:
a1=np.random.randint(1,5,size=(1,5))
a2=np.random.randint(1,5,size=(1,5))
print(a1,a2)
np.intersect1d(a1,a2)

[[1 2 2 1 4]] [[1 1 4 3 2]]


array([1, 2, 4], dtype=int32)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [10]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\aaa\AppData\Local\Temp\ipykernel_13976\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [119]:
today = np.datetime64('today', 'D')
print("Today:", today)

Today: 2025-06-18


In [120]:
yesterday = today - np.timedelta64(1, 'D')
print( np.timedelta64(1, 'D'))
print("Yesterday:", yesterday)

1 days
Yesterday: 2025-06-17


In [121]:
tomorrow = today + np.timedelta64(1, 'D')
print( np.timedelta64(1, 'D'))
print("Tomorrow:", tomorrow)

1 days
Tomorrow: 2025-06-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [122]:
dates = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [11]:
A = np.array([3.0, 5.0, 7.0])
B = np.array([1.0, 2.0, 3.0])

np.negative(A, out=A)
np.divide(A, 2, out=A)

np.add(A, B, out=A)

np.multiply(A, (A + B), out=A)

array([-0.25, -0.75, -1.25])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [125]:
Z = np.random.uniform(0, 10, size=10)
print(Z)
print(type(Z))

[6.79090616 8.64281443 7.50844246 9.64489768 5.54242435 2.12390499
 2.22443224 2.18749374 5.69573535 4.52109035]
<class 'numpy.ndarray'>


In [126]:
print(Z.astype(int))
print(type(Z))

[6 8 7 9 5 2 2 2 5 4]
<class 'numpy.ndarray'>


In [128]:
print(np.floor(Z).astype(int))

[6 8 7 9 5 2 2 2 5 4]


In [129]:
print(np.trunc(Z).astype(int))

[6 8 7 9 5 2 2 2 5 4]


In [130]:
print(np.array(list(map(int, Z))))

TypeError: 'list' object is not callable

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [13]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [139]:
vec=np.arange(5)
print(vec)
print(np.shape(vec))
new_vec=np.tile(vec,(5,1))
print(new_vec)
print(np.shape(new_vec))

[0 1 2 3 4]
(5,)
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
(5, 5)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [140]:
np.arange(1,11)/11

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [141]:
Z = np.random.uniform(0, 10, size=10).astype(int)
print(Z)

[9 6 0 0 4 8 9 6 5 8]


In [142]:
np.sort(Z)

array([0, 0, 4, 5, 6, 6, 8, 8, 9, 9])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [147]:
print(np.sum(Z))

55


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [150]:
A = np.random.randint(0,11,10)
B = np.random.randint(0,11,10)
print(A,B)
equal = np.array_equal(A,B)

if equal:
  print("Equal")
else:
  print("Not equal")

[ 0  3  8  7  7 10  1  8  4  7] [ 0  4  9  0 10  6  4  2  4  6]
Not equal


In [151]:
A = np.arange(5)
B = np.arange(5)
print(A,B)
equal = np.array_equal(A,B)

if equal:
  print("Equal")
else:
  print("Not equal")

[0 1 2 3 4] [0 1 2 3 4]
Equal


#### 43. Make an array immutable (read-only) (★★☆)

In [154]:
arr = np.array([1, 2, 3, 4, 5])

arr.flags.writeable = False

if arr.flags.writeable:
    print("The array is mutable.")
else:
    print("The array is read-only.")

The array is read-only.


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [157]:
cartesian = np.random.randint(1,21,20).reshape(10,2)
print(cartesian)
x = cartesian[:, 0]
print(x)
y = cartesian[:, 1]
print(y)
r = np.sqrt(x**2 + y**2)
print(r)
theta = np.arctan2(y,x)
print(theta)
polar = np.column_stack((r,theta))
print(polar)

[[ 9 14]
 [ 8 17]
 [16  9]
 [ 4  7]
 [18  8]
 [ 3 17]
 [19 14]
 [ 5  5]
 [13 18]
 [ 2  6]]
[ 9  8 16  4 18  3 19  5 13  2]
[14 17  9  7  8 17 14  5 18  6]
[16.64331698 18.78829423 18.35755975  8.06225775 19.6977156  17.2626765
 23.60084744  7.07106781 22.20360331  6.32455532]
[0.99945885 1.13095374 0.51238946 1.05165021 0.41822433 1.39612413
 0.63502674 0.78539816 0.94531129 1.24904577]
[[16.64331698  0.99945885]
 [18.78829423  1.13095374]
 [18.35755975  0.51238946]
 [ 8.06225775  1.05165021]
 [19.6977156   0.41822433]
 [17.2626765   1.39612413]
 [23.60084744  0.63502674]
 [ 7.07106781  0.78539816]
 [22.20360331  0.94531129]
 [ 6.32455532  1.24904577]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
vec=np.random.randint(1,20,10)
print(vec)
max=np.max(vec)
vec[np.where(vec==max)]=0
print(vec)

[12  7 10 16  4 13 19 18 11  3]
[12  7 10 16  4 13  0 18 11  3]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [14]:
num_points = 10
x = np.linspace(0, 1, num_points)
y = np.linspace(0, 1, num_points)
x_grid, y_grid = np.meshgrid(x, y)
structured_array = np.column_stack((x_grid.ravel(), y_grid.ravel()))
print("Structured array with x and y coordinates covering [0,1]x[0,1]:\n", structured_array)

Structured array with x and y coordinates covering [0,1]x[0,1]:
 [[0.         0.        ]
 [0.11111111 0.        ]
 [0.22222222 0.        ]
 [0.33333333 0.        ]
 [0.44444444 0.        ]
 [0.55555556 0.        ]
 [0.66666667 0.        ]
 [0.77777778 0.        ]
 [0.88888889 0.        ]
 [1.         0.        ]
 [0.         0.11111111]
 [0.11111111 0.11111111]
 [0.22222222 0.11111111]
 [0.33333333 0.11111111]
 [0.44444444 0.11111111]
 [0.55555556 0.11111111]
 [0.66666667 0.11111111]
 [0.77777778 0.11111111]
 [0.88888889 0.11111111]
 [1.         0.11111111]
 [0.         0.22222222]
 [0.11111111 0.22222222]
 [0.22222222 0.22222222]
 [0.33333333 0.22222222]
 [0.44444444 0.22222222]
 [0.55555556 0.22222222]
 [0.66666667 0.22222222]
 [0.77777778 0.22222222]
 [0.88888889 0.22222222]
 [1.         0.22222222]
 [0.         0.33333333]
 [0.11111111 0.33333333]
 [0.22222222 0.33333333]
 [0.33333333 0.33333333]
 [0.44444444 0.33333333]
 [0.55555556 0.33333333]
 [0.66666667 0.33333333]
 [0.777777

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [162]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

n = len(X)
m = len(Y)
C = np.empty((n, m))

for i in range(n):
    for j in range(m):
        C[i, j] = 1.0 / (X[i] - Y[j])

print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [15]:
print("Integer Types:")
for dtype in np.sctypes['int']:
    info = np.iinfo(dtype)
    print(f"{dtype}: Min={info.min}, Max={info.max}")

print("\nFloating-point Types:")
for dtype in np.sctypes['float']:
    info = np.finfo(dtype)
    print(f"{dtype}: Min={info.min}, Max={info.max}")

Integer Types:
<class 'numpy.int8'>: Min=-128, Max=127
<class 'numpy.int16'>: Min=-32768, Max=32767
<class 'numpy.int32'>: Min=-2147483648, Max=2147483647
<class 'numpy.int64'>: Min=-9223372036854775808, Max=9223372036854775807

Floating-point Types:
<class 'numpy.float16'>: Min=-65504.0, Max=65504.0
<class 'numpy.float32'>: Min=-3.4028234663852886e+38, Max=3.4028234663852886e+38
<class 'numpy.float64'>: Min=-1.7976931348623157e+308, Max=1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
arr = np.array([1,2,3,4,5])

for i in arr:
  print(i)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [164]:
vector = np.array([1, 3, 5, 3, 12, 7, 9])

target_scalar = 11
print(np.abs(vector - target_scalar))
closest_index = np.abs(vector - target_scalar).argmin()


closest_value = vector[closest_index]

print("Closest Value:", closest_value)

[10  8  6  8  1  4  2]
Closest Value: 12


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [165]:
dtype = [('x', int), ('y', int), ('r', int), ('g', int), ('b', int)]

structured_array = np.empty(1, dtype=dtype)

structured_array['x'] = 10
structured_array['y'] = 20
structured_array['r'] = 255
structured_array['g'] = 0
structured_array['b'] = 0

print(structured_array)

[(10, 20, 255, 0, 0)]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [171]:
coordinates = np.random.randint(0,101,200).reshape(100,2)
print("Coordinates",coordinates)
n = coordinates.shape[0]
print(n)
distances = np.zeros((n, n))
print(distances)
for i in range(n):
    for j in range(n):
        diff = coordinates[i] - coordinates[j]
        distances[i, j] = np.sqrt(np.dot(diff, diff))

print(distances[0, 1])

Coordinates [[ 58  66]
 [ 92  65]
 [ 77  83]
 [ 47  81]
 [ 36  71]
 [ 53  70]
 [  9  15]
 [ 18  29]
 [ 53  60]
 [ 42  82]
 [  2  29]
 [ 17  35]
 [ 19  16]
 [ 23  12]
 [ 99  56]
 [ 66  20]
 [  3  81]
 [ 44  38]
 [ 42  74]
 [ 37  40]
 [ 27   4]
 [ 51  22]
 [ 37  35]
 [ 30   7]
 [ 88  88]
 [ 15  10]
 [ 19  77]
 [ 56  18]
 [ 71  60]
 [ 24  32]
 [ 39 100]
 [ 16  52]
 [ 90  80]
 [ 46  96]
 [ 94  84]
 [ 23  15]
 [ 44  83]
 [ 55  98]
 [ 27  45]
 [ 98  81]
 [ 87  27]
 [ 77  48]
 [ 87  94]
 [  5  97]
 [ 98  28]
 [ 65  68]
 [ 85  72]
 [ 33  99]
 [ 48  99]
 [ 89  69]
 [ 65  99]
 [ 71   1]
 [  1  71]
 [ 25 100]
 [ 77  50]
 [ 27  96]
 [ 43  19]
 [ 98  45]
 [100  80]
 [ 43  67]
 [  8  83]
 [ 46  64]
 [ 20  96]
 [ 98   5]
 [ 85  24]
 [  2  71]
 [ 75  28]
 [ 95  65]
 [ 80  82]
 [ 14  21]
 [ 69  33]
 [  2  27]
 [ 19  15]
 [ 71  29]
 [ 35  97]
 [ 48  49]
 [ 80  56]
 [ 63  88]
 [ 58   5]
 [ 51  61]
 [ 83  17]
 [ 45  96]
 [ 62  22]
 [ 97   9]
 [  5  76]
 [ 61  42]
 [ 16  59]
 [ 17  68]
 [ 60  25]
 [ 14  61

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [16]:
float_array = np.array([3.14, 2.71, 1.618], dtype=np.float32)
int_array = np.empty_like(float_array, dtype=np.int32)
np.copyto(int_array, float_array.view(np.int32))
print(int_array)

[1078523331 1076719780 1070537376]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [17]:
data = """1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11"""

rows = data.strip().split('\n')
data_list = [row.split(',') for row in rows]

for i in range(len(data_list)):
    for j in range(len(data_list[i])):
        if data_list[i][j].strip() == '':
            data_list[i][j] = None
        else:
            data_list[i][j] = int(data_list[i][j])

array = np.array(data_list, dtype=np.object)

print(array)

C:\Users\aaa\AppData\Local\Temp\ipykernel_13976\1832704907.py:15: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  array = np.array(data_list, dtype=np.object)


AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [174]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
for index, value in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {value}")

Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6
Index: (2, 0), Value: 7
Index: (2, 1), Value: 8
Index: (2, 2), Value: 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [18]:
shape = (10, 10)

amplitude = 1
x0, y0 = 4, 4
sigma_x, sigma_y = 2, 1

x, y = np.meshgrid(np.arange(shape[1]), np.arange(shape[0]))
exponent = -((x - x0) ** 2 / (2 * sigma_x ** 2) + (y - y0) ** 2 / (2 * sigma_y ** 2))
gaussian_array = amplitude * np.exp(exponent)

print(gaussian_array)

[[4.53999298e-05 1.08908770e-04 2.03468369e-04 2.96044730e-04
  3.35462628e-04 2.96044730e-04 2.03468369e-04 1.08908770e-04
  4.53999298e-05 1.47391992e-05]
 [1.50343919e-03 3.60656314e-03 6.73794700e-03 9.80365504e-03
  1.11089965e-02 9.80365504e-03 6.73794700e-03 3.60656314e-03
  1.50343919e-03 4.88095244e-04]
 [1.83156389e-02 4.39369336e-02 8.20849986e-02 1.19432968e-01
  1.35335283e-01 1.19432968e-01 8.20849986e-02 4.39369336e-02
  1.83156389e-02 5.94621736e-03]
 [8.20849986e-02 1.96911675e-01 3.67879441e-01 5.35261429e-01
  6.06530660e-01 5.35261429e-01 3.67879441e-01 1.96911675e-01
  8.20849986e-02 2.66490973e-02]
 [1.35335283e-01 3.24652467e-01 6.06530660e-01 8.82496903e-01
  1.00000000e+00 8.82496903e-01 6.06530660e-01 3.24652467e-01
  1.35335283e-01 4.39369336e-02]
 [8.20849986e-02 1.96911675e-01 3.67879441e-01 5.35261429e-01
  6.06530660e-01 5.35261429e-01 3.67879441e-01 1.96911675e-01
  8.20849986e-02 2.66490973e-02]
 [1.83156389e-02 4.39369336e-02 8.20849986e-02 1.19432968e

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [19]:
shape = (5, 5)
p = 10

array = np.zeros(shape, dtype=int)

indices = np.random.choice(np.arange(shape[0] * shape[1]), p, replace=False)

array.flat[indices] = 1

print(array)

[[1 1 0 0 0]
 [0 0 1 0 1]
 [1 0 0 0 1]
 [0 0 1 0 0]
 [1 1 1 0 0]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [184]:
m=np.random.randint(1,20,(4,4))
print(m)
row_mean=np.mean(m,axis=1)
print(row_mean)
print(row_mean[np.newaxis])
m_new=m-row_mean[np.newaxis]
print(m_new)

[[ 9 10 11  7]
 [13 12  3 18]
 [ 8  8  7  6]
 [10 13  9  2]]
[ 9.25 11.5   7.25  8.5 ]
[[ 9.25 11.5   7.25  8.5 ]]
[[-0.25 -1.5   3.75 -1.5 ]
 [ 3.75  0.5  -4.25  9.5 ]
 [-1.25 -3.5  -0.25 -2.5 ]
 [ 0.75  1.5   1.75 -6.5 ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [22]:
arr = np.array([[5, 2, 8],[3, 9, 1],[7, 4, 6]])
n = 1
sorted_indices = np.argsort(arr[:, n])
sorted_arr = arr[sorted_indices]
print(sorted_arr)

[[5 2 8]
 [7 4 6]
 [3 9 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [23]:
arr = np.array([[1, 0, 0],[0, 0, 0],[4, 0, 0],[0, 2, 0]])
null_columns = np.all(arr == 0, axis=0)
if np.any(null_columns):
    print("The array has null columns.")
else:
    print("The array does not have null columns.")

The array has null columns.


#### 61. Find the nearest value from a given value in an array (★★☆)

In [24]:
arr = np.array([2.5, 1.0, 4.8, 3.2, 7.1])
# target_value = int(input("Enter a value: "))
target_value = 5
differences = np.abs(arr - target_value)
nearest_index = differences.argmin()
nearest_value = arr[nearest_index]
print("Nearest Value:", nearest_value)
print("Index of Nearest Value:", nearest_index)

Nearest Value: 4.8
Index of Nearest Value: 2


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [25]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4],
                   [5],
                   [6]])

iterator1 = np.nditer(array1)
iterator2 = np.nditer(array2)

total_sum = 0

for val1, val2 in zip(iterator1, iterator2):
    total_sum += val1 + val2

print("Sum of the two arrays:", total_sum)

Sum of the two arrays: 21


#### 63. Create an array class that has a name attribute (★★☆)

In [28]:
class array:
    def __init__(self, array, name):
        self.array = array
        self.name = name

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
name = "Custom Array"
custom_array = array(np.array(data), name)

print(custom_array.name)
print(custom_array.array)

Custom Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [29]:
original_vector = np.array([1, 2, 3, 4, 5])
indices_to_increment = np.array([1, 3, 3, 4])

mask = np.zeros_like(original_vector)
mask_indices = np.unique(indices_to_increment)
mask[mask_indices] = 1

result_vector = original_vector + mask

print("Original Vector:", original_vector)
print("Indices to Increment:", indices_to_increment)
print("Result Vector:", result_vector)

Original Vector: [1 2 3 4 5]
Indices to Increment: [1 3 3 4]
Result Vector: [1 3 3 5 6]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [30]:
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 2, 1, 4, 2])
N = len(I)
F = np.zeros(N, dtype=X.dtype)

for i in range(N):
    F[i] += X[I[i]]

print("Vector X:", X)
print("Index list I:", I)
print("Accumulated Array F:", F)

Vector X: [1 2 3 4 5]
Index list I: [0 2 1 4 2]
Accumulated Array F: [1 3 2 5 3]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [31]:

image = np.random.randint(0, 256, size=(10, 10, 3), dtype=np.uint8)

reshaped_image = image.reshape(-1, 3)

unique_colors = np.unique(reshaped_image, axis=0)

num_unique_colors = unique_colors.shape[0]

print("Number of Unique Colors:", num_unique_colors)

Number of Unique Colors: 100


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [32]:
array= np.random.rand(2, 3, 4, 5)

sum_last_two_axes = np.sum(array, axis=(2, 3))

print("Original 4D Array Shape:", array.shape)
print("Sum over Last Two Axes Shape:", sum_last_two_axes.shape)
print("Sum over Last Two Axes:")
print(sum_last_two_axes)


Original 4D Array Shape: (2, 3, 4, 5)
Sum over Last Two Axes Shape: (2, 3)
Sum over Last Two Axes:
[[10.93724881 11.6228336   8.43992864]
 [10.4069307  10.51394127 11.27266811]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [33]:
D = np.array([1, 2, 3, 4, 5, 6])

S = np.array([0, 1, 0, 1, 2, 2])

unique_indices = np.unique(S)
subset_means = np.zeros(len(unique_indices))

for i, index in enumerate(unique_indices):
    subset = D[S == index]
    subset_mean = np.mean(subset)
    subset_means[i] = subset_mean

print("Vector D:", D)
print("Vector S:", S)
print("Subset Means:", subset_means)

Vector D: [1 2 3 4 5 6]
Vector S: [0 1 0 1 2 2]
Subset Means: [2.  3.  5.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [34]:
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
B = np.array([[9, 8, 7],[6, 5, 4],[3, 2, 1]])

dot_product = np.dot(A, B)
diagonal = np.einsum('ii->i', dot_product)

print("Diagonal of Dot Product:")
print(diagonal)

Diagonal of Dot Product:
[30 69 90]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [35]:
original_vector = np.array([1, 2, 3, 4, 5])
num_zeros = 3

new_vector = np.zeros(len(original_vector) + (len(original_vector) - 1) * num_zeros, dtype=original_vector.dtype)
new_vector[::num_zeros + 1] = original_vector

print("Original Vector:", original_vector)
print("New Vector with Consecutive Zeros:", new_vector)

Original Vector: [1 2 3 4 5]
New Vector with Consecutive Zeros: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)