# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
# %run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

2.1.3


#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
x=np.zeros(10,dtype=int)
print(x)

[0 0 0 0 0 0 0 0 0 0]


#### 4. How to find the memory size of any array (★☆☆)

In [10]:
print(x.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [1]:
import numpy as np 
print(help(np.add))

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [3]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [5]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [6]:
#reverse a vector
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
matrix_3by3= np.arange(9).reshape(3,3)
matrix_3by3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
#find indices of non-zero elements
non_zero_indices = np.nonzero([1,2,0,0,0,4,5])
print(non_zero_indices)

(array([0, 1, 5, 6], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
arr = np.random.randint(1, 100, size=(3,3,3))
print(arr)

[[[39 10 74]
  [70 52 55]
  [90 30 78]]

 [[32 59 26]
  [43 59 33]
  [38 84 71]]

 [[62 63 38]
  [47  8 23]
  [81 63 41]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
arra_100_rand= np.random.randint(1,100, size=(10,10))
print(arra_100_rand.max())
print(arra_100_rand.min())
print(arra_100_rand)

97
1
[[78 31  6 41 49 80 63 36 57 31]
 [23 54 76 93 75 79 46 30 12 96]
 [70 92 58  1 80 42 61 96 13 96]
 [66 40  5 25 76 87 45 50 17 71]
 [17 92 66 59 78 49 69 18 21 73]
 [58 10 10 21 62 75 33 58 55  7]
 [43 67 55 58  8 34 97 44 15 74]
 [11 84 40 24  3 87 28 80 64 25]
 [41 64 52 59 72 49 67 20 79 40]
 [14  4 47 61 51 80 53 50 41 41]]


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [23]:
random_vector = np.random.rand(30)
mean = np.mean(random_vector)
print(mean)

0.4853243835514638


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [47]:
import numpy as np
n, m = 2, 2 
array = np.zeros((n, m), dtype=int)
border_val= np.pad(array, pad_width=1, mode='constant', constant_values=1)
print(border_val)




[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [43]:

import numpy as np
array = np.ones((3, 3), dtype=int)
bordered = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(bordered)


[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [57]:
'''Results'''
# 0 * np.nan -- > nan
# np.nan == np.nan --> False
# np.inf > np.nan --> False
# np.nan - np.nan --> False
# np.nan in set([np.nan]) -- > True
# 0.3 == 3 * 0.1 --> False

'Results'

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [61]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
ls = [1,2,3,4]
matrix = np.diag(ls, k=-1)
print(matrix)

        

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [67]:
import numpy as np
import matplotlib.pyplot as plt

# Create an 8x8 checkerboard matrix
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [71]:
import numpy as np
shape = (6, 7, 8)
flat_index = 99
index = np.unravel_index(flat_index, shape)
print(f"The index of the 100th element is: {index}")


The index of the 100th element is: (1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [73]:
pattern = np.array([[0, 1],
                    [1, 0]])
checkerboard = np.tile(pattern, (4, 4)) 

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [4]:
import numpy as np
matrix_5by5= np.random.random((5, 5))
matrix_5by5= (matrix_5by5 - np.mean(matrix_5by5)) / np.std(matrix_5by5)
print(matrix_5by5)

[[ 0.42608059  0.60078262  0.91125687 -0.97941381  1.51922294]
 [-0.61736023  0.13046975  0.24848927  1.44120944  1.21994415]
 [ 1.32104192 -0.46268801  0.09138762 -0.42174312 -1.35270725]
 [-0.24661806  0.5576049   1.12846598 -1.5802585  -1.16181212]
 [-1.16871747 -1.3503619   0.35162905 -1.60113049  0.99522587]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
custome_dtype = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])
print(custome_dtype)


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [9]:
matrix_1 = np.random.randint(1, 50, size=(5, 3))
matrix_2 = np.random.randint(1, 50, size=(3, 2))
real_matrix_product = np.dot(matrix_1, matrix_2)
# print("Matrix 1:")
# print(matrix_1)
# print("Matrix 2:")
# print(matrix_2)
print(real_matrix_product)


[[1113  748]
 [3197 3060]
 [1068  908]
 [1028  976]
 [2301 2096]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,4,5,6,7])
# NEGATE ALL ELEMENTS BETEWEEN 3 AND 8
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)

[ 1  2  3 -4 -5 -6 -7  8  9 10 -4 -5 -6 -7]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
'''Its output will be 10'''

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [20]:
z =np.array([1, 2, 3, 4, 5])
print(z**z)
print(2<<z>>2)
print(z/1/1)
# print(z<z>z) --> This line will raise an error because comparison operators cannot be chained like this in numpy.
print(1j*z)

[   1    4   27  256 3125]
[ 1  2  4  8 16]
[1. 2. 3. 4. 5.]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\ghula\AppData\Local\Temp\ipykernel_5544\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\ghula\AppData\Local\Temp\ipykernel_5544\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\ghula\AppData\Local\Temp\ipykernel_5544\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
#How to round away from zero a float array 
def round_away_from_zero(arr):
    return np.where(arr > 0, np.ceil(arr), np.floor(arr))
arr = np.array([1.2, -1.2, 1.7, -1.7, 0.0])
rounded_arr = round_away_from_zero(arr)
print(rounded_arr)

[ 2. -2.  2. -2.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [32]:

a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])

common = np.intersect1d(a, b)
print(common)

[4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [33]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [35]:
'''NO!'''

'NO!'

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [38]:
yesterday_time = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today_time = np.datetime64('today', 'D')
tomorow_time = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Yesterday:", yesterday_time)
print("Today:", today_time)
print("Tomorrow:", tomorow_time)

Yesterday: 2025-07-01
Today: 2025-07-02
Tomorrow: 2025-07-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [41]:
corresponding_time = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print("Corresponding Time:", corresponding_time)

Corresponding Time: ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [42]:
#How to compute ((A+B)*(-A/2)) in place (without copy
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = (A + B) * (-A / 2)
print(result)



[[ -3.  -8.]
 [-15. -24.]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [58]:
arr4 = np.random.uniform(0,10,10)
print(arr4 - arr4%1)    
print(arr // 1)
print(np.trunc(arr4))
print(np.floor(arr4))
print(arr4.astype(int))
# we can also use loop

[9. 9. 0. 0. 7. 1. 8. 1. 8. 3.]
[ 1. -2.  1. -2.  0.]
[9. 9. 0. 0. 7. 1. 8. 1. 8. 3.]
[9. 9. 0. 0. 7. 1. 8. 1. 8. 3.]
[9 9 0 0 7 1 8 1 8 3]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [64]:
matric_5 = np.tile(np.arange(5), (5, 1))
print(matric_5)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [69]:
def generate():
    for x in range(10):
        yield x
arr5= np.fromiter(generate(),dtype=float)
print(arr5)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [72]:
vect = np.linspace(0, 1, 11, endpoint=False)[1:]
print(vect)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [75]:
random_vector = np.random.rand(10)
random_vector.sort()
print(random_vector)

[0.01122239 0.15024504 0.18421569 0.46570987 0.5544543  0.59745108
 0.65657614 0.71445277 0.93519886 0.95906312]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [76]:
#### 41. How to sum a small array faster than np.sum? (★★☆)
def sum_array(arr):
    total = 0
    for num in arr:
        total += num
    return total
sum_result = sum_array(np.array([1, 2, 3, 4, 5]))
print("Sum of the array:", sum_result)

Sum of the array: 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [77]:
array1 = np.array([5,6,4,3,2,1])
print("Reduced sum of the array:", np.add.reduce(array1))

Reduced sum of the array: 21


#### 43. Make an array immutable (read-only) (★★☆)

In [78]:
# make array immutable
arr = tuple(arr)
print(arr)  # (1, 2, 3, 4, 5)


(1.2, -1.2, 1.7, -1.7, 0.0)


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [79]:
arr = np.array([1, 2, 3, 4, 5])

# Make it read-only
arr.flags.writeable = False

print("Immutable array:", arr)



Immutable array: [1 2 3 4 5]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [84]:
vector1 = np.array([1, 2, 3,4,5,6])
vector1[vector1.argmax()] = 0
print("Vector:",vector1)    

Vector: [1 2 3 4 5 0]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [87]:
import numpy as np
n = 5
x_vals = np.linspace(0, 1, n)
y_vals = np.linspace(0, 1, n)
X, Y = np.meshgrid(x_vals, y_vals)
coords = np.zeros(X.size, dtype=[('x', float), ('y', float)])
coords['x'] = X.ravel()
coords['y'] = Y.ravel()

print(coords)


[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [89]:
import numpy as np

X = np.arange(1, 6)     
Y = np.arange(6, 11)
# Construct Cauchy matrix using broadcasting
C = 1.0 / (X[:, None] - Y[None, :])
print("Cauchy matrix:\n", C)


Cauchy matrix:
 [[-0.2        -0.16666667 -0.14285714 -0.125      -0.11111111]
 [-0.25       -0.2        -0.16666667 -0.14285714 -0.125     ]
 [-0.33333333 -0.25       -0.2        -0.16666667 -0.14285714]
 [-0.5        -0.33333333 -0.25       -0.2        -0.16666667]
 [-1.         -0.5        -0.33333333 -0.25       -0.2       ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [91]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [94]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((60,60))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
# print(z.argmin())
# print(np.abs(z-v))
index = (np.abs(Z-v)).argmin()
print(Z[index])

0
[18.99247484 17.99247484 16.99247484 15.99247484 14.99247484]
20


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [101]:
dtype = [('position', [('x', float), ('y', float)]),
         ('color',    [('r', float), ('g', float), ('b', float)])]

data = np.zeros(3, dtype=dtype)

# Fill it with example data
data['position']['x'] = [0.0, 1.0, 2.0]
data['position']['y'] = [0.0, 1.0, 2.0]
data['color']['r'] = [255, 128, 0]
data['color']['g'] = [0, 128, 255]
data['color']['b'] = [0, 64, 128]
print(data)


[((0., 0.), (255.,   0.,   0.)) ((1., 1.), (128., 128.,  64.))
 ((2., 2.), (  0., 255., 128.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [106]:
from scipy.spatial import distance

points = np.random.rand(100, 2) 
dist_matrix = distance.squareform(distance.pdist(points, metric='euclidean'))
# d = distance.cdist(points, points, metric='euclidean')
print(dist_matrix.shape)  # (100, 100)
print(dist_matrix)
# print(d)


(100, 100)
[[0.         0.94924158 0.29078156 0.66925775 0.66214397 0.53128587
  0.44399682 0.58994751 0.76762142 1.11967619 0.36407815 0.45254302
  0.1804865  0.25182389 0.62008088 0.3062708  0.54780561 0.84449925
  0.81792302 0.60597964 0.54301337 0.29755048 0.22274745 0.77389607
  0.63821631 0.24021415 0.53057295 0.94402445 0.83316434 0.12752863
  0.36550106 0.43041044 1.01123957 0.65593002 0.68228708 0.52164078
  0.47052424 0.69271078 0.54789488 0.94282517 0.62332161 0.50445475
  0.58436377 0.76590389 0.39902494 0.9800551  0.84786583 0.58647401
  0.05321469 0.6689953  1.02647036 0.39754488 0.79640209 0.80557782
  0.59833537 0.8685119  0.52251279 0.4860292  0.31797853 0.09684667
  0.70914136 0.53282758 0.35638048 0.24375293 0.60061312 0.1772929
  0.21153907 0.65955875 0.474928   0.79535749 0.14474379 0.53637606
  0.52283305 0.22816913 0.72878068 0.63290736 0.51649386 0.02524524
  0.7413835  0.50485037 0.78371856 0.49965113 0.25310499 0.90355988
  0.77227479 0.16792179 1.03295229 0.3

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [113]:
arr = (np.random.rand(10)*100).astype(np.float32)
arr_1 = arr.view(np.int32)
arr_1[:] = arr
print(Y)

[27 24 46 27 61 77 67 49 54 19]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [116]:
# Simulating file reading using a string buffer
from io import StringIO

data_str = """
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
"""
data = np.genfromtxt(StringIO(data_str), delimiter=",", dtype=float)
print(data)


[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [117]:
# ndenumerate iterate over the multi dimention array
arr = np.array([[10, 20], [30, 40]])

for index, value in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {value}")


Index: (0, 0), Value: 10
Index: (0, 1), Value: 20
Index: (1, 0), Value: 30
Index: (1, 1), Value: 40


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [120]:
import numpy as np
import matplotlib.pyplot as plt

# Size of the array (e.g., 2D grid: 100x100)
n = 100

# Create a grid of (x,y) coordinates centered at 0
x = np.linspace(-1, 1, n)
y = np.linspace(-1, 1, n)
X, Y = np.meshgrid(x, y)

# Compute 2D Gaussian
sigma = 0.4  # standard deviation
gaussian = np.exp(-(X**2 + Y**2) / (2 * sigma**2))
print(gaussian)


[[0.00193045 0.00218746 0.00247237 0.00278728 0.00313428 0.00351551
  0.00393306 0.00438899 0.00488531 0.00542389 0.00600651 0.00663476
  0.00731006 0.00803358 0.00880621 0.00962856 0.01050089 0.01142307
  0.01239458 0.01341446 0.01448127 0.01559309 0.0167475  0.01794156
  0.01917178 0.02043417 0.0217242  0.02303683 0.02436654 0.02570735
  0.02705284 0.02839623 0.0297304  0.03104796 0.03234131 0.03360271
  0.03482436 0.0359985  0.03711741 0.03817362 0.03915986 0.04006924
  0.0408953  0.04163206 0.04227412 0.04281673 0.04325582 0.0435881
  0.04381103 0.04392293 0.04392293 0.04381103 0.0435881  0.04325582
  0.04281673 0.04227412 0.04163206 0.0408953  0.04006924 0.03915986
  0.03817362 0.03711741 0.0359985  0.03482436 0.03360271 0.03234131
  0.03104796 0.0297304  0.02839623 0.02705284 0.02570735 0.02436654
  0.02303683 0.0217242  0.02043417 0.01917178 0.01794156 0.0167475
  0.01559309 0.01448127 0.01341446 0.01239458 0.01142307 0.01050089
  0.00962856 0.00880621 0.00803358 0.00731006 0.00

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)