# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [3]:
# %run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
print(np.show_config())

2.3.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-8d7bajfv/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-8d7bajfv/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.29  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: C:/a/numpy/numpy/.openblas
    version: 0.3.29
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-8d7bajfv/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-8d7bajfv/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
arr = np.full(10, np.nan)

print(arr)

[nan nan nan nan nan nan nan nan nan nan]


#### 4. How to find the memory size of any array (★☆☆)

In [7]:
size = arr.nbytes
print(size)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
 np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
arr = np.full(10, np.nan)
arr[4] = 1
print(arr)

[nan nan nan nan  1. nan nan nan nan nan]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
arr = np.arange(10,50)

print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
reverse_arr = arr[::-1]
print(reverse_arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
arr = np.arange(9)
arr1 = arr.reshape(3,3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
arr = np.array([1,2,0,0,4,0])
x = np.where(arr != 0)
print(x)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
arr = np.array(np.random.rand(27))
arr1 = arr.reshape(3,3,3)
print(arr1)

[[[0.32153163 0.70256932 0.07162273]
  [0.71117786 0.45119591 0.0450657 ]
  [0.03124677 0.25760832 0.64065549]]

 [[0.65126683 0.18462333 0.78921297]
  [0.48187412 0.57350496 0.3584985 ]
  [0.42718733 0.97314839 0.65418164]]

 [[0.76532041 0.32228713 0.91858161]
  [0.130979   0.37522441 0.94673162]
  [0.02288692 0.21966292 0.11214268]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
arr = np.array(np.random.rand(100))
arr1 = arr.reshape(10,10)
min_val = arr1.min()
max_val = arr1.max()
print(arr1)
print("min_val =",min_val)
print("max_val =",max_val)

[[0.00235803 0.49372475 0.05813456 0.66805397 0.83821642 0.33141391
  0.47441191 0.61241744 0.90826047 0.59406234]
 [0.93404093 0.66727379 0.75947667 0.37701503 0.80469064 0.36684562
  0.94136363 0.02646548 0.80622468 0.13637497]
 [0.41649672 0.91982379 0.00967068 0.54455068 0.64355767 0.50662319
  0.4597266  0.69313398 0.73671072 0.01339344]
 [0.67436699 0.38563903 0.95367093 0.82752744 0.38285116 0.36496834
  0.64842211 0.66475219 0.80093754 0.92079661]
 [0.83981005 0.36943451 0.03085074 0.18451351 0.40935585 0.48056276
  0.41543065 0.91484423 0.46775272 0.84412196]
 [0.99185215 0.8460042  0.75147344 0.43392521 0.9339246  0.28332586
  0.31349055 0.57525005 0.44352733 0.88988416]
 [0.60269154 0.12487195 0.57983241 0.62863335 0.06295817 0.6367123
  0.89061615 0.08167924 0.94149806 0.18092197]
 [0.223504   0.27219099 0.53838113 0.92044988 0.003033   0.66378414
  0.24349491 0.10390543 0.64468114 0.42858808]
 [0.69900101 0.80077848 0.00473571 0.30563239 0.47583216 0.59474871
  0.80294969 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
arr = np.array(np.random.rand(30))

mean_val = arr1.mean()

print(arr1)
print("mean_val =",mean_val)

[[0.00235803 0.49372475 0.05813456 0.66805397 0.83821642 0.33141391
  0.47441191 0.61241744 0.90826047 0.59406234]
 [0.93404093 0.66727379 0.75947667 0.37701503 0.80469064 0.36684562
  0.94136363 0.02646548 0.80622468 0.13637497]
 [0.41649672 0.91982379 0.00967068 0.54455068 0.64355767 0.50662319
  0.4597266  0.69313398 0.73671072 0.01339344]
 [0.67436699 0.38563903 0.95367093 0.82752744 0.38285116 0.36496834
  0.64842211 0.66475219 0.80093754 0.92079661]
 [0.83981005 0.36943451 0.03085074 0.18451351 0.40935585 0.48056276
  0.41543065 0.91484423 0.46775272 0.84412196]
 [0.99185215 0.8460042  0.75147344 0.43392521 0.9339246  0.28332586
  0.31349055 0.57525005 0.44352733 0.88988416]
 [0.60269154 0.12487195 0.57983241 0.62863335 0.06295817 0.6367123
  0.89061615 0.08167924 0.94149806 0.18092197]
 [0.223504   0.27219099 0.53838113 0.92044988 0.003033   0.66378414
  0.24349491 0.10390543 0.64468114 0.42858808]
 [0.69900101 0.80077848 0.00473571 0.30563239 0.47583216 0.59474871
  0.80294969 

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
arr = np.zeros((5, 5))

arr[0, :] = 1
arr[-1, :] = 1

arr[:, 0] = 1
arr[:, -1] = 1

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
arr = np.ones((5, 5))

arr[0, :] = 0
arr[-1, :] = 0

arr[:, 0] = 0
arr[:, -1] = 0

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [20]:
print("0 * np.nan =",0 * np.nan)
print("np.nan == np.nan =",np.nan == np.nan)
print("np.inf > np.nan =",np.inf > np.nan)
print("np.nan - np.nan =",np.nan - np.nan)
print("np.nan in set([np.nan]) =",np.nan in set([np.nan]))
print("0.3 == 3 * 0.1 =",0.3 == 3 * 0.1)

0 * np.nan = nan
np.nan == np.nan = False
np.inf > np.nan = False
np.nan - np.nan = nan
np.nan in set([np.nan]) = True
0.3 == 3 * 0.1 = False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
arr = np.zeros(25)
arr1 = arr.reshape(5,5)
arr1[1,0] = 1
arr1[2,1] = 2
arr1[3,2] = 3
arr1[4,3] = 4
print(arr1)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
arr = np.zeros((8, 8))
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [23]:
# 8*7 + 44
# 6,7,8
# 1,0,0 = 57
# 1,5,0 = 97
# 1,5,3 = 100
# [0][5][3]
arr = np.arange(6*7*8)
arr1 = arr.reshape(6,7,8)
print(arr1)
print(arr1[1][5][3])

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [24]:
base_pattern = np.array([[0, 1], [1, 0]])

arr = np.tile(base_pattern, (4, 4))

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [25]:
nums = np.random.rand(5, 5)
col_means = np.mean(nums, axis=0)
arr_normalized = (nums - col_means) / np.std(nums, axis=0)
print("arr_normalized =",arr_normalized)

arr_normalized = [[-1.48130978  0.99392321  1.4725565   1.43303634 -0.14681638]
 [ 1.13609128 -0.67773925  0.29014073 -1.19125241  0.83722265]
 [ 0.40490936 -1.53235557 -1.36887701  0.89283164  0.90873687]
 [-0.85121163  1.09033878  0.43397193 -0.35934147 -1.84194173]
 [ 0.79152076  0.12583284 -0.82779214 -0.77527409  0.24279859]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [26]:
color_dtype = np.dtype([
    ('R', np.uint8), 
    ('G', np.uint8),  
    ('B', np.uint8), 
    ('A', np.uint8) 
])

colors = np.array([
    (255, 0, 0, 255),    
    (0, 255, 0, 128),    
    (0, 0, 255, 0)      
], dtype=color_dtype)

print(colors)
print(colors['R'])

[(255,   0,   0, 255) (  0, 255,   0, 128) (  0,   0, 255,   0)]
[255   0   0]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [27]:
x = np.random.random((5,3))
y = np.random.random((3,2))
z = np.dot(x, y)
print("x =",x)
print("y =",y)
print("z =",z)

x = [[0.2058712  0.17809643 0.39843062]
 [0.81641694 0.1224454  0.81975559]
 [0.95332718 0.96803322 0.01353552]
 [0.92049765 0.83546017 0.64273672]
 [0.88467241 0.5320156  0.00604369]]
y = [[0.65457694 0.18375621]
 [0.16934284 0.11772925]
 [0.01437187 0.70256802]]
z = [[0.17064409 0.33872189]
 [0.56692438 0.74037115]
 [0.78815002 0.29865524]
 [0.75325306 0.71907153]
 [0.66926605 0.22944396]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [29]:
arr = np.array([1,2,3,4,5,6,7,8,9])

for i in range(len(arr)):
    if arr[i] >= 3 and arr[i] <= 8:
        arr[i] = 0

print(arr)

[1 2 0 0 0 0 0 0 9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [81]:
print(sum(range(5)))
from numpy import *
print(sum(range(5),-1))

# It gives the sum of number in the range from 0 to 4

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [30]:
Z = np.array([1,2,3])
print("Z**Z =",Z**Z)
print("2 << Z >> 2 =",2 << Z >> 2)
print("Z <- Z =",Z <- Z)
print("1j*Z =",1j*Z)
print("Z/1/1 =",Z/1/1)
# print("Z<Z> =",Z<Z>) Not valid

Z**Z = [ 1  4 27]
2 << Z >> 2 = [1 2 4]
Z <- Z = [False False False]
1j*Z = [0.+1.j 0.+2.j 0.+3.j]
Z/1/1 = [1. 2. 3.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [97]:
print("np.array(0) / np.array(0) =",np.array(0) / np.array(0))
print("np.array(0) // np.array(0) =",np.array(0) // np.array(0))
print("np.array([np.nan]).astype(int).astype(float) =",np.array([np.nan]).astype(int).astype(float))

np.array(0) / np.array(0) = nan
np.array(0) // np.array(0) = 0
np.array([np.nan]).astype(int).astype(float) = [-9.22337204e+18]


C:\Users\HP\AppData\Local\Temp\ipykernel_1696\2752023512.py:1: RuntimeWarning: invalid value encountered in divide
  print("np.array(0) / np.array(0) =",np.array(0) / np.array(0))
C:\Users\HP\AppData\Local\Temp\ipykernel_1696\2752023512.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print("np.array(0) // np.array(0) =",np.array(0) // np.array(0))
C:\Users\HP\AppData\Local\Temp\ipykernel_1696\2752023512.py:3: RuntimeWarning: invalid value encountered in cast
  print("np.array([np.nan]).astype(int).astype(float) =",np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [98]:
float_array = np.array([-2.5, -1.8, 0.3, 1.5, 2.7])

rounded_array = np.sign(float_array) * np.ceil(np.abs(float_array))

print(rounded_array)

[-3. -2.  1.  2.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [99]:
ar1 = np.array([0, 1, 2, 3, 4])
ar2 = [1, 3, 4]

print(np.intersect1d(ar1, ar2))

[1 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [100]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [102]:
np.sqrt(-1) == np.emath.sqrt(-1)
# Nan == 1j

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [103]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ", yesterday)

today = np.datetime64('today', 'D')
print("Today: ", today)

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)

Yestraday:  2025-06-17
Today:  2025-06-18
Tomorrow:  2025-06-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [104]:
import datetime

year = 2016
month = 7

for day in range(1, 32):
   
    date_obj = datetime.date(year, month, day)
    print(date_obj)
    

2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [107]:
x = np.ones(2) * 1
y = np.ones(2) * 2
z = np.ones(2) * 3
np.add(x, y, out=y)
np.divide(x, 2, out=x)
np.negative(x, out=x)
np.multiply(x, y, out=z)

array([-1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [113]:
random_array = np.random.rand(5) * 10 

integer_array_int = random_array.astype(int)

integer_array_floor = np.floor(random_array).astype(int)

integer_array_trunc = np.trunc(random_array).astype(int)

integer_array_fix = np.fix(random_array).astype(int)

print("Original array:", random_array)
print("Integer array (using int()):", integer_array_int)
print("Integer array (using np.floor()):", integer_array_floor)
print("Integer array (using np.trunc()):", integer_array_trunc)
print("Integer array (using np.fix()):", integer_array_fix)

Original array: [4.95560162 8.33198795 6.10678523 0.9309351  0.33417509]
Integer array (using int()): [4 8 6 0 0]
Integer array (using np.floor()): [4 8 6 0 0]
Integer array (using np.trunc()): [4 8 6 0 0]
Integer array (using np.fix()): [4 8 6 0 0]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [115]:
x = np.zeros((5,5))
print("X before =",x)
x += np.arange(5)

print("X after =",x)

X before = [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
X after = [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [119]:
iterable = (x for x in range(10))

print(np.fromiter(iterable, dtype=int)) 

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [120]:
vector = np.linspace(0, 1, 12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [121]:
x = np.random.random(10)
x.sort()
print(x)

[0.10844881 0.24957934 0.36043548 0.36225656 0.37516931 0.41707241
 0.4184274  0.51050276 0.62796929 0.7691335 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [69]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[1,0],[0,1]])
fin = mat1*mat2
list = []
for i in range(fin.shape[0]):
    list.append(int(fin[i][i]))
list
    
                       

[1, 4]

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)