# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
# %run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.3.1


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:

import numpy as np

x = np.array([100,20,34])

print("Size of the array: ", x.size)

print("Memory size of one array element in bytes: ", x.itemsize)

print("Memory size of numpy array in bytes:", x.size * x.itemsize)

Size of the array:  3
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 24


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
import numpy as np

help(np.add)
np.info(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
vec=np.array([1,2,3,4,5])

reverse=vec[::-1]

print(reverse)

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [20]:
import numpy as np
random_matrix = np.random.randint(0,8,size=(3,3))
print(random_matrix)


[[5 6 1]
 [4 5 7]
 [3 3 0]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [32]:
a = [1,2,0,0,4,0]
ind = []
for i,v in enumerate(a):
    
    if v != 0:
        ind.append(i)
print(ind)

[0, 1, 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [37]:
import numpy as np

identity_matrix = np.identity(3)
print("The 3x3 identity matrix is :")
print(identity_matrix)


The 3x3 identity matrix is :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [38]:
import numpy as np
random_matrix = np.random.randint(0,8,size=(3,3,3))
print(random_matrix)

[[[5 3 6]
  [5 4 0]
  [7 3 1]]

 [[0 0 6]
  [2 4 0]
  [4 6 7]]

 [[0 4 4]
  [6 3 6]
  [3 7 1]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [45]:
import numpy as np
random_matrix = np.random.randint(0,8,size=(10,10))
max=-99999999
min=999999999
for i in range(10):
    for j in range(10):
        if random_matrix[i][j]>max:
            max=random_matrix[i][j]
            
    for y in range(10):
        if random_matrix[i][j]<min:
            min=random_matrix[i][j]        
        
           
print(random_matrix)            
print("Max is:", max)
print("Min is:", min)

[[0 6 2 3 2 6 5 2 6 5]
 [1 1 1 1 0 7 6 4 1 6]
 [2 5 7 0 6 4 1 4 7 0]
 [6 2 5 5 1 5 4 1 6 0]
 [0 2 7 5 1 3 7 4 2 2]
 [5 1 7 7 5 5 4 2 4 4]
 [2 4 3 1 4 6 5 4 4 2]
 [0 5 7 6 7 4 7 0 4 1]
 [1 7 3 5 6 4 6 2 2 0]
 [4 7 7 0 1 4 6 1 1 5]]
Max is: 7
Min is: 0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [54]:
import numpy as np

x= np.random.randint(0,30,size=30)
print(x)

m=np.mean(x)
print("The mean is :",m)


[ 5 25 29 20  9 14 16  4 25  3  4  8 13  0  2 15 21 23 16 14  4 13 22 24
 14 23 26 12 24 14]
The mean is : 14.733333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
x= np.random.randint(1,size=(3,3))

n=len(x)
print(n)
for i in range (3):
    for j in range (3):
        if i==0 or j==0 or i==2 or j==2:
            x[i][j]=1
          
print(x)

3
[[1 1 1]
 [1 0 1]
 [1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [104]:
import numpy as np

x = np.ones((3, 3), dtype=int)
print("Original:\n", x)

x_padded = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print("With Border:\n", x_padded)


Original:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
With Border:
 [[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [105]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [109]:
import numpy as np

values = [1, 2, 3, 4]

matrix = np.diag(values, k=-1)

print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [115]:

import numpy as np

print("Checkerboard pattern:")

x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1  
x[::2, 1::2] = 1  

print(x) 


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
import numpy as np

shape = (6, 7, 8)
index = 99 

coords = np.unravel_index(index, shape)
print(coords)


(np.int64(1), np.int64(5), np.int64(4))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [123]:

pattern = np.array([[0, 1],
                    [1, 0]])

checkerboard = np.tile(pattern, (4, 4))

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [126]:

import numpy as np


x = np.random.randint(0,8,(5, 5))

print("Original Array:")
print(x)

xmax, xmin = x.max(), x.min()

x = (x - xmin) / (xmax - xmin)

print("After normalization:")
print(x) 

Original Array:
[[1 3 7 3 2]
 [3 4 1 6 1]
 [4 2 4 6 3]
 [3 7 7 4 4]
 [0 3 1 3 7]]
After normalization:
[[0.14285714 0.42857143 1.         0.42857143 0.28571429]
 [0.42857143 0.57142857 0.14285714 0.85714286 0.14285714]
 [0.57142857 0.28571429 0.57142857 0.85714286 0.42857143]
 [0.42857143 1.         1.         0.57142857 0.57142857]
 [0.         0.42857143 0.14285714 0.42857143 1.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [128]:
import numpy as np


dtype_rgba = np.dtype([
    ('R', np.uint8), 
    ('G', np.uint8),  
    ('B', np.uint8),  
    ('A', np.uint8)  
])


colors = np.array([
    (255, 0, 0, 255),   
    (0, 255, 0, 128),    
    (0, 0, 255, 0)       
], dtype=dtype_rgba)

print(colors)


[(255,   0,   0, 255) (  0, 255,   0, 128) (  0,   0, 255,   0)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [129]:
matrix1=np.random.randint(0,8,(5, 3))
matrix2=np.random.randint(0,8,(3, 2))

prod=np.dot(matrix1,matrix2)

print(prod)

[[17 48]
 [27 12]
 [47 39]
 [31 51]
 [14 18]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [138]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr = arr[(arr > 3) & (arr < 8)]

print(arr)


[4 5 6 7]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [139]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:

# using combination of where() ciel and floor() functions

#where(condition, ciel, floor)

#### 30. How to find common values between two arrays? (★☆☆)

In [141]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8]) 
c=np.array([4, 5, 6,6,8])
common = np.intersect1d(a, b)
print(common)


[4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all='ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [142]:
import numpy as np

today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2025-07-01
Today: 2025-07-02
Tomorrow: 2025-07-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [144]:
import numpy as np

dates = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')

print(dates)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [154]:

arr = np.random.uniform(0, 10, size=5) 
print("Original array:", arr)
int_part1 = np.floor(arr).astype(int)
print("Using floor:", int_part1)
int_part2 = arr.astype(int)
print("Using astype(int):", int_part2)
int_part3 = np.trunc(arr).astype(int)
print("Using trunc:", int_part3)
fractional, int_part4 = np.modf(arr)
int_part4 = int_part4.astype(int)
print("Using modf:", int_part4)



Original array: [1.25345828 1.55381428 0.62489264 2.88298548 3.73384488]
Using floor: [1 1 0 2 3]
Using astype(int): [1 1 0 2 3]
Using trunc: [1 1 0 2 3]
Using modf: [1 1 0 2 3]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [158]:
matrix=np.random.randint(0,5,(5,5))

print(matrix)

[[3 3 0 2 4]
 [3 2 2 2 2]
 [1 1 2 1 2]
 [0 4 0 4 3]
 [1 1 4 3 2]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [159]:
import numpy as np

def gen_10_integers():
    for i in range(10):
        yield i  
        
arr = np.fromiter(gen_10_integers(), dtype=int)

print("Array from generator:", arr)


Array from generator: [0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [161]:

vec = np.linspace(0, 1, 12)[1:-1] 
print(vec)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [169]:
arr=np.random.randint(1,10,10)
narr=np.sort(arr)
print(narr)

[1 2 2 3 4 4 5 6 7 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [173]:
arr=np.random.randint(1,10,10)
print(arr)
result=np.add.reduce(arr)

print(result)

[2 9 7 3 9 1 5 5 5 2]
48


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [181]:
import numpy as np

A = np.random.randint(0, 5, size=(3, 3))
B = np.random.randint(0, 5, size=(3, 3))

if A.shape != B.shape:
    print("Arrays are not equal (different shapes).")
else:
    equal = True
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if A[i][j] != B[i][j]:
                equal = False
                break
        if not equal:
            break

    print("A:\n", A)
    print("B:\n", B)
    print("Arrays are equal:" if equal else "Arrays are not equal.")


A:
 [[0 0 2]
 [1 1 1]
 [2 4 4]]
B:
 [[3 4 2]
 [2 4 0]
 [4 4 3]]
Arrays are not equal.


#### 43. Make an array immutable (read-only) (★★☆)

In [183]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr.setflags(write=False)

print("Array:", arr)




Array: [1 2 3 4 5]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [192]:
import numpy as np


vec = np.random.randint(1,10,10)
print("Original vector:\n", vec)

max_index = np.argmax(vec)

vec[max_index] = 0

print("\nModified vector (max replaced by 0):\n", vec)


Original vector:
 [2 3 6 9 5 1 6 5 7 6]

Modified vector (max replaced by 0):
 [2 3 6 0 5 1 6 5 7 6]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [194]:
arr=np.array([1,4,7,5,8,6,4,7])

print(arr)



[1 4 7 5 8 6 4 7]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="unnamed"):
        
        obj = np.asarray(input_array).view(cls)
        
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        
        if obj is None: return
        self.name = getattr(obj, 'name', "unnamed")

a = NamedArray([1, 2, 3, 4], name="MyArray")

print("Array contents:", a)
print("Array name:", a.name)


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [197]:
import numpy as np

arr = np.random.rand(2, 3, 4, 5)

result = np.sum(arr, axis=(-2, -1))

print("Original shape:", arr.shape)
print("Result shape after summing:", result.shape)


Original shape: (2, 3, 4, 5)
Result shape after summing: (2, 3)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [196]:
vec1 = np.random.randint(1, 5, size = (2,2))
vec2 = np.random.randint(10, 50, size = (2,2))

print(np.diag(np.dot(vec1, vec2)))

[ 93 171]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [206]:

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)
    


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
print(A)
B = 2*np.ones((5,5))
print(A * B[:,:,None])



IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

#### 72. How to swap two rows of an array? (★★★)

In [223]:
A=np.ones((3,3))

for i in range(3):
    for j in range(3):
            A[0][j]=3
            

A[[0,1]] = A[[1,0]]
print(A)


[[1. 1. 1.]
 [3. 3. 3.]
 [1. 1. 1.]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

rank = np.linalg.matrix_rank(A)

print("Matrix:\n", A)
print("Rank of matrix:", rank)


Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  7 10]]
Rank of matrix: 3


#### 83. How to find the most frequent value in an array?

In [228]:
import numpy as np

arr = np.array([1, 2, 3, 4, 4, 4, 2, 2, 2, 3, 4])

counts = np.bincount(arr)    
print(counts)    
most_frequent = np.argmax(counts)    

print("Most frequent value:", most_frequent)


[0 1 4 2 4]
Most frequent value: 2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [229]:


arr = np.array([10, 20, 5, 8, 70, 30])
n = 3

largest_n = np.sort(arr)[-n:]  

print("Top", n, "largest values:", largest_n)


Top 3 largest values: [20 30 70]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)