# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
# %run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
print(np.show_config())

2.2.5
Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.12
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/qn/7t0vq3ts721cmgt0tgrtgzl80000gn/T/build-en

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
x = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
x.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` 

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
null_v = np.zeros(10)
null_v[4] = 1
null_v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
v= np.array([1, 2, 3, 4, 5])
rev = v[::-1]
print(rev)

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
arr = np.arange(9)
matrix_3x3 = arr.reshape(3, 3)
matrix_3x3


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
arr = np.array([1,2,0,0,4,0])
idx = np.nonzero(arr)
print(idx)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
arr = np.random.random((3, 3, 3))
arr

array([[[0.6547862 , 0.06030384, 0.65959164],
        [0.62977068, 0.7465376 , 0.756497  ],
        [0.65412139, 0.21104623, 0.72215508]],

       [[0.92513452, 0.59424569, 0.97087282],
        [0.12072942, 0.31137598, 0.1111549 ],
        [0.65676016, 0.5685629 , 0.04935929]],

       [[0.7825374 , 0.01252752, 0.1594614 ],
        [0.43525624, 0.71739052, 0.33680331],
        [0.77677041, 0.20553226, 0.11096052]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
rand = np.random.randint(0, 100, size=(10, 10))
min = np.min(rand)
max = np.max(rand)
rand, min, max

(array([[78, 24, 58, 78,  8, 49, 58, 68, 55, 14],
        [91, 22, 97, 26,  7, 53, 33,  0, 92, 32],
        [23, 53, 94,  6, 82, 18, 76, 26, 61, 19],
        [95,  8, 27, 87,  6, 51, 13,  5, 96, 17],
        [32, 72, 89, 98, 21, 86, 65, 75, 63, 45],
        [78, 83, 44, 12, 92, 32, 93, 53, 15, 49],
        [ 6, 81, 18, 72, 37, 63, 82, 39, 44, 34],
        [35, 58, 54, 61, 31,  3, 72, 64, 21, 71],
        [23, 93, 24, 89, 24, 88, 31, 77, 99, 72],
        [49, 94, 54, 67,  2, 37,  1, 87,  6, 20]]),
 np.int64(0),
 np.int64(99))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
v = np.random.rand(30)
mean = np.mean(v)
mean

np.float64(0.5256654248828088)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
x = np.ones((5, 5))
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
x = np.ones((4, 4))
x = np.pad(x, 1)
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
matrix = np.zeros((5, 5))
values = np.array([1, 2, 3, 4])
matrix[1:, :-1] = np.diag(values)
matrix


array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [27]:
arr1 = np.zeros((8,8))
arr1[1::2, ::2] = 1
arr1[::2, 1::2] = 1
arr1

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [32]:
arr1 = np.empty((6,7,8))
idx = np.unravel_index(100, arr1.shape)
idx


np.float64(3.597e-321)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [33]:
arr2 = np.tile([[0,1],[1,0]], (4,4))
arr2


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
arr3 = np.random.rand(5,5)
arr3 = (arr3 - arr3.min()) / (arr3.max() - arr3.min())
arr3


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [36]:
arr4 = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])
arr4


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [37]:
arr5 = np.random.rand(5,3)
arr6 = np.random.rand(3,2)
arr7 = np.dot(arr5, arr6)
arr7


array([[1.26025443, 1.29906249],
       [1.0751115 , 0.89449373],
       [0.89168308, 0.75921137],
       [0.68987559, 0.73000626],
       [0.59599893, 0.69741635]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [38]:
arr8 = np.arange(10)
arr8[(arr8 > 3) & (arr8 < 8)] *= -1
arr8


array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [39]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [43]:
#Legal
arr1 = np.arange(5)
arr2 = arr1 ** arr1
arr3 = 2 << arr1 >> 2
arr4 = 1j * arr1
arr5 = arr1 / 1 / 1
arr2, arr3, arr4, arr5

#Not legal
#Z <- Z
#Z<Z>


(array([  1,   1,   4,  27, 256]),
 array([0, 1, 2, 4, 8]),
 array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j]),
 array([0., 1., 2., 3., 4.]))

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [48]:
# arr6 = np.array(0) / np.array(0) UNDEFINED
# arr7 = np.array(0) // np.array(0) UNDEFINED
arr8 = np.array([np.nan]).astype(int).astype(float)
arr8


array([0.])

#### 29. How to round away from zero a float array ? (★☆☆)

In [45]:
arr9 = np.array([1.2, -1.5, 2.6, -3.7])
arr10 = np.copysign(np.ceil(np.abs(arr9)), arr9)
arr10


array([ 2., -2.,  3., -4.])

#### 30. How to find common values between two arrays? (★☆☆)

In [46]:
arr11 = np.array([1, 2, 3, 4, 5])
arr12 = np.array([4, 5, 6, 7, 8])
arr13 = np.intersect1d(arr11, arr12)
arr13


array([4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [47]:
import warnings
warnings.filterwarnings('ignore')
np.seterr(all='ignore')


{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [50]:
X = np.sqrt(-1) == np.emath.sqrt(-1)
X


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [51]:
arr2 = np.datetime64('today', 'D')
arr3 = arr2 - np.timedelta64(1, 'D')
arr4 = arr2 + np.timedelta64(1, 'D')
arr3, arr2, arr4


(np.datetime64('2025-06-17'),
 np.datetime64('2025-06-18'),
 np.datetime64('2025-06-19'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [22]:
start = np.datetime64('2016-07-01')
end = np.datetime64('2016-08-01')
dates = np.arange(start, end, dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [23]:
A = np.array([1.0, 2.0, 3.0])
B = np.array([4.0, 5.0, 6.0])
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A) 
np.multiply(B, A, out=A)
print(A)

[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [24]:
random_array = np.random.rand(5) * 10 
integer_array = np.floor(random_array)
print(integer_array)


integer_array = np.trunc(random_array)
print(integer_array)


integer_array = random_array.astype(int)
print(integer_array)


integer_array = np.array([int(x) for x in random_array])
print(integer_array)


[9. 6. 5. 9. 5.]
[9. 6. 5. 9. 5.]
[9 6 5 9 5]
[9 6 5 9 5]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [25]:
arr = np.zeros((5,5))
matrix_5x5 = arr+np.arange(5)
matrix_5x5


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [54]:
def gen():
    for i in range(10):
        yield i
arr1 = np.fromiter(gen(), dtype=int)
arr1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [55]:
arr2 = np.linspace(0, 1, 12)[1:-1]
arr2


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [56]:
arr3 = np.random.rand(10)
arr3.sort()
arr3


array([0.06234697, 0.10110031, 0.27170874, 0.34044243, 0.54210145,
       0.54289783, 0.58823207, 0.65509287, 0.67079004, 0.96557773])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [57]:
arr4 = np.arange(10)
arr5 = sum(arr4)
arr5


np.int64(45)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [58]:
arr1 = np.random.rand(5)
arr2 = np.random.rand(5)
arr3 = np.array_equal(arr1, arr2)
arr3


False

#### 43. Make an array immutable (read-only) (★★☆)

In [61]:
arr4 = np.arange(10)
arr4.flags.writeable = False
# arr4[0] = 6 gives errorr


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [62]:
arr5 = np.random.rand(10,2)
arr6 = np.sqrt(arr5[:,0]**2 + arr5[:,1]**2)
arr7 = np.arctan2(arr5[:,1], arr5[:,0])
arr6, arr7


(array([0.83881425, 0.57427057, 1.00159859, 0.9017989 , 0.7560315 ,
        1.09902653, 1.13761976, 1.04129065, 0.78589793, 0.83427589]),
 array([0.87098953, 0.23449997, 0.21558837, 1.14849763, 0.67694298,
        0.72708879, 0.85160851, 0.69331012, 0.26770152, 0.86554468]))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [63]:
arr8 = np.random.rand(10)
arr8[arr8.argmax()] = 0
arr8


array([0.19091023, 0.28867538, 0.        , 0.53582454, 0.83008297,
       0.27264502, 0.50309365, 0.81768998, 0.09711904, 0.3248362 ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [64]:
arr9 = np.zeros((5,5), dtype=[('x', float), ('y', float)])
arr9['x'], arr9['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
arr9


array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [65]:
arr0 = np.random.rand(8)
arr1 = np.random.rand(8)
arr2 = 1 / (arr0[:,None]-arr1)
arr2


array([[  1.95016862,   5.47541255,   5.86247679, -42.33313318,
        -42.14263885,   1.42165686,   6.30790487,   1.39945982],
       [ -9.20224813,  -2.27888736,  -2.21793961,  -1.55022553,
         -1.54996897,  12.201171  ,  -2.16022834,  10.73927564],
       [-17.06202765,  -2.57233923,  -2.49495093,  -1.68064963,
         -1.68034809,   7.57468089,  -2.42216018,   6.98443195],
       [  2.00796571,   5.95681529,   6.4177987 , -26.05397397,
        -25.98169343,   1.45212718,   6.95547944,   1.4289762 ],
       [ -6.82376453,  -2.09780729,  -2.04605054,  -1.46424674,
         -1.46401784,  22.68511482,  -1.99683859,  18.10329172],
       [  3.63642123, -18.13371819, -14.88003119,  -3.82551538,
         -3.82395337,   2.14765521, -12.61841031,   2.09739949],
       [ -3.06957645,  -1.52457761,  -1.49705608,  -1.15985575,
         -1.15971213,  -7.39921892,  -1.47053898,  -8.06499764],
       [-13.51789939,  -2.47452768,  -2.40283075,  -1.6383389 ,
         -1.63805235,   8.5724729

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [66]:
arr1 = [(t, np.iinfo(t).min, np.iinfo(t).max) for t in [np.int8, np.int16, np.int32, np.int64]]
arr2 = [(t, np.finfo(t).min, np.finfo(t).max) for t in [np.float32, np.float64]]
arr1, arr2


([(numpy.int8, -128, 127),
  (numpy.int16, -32768, 32767),
  (numpy.int32, -2147483648, 2147483647),
  (numpy.int64, -9223372036854775808, 9223372036854775807)],
 [(numpy.float32, np.float32(-3.4028235e+38), np.float32(3.4028235e+38)),
  (numpy.float64,
   np.float64(-1.7976931348623157e+308),
   np.float64(1.7976931348623157e+308))])

#### 49. How to print all the values of an array? (★★☆)

In [68]:
arr3 = np.random.rand(10)
np.set_printoptions(threshold=np.inf)
arr3


array([0.62092356, 0.13011729, 0.34778429, 0.17348198, 0.45193526,
       0.55761908, 0.66952313, 0.31944457, 0.71444108, 0.39409738])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [69]:
arr4 = np.random.rand(10)
val = 0.5
arr5 = arr4[np.abs(arr4 - val).argmin()]
arr5


np.float64(0.44626737283882745)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [70]:
arr6 = np.zeros(10, dtype=[('position', [('x', float), ('y', float)]), ('color', [('r', float), ('g', float), ('b', float)])])
arr6


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [71]:
arr7 = np.random.rand(100, 2)
arr8 = np.sqrt(((arr7[:, None, :] - arr7[None, :, :]) ** 2).sum(axis=2))
arr8


array([[0.        , 0.24049146, 0.37934565, 0.33063701, 0.04853809,
        0.49520962, 0.38054027, 0.48671515, 0.46317955, 0.42283056,
        0.45157576, 0.1666561 , 0.39330207, 0.29489172, 0.42224699,
        0.71219988, 0.55059907, 0.40257237, 0.11898743, 0.55129597,
        0.46741467, 0.41542255, 0.68987851, 0.52208672, 0.51310762,
        0.41694303, 0.36211693, 0.167529  , 0.72890034, 0.35157989,
        0.38843443, 0.29507682, 0.21584066, 0.62049187, 0.3894539 ,
        0.18569766, 0.62451137, 0.18394191, 0.25465446, 0.18598554,
        0.12459678, 0.29307841, 0.67867355, 0.62423697, 0.46454397,
        0.24108282, 0.55976973, 0.52988408, 0.21798622, 0.53772052,
        0.24818432, 0.39893284, 0.44646641, 0.3795029 , 0.32500877,
        0.51669357, 0.38991653, 0.19541893, 0.11831979, 0.37597451,
        0.50913646, 0.36068135, 0.32926988, 0.30415231, 0.10952944,
        0.20619965, 0.47171146, 0.24156621, 0.69134308, 0.56274259,
        0.2927142 , 0.37611562, 0.66086311, 0.51

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [72]:
arr9 = np.arange(10, dtype=np.float32)
arr9[:] = arr9.astype(np.int32)
arr9


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
#assume file is file.txt
arr1 = np.genfromtxt('file.txt', delimiter=",", filling_values=np.nan)
arr1


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [73]:
arr2 = np.arange(9).reshape(3,3)
arr3 = [(index, value) for index, value in np.ndenumerate(arr2)]
arr3


[((0, 0), np.int64(0)),
 ((0, 1), np.int64(1)),
 ((0, 2), np.int64(2)),
 ((1, 0), np.int64(3)),
 ((1, 1), np.int64(4)),
 ((1, 2), np.int64(5)),
 ((2, 0), np.int64(6)),
 ((2, 1), np.int64(7)),
 ((2, 2), np.int64(8))]

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [74]:
x, y = np.meshgrid(np.linspace(-1,1,100), np.linspace(-1,1,100))
arr4 = np.exp(-(x**2+y**2))
arr4


array([[0.13533528, 0.14085785, 0.14648615, 0.15221505, 0.15803895,
        0.16395179, 0.16994709, 0.17601788, 0.18215679, 0.188356  ,
        0.19460727, 0.20090196, 0.20723103, 0.21358508, 0.21995435,
        0.22632873, 0.23269784, 0.23905098, 0.2453772 , 0.25166533,
        0.257904  , 0.26408169, 0.27018673, 0.27620736, 0.28213176,
        0.28794811, 0.29364458, 0.29920941, 0.30463095, 0.30989768,
        0.31499823, 0.3199215 , 0.32465661, 0.32919299, 0.33352041,
        0.33762902, 0.34150937, 0.34515247, 0.34854983, 0.35169343,
        0.35457586, 0.35719023, 0.35953029, 0.36159042, 0.36336564,
        0.36485164, 0.36604482, 0.36694226, 0.36754178, 0.36784191,
        0.36784191, 0.36754178, 0.36694226, 0.36604482, 0.36485164,
        0.36336564, 0.36159042, 0.35953029, 0.35719023, 0.35457586,
        0.35169343, 0.34854983, 0.34515247, 0.34150937, 0.33762902,
        0.33352041, 0.32919299, 0.32465661, 0.3199215 , 0.31499823,
        0.30989768, 0.30463095, 0.29920941, 0.29

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [75]:
n, p = 10, 5
arr5 = np.zeros((n, n), dtype=int)
arr5.flat[np.random.choice(arr5.size, p, replace=False)] = 1
arr5


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [76]:
arr6 = np.random.rand(5, 5)
arr7 = arr6 - arr6.mean(axis=1, keepdims=True)
arr7


array([[-0.14642014,  0.1581426 , -0.40734563,  0.18389112,  0.21173205],
       [ 0.10956015,  0.24883723, -0.2819111 , -0.0880049 ,  0.01151862],
       [ 0.31710007, -0.2717945 , -0.16049825,  0.10901042,  0.00618226],
       [ 0.53553204, -0.23395649, -0.43810673, -0.26167494,  0.39820613],
       [-0.29628617,  0.26599878,  0.36093774, -0.08545603, -0.24519432]])

#### 59. How to sort an array by the nth column? (★★☆)

In [77]:
arr8 = np.random.randint(0, 100, (5, 5))
arr9 = arr8[arr8[:, 2].argsort()]
arr9


array([[72,  6, 21, 50, 84],
       [70, 15, 50, 85, 99],
       [27, 88, 51, 85, 51],
       [ 1,  7, 67, 12, 89],
       [67, 13, 97, 49, 30]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [78]:
arr1 = np.random.rand(5, 5)
arr1[:, 2] = 0
arr2 = np.all(arr1 == 0, axis=0)
arr2


array([False, False,  True, False, False])

#### 61. Find the nearest value from a given value in an array (★★☆)

In [79]:
arr3 = np.random.rand(10)
val = 0.4
arr4 = arr3[np.abs(arr3 - val).argmin()]
arr4


np.float64(0.37725848904435655)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [80]:
arr5 = np.arange(3).reshape(1,3)
arr6 = np.arange(3).reshape(3,1)
it = np.nditer([arr5, arr6, None])
arr7 = np.empty((3,3))
for x, y, z in it:
    z[...] = x + y
arr7 = it.operands[2]
arr7


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### 63. Create an array class that has a name attribute (★★☆)

In [81]:
class Arr(np.ndarray):
    def __new__(cls, input_array, name="no_name"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

arr8 = Arr(np.arange(10), name="my_array")
arr8


Arr([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [82]:
arr9 = np.zeros(5, dtype=int)
arr10 = np.array([1, 1, 2, 3])
np.add.at(arr9, arr10, 1)
arr9


array([0, 2, 1, 1, 0])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [83]:
arr11 = np.array([1, 2, 3, 4])
arr12 = np.array([0, 1, 0, 1])
arr13 = np.zeros(2, dtype=int)
np.add.at(arr13, arr12, arr11)
arr13


array([4, 6])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [84]:
arr1 = np.random.randint(0, 256, (100, 100, 3), dtype=np.uint8)
arr2 = arr1.reshape(-1, 3)
arr3 = np.unique(arr2, axis=0)
arr4 = len(arr3)
arr4


9998

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [85]:
arr5 = np.random.rand(2, 3, 4, 5)
arr6 = arr5.sum(axis=(-2, -1))
arr6


array([[ 8.0980026 , 10.8143968 , 10.48784569],
       [ 8.78415344, 10.45090851, 11.60183401]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [86]:
arr7 = np.random.rand(10)
arr8 = np.random.randint(0, 3, 10)
arr9 = np.bincount(arr8, weights=arr7) / np.bincount(arr8)
arr9


array([0.4428998 , 0.40860922, 0.52343345])

#### 69. How to get the diagonal of a dot product? (★★★)

In [87]:
arr10 = np.random.rand(5, 5)
arr11 = np.random.rand(5, 5)
arr12 = np.einsum("ij,ji->i", arr10, arr11)
arr12


array([0.37014868, 1.72162832, 0.93976513, 1.4884307 , 1.46196027])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [88]:
arr13 = np.array([1, 2, 3, 4, 5])
arr14 = np.zeros(len(arr13) * 4 - 3, dtype=int)
arr14[::4] = arr13
arr14


array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [89]:
arr1 = np.random.rand(5, 5, 3)
arr2 = np.random.rand(5, 5)
arr3 = arr1 * arr2[:, :, np.newaxis]
arr3


array([[[0.39105207, 0.462643  , 0.21025259],
        [0.03868123, 0.10610896, 0.0317287 ],
        [0.16483253, 0.20941641, 0.75279124],
        [0.33827341, 0.3463884 , 0.43293797],
        [0.11744061, 0.04090111, 0.16080507]],

       [[0.0756605 , 0.18538158, 0.12759594],
        [0.40966048, 0.50589171, 0.28438885],
        [0.37855107, 0.28812199, 0.55972518],
        [0.15471897, 0.09845743, 0.14271324],
        [0.35034673, 0.13328506, 0.16410454]],

       [[0.41965445, 0.2901424 , 0.44624563],
        [0.32847231, 0.33490248, 0.37996922],
        [0.15770073, 0.68592002, 0.53075406],
        [0.06618759, 0.0574024 , 0.37707494],
        [0.15599525, 0.19187886, 0.54146202]],

       [[0.44368601, 0.22001332, 0.43081385],
        [0.00424713, 0.02105488, 0.04191159],
        [0.41189686, 0.16938223, 0.12297998],
        [0.38094094, 0.31916511, 0.13118717],
        [0.09258408, 0.01484726, 0.01126982]],

       [[0.30388473, 0.56139768, 0.82854732],
        [0.65972375, 0.050

#### 72. How to swap two rows of an array? (★★★)

In [90]:
arr4 = np.arange(25).reshape(5, 5)
arr4[[0, 1]] = arr4[[1, 0]]
arr4


array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [91]:
arr8 = np.array([0, 2, 3])
arr9 = np.repeat(np.arange(len(arr8)), arr8)
arr9


array([1, 1, 2, 2, 2])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [92]:
arr10 = np.arange(10)
window = 3
arr11 = np.convolve(arr10, np.ones(window)/window, mode='valid')
arr11


array([1., 2., 3., 4., 5., 6., 7., 8.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [93]:
arr12 = np.arange(1, 15)
arr13 = np.lib.stride_tricks.sliding_window_view(arr12, 4)
arr13


array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [94]:
arr14 = np.array([True, False, True])
arr14 ^= True
arr15 = np.array([1.0, -2.0, 3.0])
arr15 *= -1
arr14, arr15


(array([False,  True, False]), array([-1.,  2., -3.]))

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [95]:
arr16 = np.random.rand(10, 2)
arr17 = np.random.rand(10, 2)
p = np.random.rand(2)
arr18 = np.abs(np.cross(arr17 - arr16, arr16 - p)) / np.linalg.norm(arr17 - arr16, axis=1)
arr18


array([0.59331706, 0.32580587, 0.46320256, 0.05085571, 0.27914263,
       0.16060536, 0.43759476, 0.31507706, 0.234833  , 0.06719472])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [97]:
arr25 = np.arange(1, 15)
arr26 = np.lib.stride_tricks.sliding_window_view(arr25, 4)
arr26


array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★)

In [98]:
arr27 = np.random.rand(5, 5)
arr28 = np.linalg.matrix_rank(arr27)
arr28


np.int64(5)

#### 83. How to find the most frequent value in an array?

In [99]:
arr1 = np.random.randint(0, 10, 100)
arr2 = np.bincount(arr1)
arr3 = np.argmax(arr2)
arr3


np.int64(8)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [100]:
arr4 = np.random.rand(10, 10)
arr5 = np.lib.stride_tricks.sliding_window_view(arr4, (3, 3))
arr5


array([[[[0.60588535, 0.66223537, 0.59566468],
         [0.5659322 , 0.37516775, 0.17783814],
         [0.8153315 , 0.84582898, 0.17196041]],

        [[0.66223537, 0.59566468, 0.76621881],
         [0.37516775, 0.17783814, 0.29125638],
         [0.84582898, 0.17196041, 0.65627101]],

        [[0.59566468, 0.76621881, 0.41450195],
         [0.17783814, 0.29125638, 0.26178357],
         [0.17196041, 0.65627101, 0.07920967]],

        [[0.76621881, 0.41450195, 0.63198086],
         [0.29125638, 0.26178357, 0.68309594],
         [0.65627101, 0.07920967, 0.74023618]],

        [[0.41450195, 0.63198086, 0.40788429],
         [0.26178357, 0.68309594, 0.47443022],
         [0.07920967, 0.74023618, 0.49624632]],

        [[0.63198086, 0.40788429, 0.07464307],
         [0.68309594, 0.47443022, 0.20110603],
         [0.74023618, 0.49624632, 0.69226853]],

        [[0.40788429, 0.07464307, 0.40094729],
         [0.47443022, 0.20110603, 0.10437289],
         [0.49624632, 0.69226853, 0.20994804]],


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [101]:
p, n = 10, 4
arr7 = np.random.rand(p, n, n)
arr8 = np.random.rand(p, n, 1)
arr9 = np.sum(np.matmul(arr7, arr8), axis=0)
arr9


array([[10.24402189],
       [11.54753508],
       [10.66844768],
       [10.9977112 ]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [102]:
arr10 = np.random.rand(16, 16)
arr11 = arr10.reshape(4, 4, 4, 4).sum(axis=(2, 3))
arr11


array([[ 7.73505013,  7.86384029,  9.11652911,  7.45137048],
       [ 8.52344157,  7.0599855 ,  9.18151356,  9.74672824],
       [ 8.61927047,  7.75613966,  9.1782259 ,  9.13919743],
       [ 7.58636321, 10.109711  ,  8.37746305,  6.28831998]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [103]:
arr14 = np.random.rand(100)
n = 5
arr15 = np.sort(arr14)[-n:]
arr15


array([0.97032644, 0.9720434 , 0.98041103, 0.98162285, 0.99920003])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [106]:
arr1 = [np.array([1, 2]), np.array([3, 4]), np.array([5, 6])]
arr2 = np.array(np.meshgrid(*arr1)).T.reshape(-1, len(arr1))
arr2


array([[1, 3, 5],
       [1, 4, 5],
       [2, 3, 5],
       [2, 4, 5],
       [1, 3, 6],
       [1, 4, 6],
       [2, 3, 6],
       [2, 4, 6]])

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [109]:
arr5 = np.arange(10)
arr6 = arr5 ** 3
arr7 = np.power(arr5, 3)
arr8 = arr5 * arr5 * arr5
arr6, arr7, arr8


(array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729]),
 array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729]),
 array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729]))

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [110]:
arr9 = np.random.randint(0, 5, (8, 3))
arr10 = np.random.randint(0, 5, (2, 2))
arr11 = np.array([row for row in arr9 if any(np.all(np.isin(b_row, row)) for b_row in arr10)])
arr11


array([[1, 2, 1],
       [0, 4, 1],
       [1, 0, 1],
       [0, 1, 0],
       [4, 2, 4],
       [0, 2, 0],
       [4, 0, 1],
       [4, 0, 4]])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [111]:
arr12 = np.random.randint(0, 5, (10, 3))
arr13 = arr12[~np.all(arr12[:, 0][:, None] == arr12, axis=1)]
arr13


array([[1, 3, 2],
       [3, 1, 0],
       [3, 1, 2],
       [0, 4, 0],
       [4, 2, 1],
       [4, 3, 2],
       [1, 3, 3],
       [1, 4, 3],
       [3, 3, 0]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [112]:
arr14 = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr15 = ((arr14[:, None] & (1 << np.arange(8))) > 0).astype(int)
arr15


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0]])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [113]:
arr1 = np.random.randint(0, 5, (10, 3))
arr2 = np.unique(arr1, axis=0)
arr2


array([[0, 1, 0],
       [0, 1, 4],
       [0, 2, 2],
       [0, 3, 1],
       [1, 0, 1],
       [1, 3, 0],
       [3, 1, 1],
       [3, 1, 2],
       [3, 4, 3],
       [4, 2, 0]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [114]:
arr3 = np.array([1, 2, 3])
arr4 = np.array([4, 5, 6])
arr5 = np.einsum('i,i->', arr3, arr4)
arr6 = np.einsum('i,j->ij', arr3, arr4)
arr7 = np.einsum('i->', arr3)
arr8 = np.einsum('i,i->i', arr3, arr4)
arr5, arr6, arr7, arr8


(np.int64(32),
 array([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]]),
 np.int64(6),
 array([ 4, 10, 18]))

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [115]:
n = 10
arr18 = np.random.randint(0, 5, (10, 5))
arr19 = arr18[np.all(arr18 == arr18.astype(int), axis=1) & (arr18.sum(axis=1) == n)]
arr19


array([], shape=(0, 5), dtype=int64)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)