# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
run initialise.py

Exception: File `'initialise.py'` not found.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

1.26.4


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
null_vec=np.zeros(10)
null_vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [13]:
arr=np.array([[1,2,3],[4,5,6]])
m_size=arr.nbytes
m_size


24

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [20]:
help(np.add)
#python -m pydoc numpy.add

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [21]:
null_vec=np.zeros(10)
null_vec[4]=1
null_vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [23]:
arr=np.array(range(10,49))
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [24]:
arr=np.array(range(10,49))
arr=np.flip(arr)
arr

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [28]:
arr=np.array([(range(0,8),range(0,8),range(0,8))])
arr

array([[[0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7]]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [34]:
arr=np.array([1,2,0,0,4,0])
lst=[]
for i,x in np.ndenumerate(arr):
    if x>0:
        lst.append(i)
lst        
        

[(0,), (1,), (4,)]

#### 11. Create a 3x3 identity matrix (★☆☆)

In [35]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [51]:
arr=np.random.random((3,3,3))*10
arr

array([[[5.64612386, 0.54592412, 7.409695  ],
        [7.05805668, 1.78069827, 3.03806465],
        [3.22551524, 0.06194588, 7.90201995]],

       [[3.04009262, 3.68976907, 0.70762925],
        [6.20459614, 3.88013879, 7.82675669],
        [4.47246931, 8.48521604, 4.60596112]],

       [[5.27474663, 8.7586755 , 5.76353843],
        [7.37845197, 0.65814068, 3.97599139],
        [6.23858162, 4.24164309, 1.16818474]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [52]:
arr=np.random.random((10,10))
min1=arr.min()
max1=arr.max()
print(min1,max1)

0.0007697779021894613 0.9950215157749752


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [55]:
arr=np.random.random(30)*100
mean=arr.mean()
mean

46.24693242634496

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [61]:
np.nan in set([np.nan])

True

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
'''
nan
false
false
nan
True
False
'''

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [198]:
z=np.array([1,2,3,4,5])
if z>3 and z<8:
    z=-z
z    

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [196]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

TypeError: 'numpy.float64' object is not callable

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [194]:
z=np.array([1,2,3,4,5])
#legal
#legal
#legal
#legal
#legal
#illegal

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [188]:
#nan
#0
#-2.14

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [184]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([1,3,4,8,9])
common=np.intersect1d(array1, array2)
common

array([1, 3, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
#np.seterr(all='ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [181]:
#ITS FALSE

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [179]:
yesterday=np.datetime64('today')-np.timedelta64(1)
today= np.datetime64('today')
tomorrow=np.datetime64('today')+np.timedelta64(1)
tomorrow

numpy.datetime64('2025-06-21')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [66]:
date1 = np.datetime64('2016-07-01')
date2 = np.datetime64('2016-08-01')
date3=np.arange(date1,date2)
date3

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [174]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
add=np.add(arr1,arr2)
arr1N=np.negative(arr1)
div=np.divide(arr1N,2)
res=np.multiply(add,div)
res

array([ -2.5,  -7. , -13.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
arr=np.random.random(30)*100


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
arr=

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [73]:
def gen():
    for i in range(10):
        yield i*420
arr=np.fromiter(gen(),dtype=int)    
arr

array([   0,  420,  840, 1260, 1680, 2100, 2520, 2940, 3360, 3780])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [77]:
arr=np.random.random(10)*100
arr.sort()
arr

array([ 4.29478418,  6.47493353, 17.88039979, 21.05212731, 44.81667824,
       56.08728003, 56.54780711, 75.86750076, 80.60598778, 96.17924418])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [74]:
arr=np.random.random(30)*100
sum=0
for i in arr:
    sum +=i
sum    

1540.4213426236572

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [75]:
arr=np.random.random(30)*100
arr2=np.random.random(30)*100
np.array_equal(arr,arr2)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [91]:
arr=np.random.random(30)*100
arr.flags.writeable=False
arr[1]=10

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [81]:
arr=np.random.random(10)*100
lst=[]
max=0
maxI=0
arr.sort()
for i,x in np.ndenumerate(arr):
    if x>max:
        max=x
        maxI=i
arr[maxI]=0      
arr

array([ 8.48882123, 14.89462731, 26.71700039, 51.34934585, 55.8240377 ,
       69.15201774, 84.71906412, 85.53480401, 91.95472681,  0.        ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [69]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6, 7])
x_col=np.reshape(-1,1)
y_row=np.reshape(1,-1)
caucthy=1.0/(x_col-y_row)
caucthy

array([-0.5])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [82]:
np.iinfo(int)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [87]:
np.finfo(float)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

#### 49. How to print all the values of an array? (★★☆)

In [88]:
y = np.array([4, 5, 6, 7])
print(y)

[4 5 6 7]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [172]:
arr=np.array(('position',(1,2)),('colour',('r','g','b')))
arr

TypeError: data type 'colour' not understood

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [100]:
float_array=np.array([1.1,3.2,4.4,5.4])
float_array.astype(np.int32)
float_array.dtype

dtype('float64')

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [67]:
arr=np.array([1,2,0,0,4,0])
lst=[]
for i,x in np.ndenumerate(arr):
    if x>0:
        lst.append(i)
lst        
   

[(0,), (1,), (4,)]

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [90]:
x,y=np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d=np.sqrt(x*x + y*y)
sigma,mu=1.0,0.0
g=np.exp((-((d-mu)**2/ 2.0*sigma**2)))
g

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [224]:
arr=np.random.rand(3,3)
p=3
np.put(arr, np.random.choice(range(2*2),p,replace=False),1)
arr

array([[1.        , 1.        , 1.        ],
       [0.44169344, 0.48552878, 0.1061937 ],
       [0.36912342, 0.77442704, 0.55248893]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [121]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
row_means=np.mean(matrix, axis=1, keepdims=True)
new_matrix=matrix-row_means
new_matrix

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

#### 59. How to sort an array by the nth column? (★★☆)

In [205]:
arr=np.random.rand(3,3)
arr
n=2
arr[arr[:,n].argsort()]
arr

array([[0.91531746, 0.65212022, 0.04063082],
       [0.65097728, 0.779093  , 0.64526081],
       [0.47748799, 0.68309818, 0.25019877]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [116]:
arr=np.random.randint(0,3,(3,10))
np.all(arr == 0, axis=0)

array([False, False, False, False, False, False, False, False, False,
       False])

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [122]:
arr1d = np.array([1, 2, 3])
arr2d = np.array([[4], [7], [8]])
arr2d=arr2d.reshape(-1,1)
arr1d+arr2d

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [ 9, 10, 11]])

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
def name_array(np.ndarray)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [245]:
arr=np.random.rand(3,3)*1000
arr2=np.random.rand(3,3)*1000
arr3=arr+np.bincount(arr2, minlength=len(arr))
arr3

ValueError: object too deep for desired array

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [142]:
arr=np.random.rand(5, 5, 3)
arr2=np.random.rand(5,5)
arr2=arr2[:,:,None]
arr*arr2

array([[[0.01220523, 0.04336999, 0.10122726],
        [0.18801857, 0.72485915, 0.02654564],
        [0.03062231, 0.03095097, 0.01709066],
        [0.09857425, 0.38513239, 0.37541319],
        [0.33875058, 0.34933902, 0.26636302]],

       [[0.00558978, 0.17008442, 0.01164459],
        [0.39737407, 0.37790976, 0.00212271],
        [0.25596664, 0.04742463, 0.11107466],
        [0.02128872, 0.01512036, 0.08511994],
        [0.70507478, 0.36150765, 0.44796378]],

       [[0.13112273, 0.260831  , 0.00826065],
        [0.00491132, 0.10473561, 0.01353088],
        [0.15801256, 0.21561647, 0.1395767 ],
        [0.05456566, 0.10980749, 0.08755184],
        [0.14106554, 0.08679067, 0.15733637]],

       [[0.07083787, 0.41112955, 0.45203016],
        [0.24607083, 0.01173804, 0.09262134],
        [0.10203336, 0.2294071 , 0.00136916],
        [0.05646328, 0.4182736 , 0.09968115],
        [0.39045635, 0.19367184, 0.27510865]],

       [[0.17211758, 0.28718301, 0.10848519],
        [0.07350889, 0.182

#### 72. How to swap two rows of an array? (★★★)

In [107]:
arr=([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
temp=arr[1].copy()
arr[1]=arr[2].copy()
arr[2]=temp
arr

[[1, 2, 3], [7, 8, 9], [4, 5, 6], [10, 11, 12]]

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [126]:
c= np.array([2, 0, 3, 1])
indices=np.arange(len(c))
arr=np.repeat(indices,c)
arr

array([0, 0, 2, 2, 2, 3])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [131]:
from numpy.lib.stride_tricks import sliding_window_view
arr=np.array([1,2,3,4,5,6,7])
view=3
arr2=sliding_window_view(arr,window_shape=view)
arr2.mean(axis=1)

array([2., 3., 4., 5., 6.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [101]:
flag=True
flag=not True
flag

False

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [228]:
arr=[1,2,3,4,5,6,7,8,9,10,11,12,13,14]
arr2=sliding_window_view(arr, window_shape=4)
arr2

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★)

In [108]:
arr=([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
rank=np.linalg.matrix_rank(arr)
rank

2

#### 83. How to find the most frequent value in an array?

In [232]:
arr=np.array([1,2,3,4,5,5,5])
np.bincount(arr).argmax()

5

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [164]:
arr=np.random.rand(10, 10)
view=(3,3)
arr2=sliding_window_view(arr,window_shape=view)
arr2


array([[[[0.04808911, 0.24417772, 0.57193848],
         [0.22122732, 0.78627207, 0.9080599 ],
         [0.44002103, 0.03921744, 0.37242502]],

        [[0.24417772, 0.57193848, 0.60618863],
         [0.78627207, 0.9080599 , 0.49847403],
         [0.03921744, 0.37242502, 0.76521214]],

        [[0.57193848, 0.60618863, 0.34570867],
         [0.9080599 , 0.49847403, 0.60562913],
         [0.37242502, 0.76521214, 0.97094719]],

        [[0.60618863, 0.34570867, 0.8518089 ],
         [0.49847403, 0.60562913, 0.85964016],
         [0.76521214, 0.97094719, 0.22989766]],

        [[0.34570867, 0.8518089 , 0.46244842],
         [0.60562913, 0.85964016, 0.58996874],
         [0.97094719, 0.22989766, 0.65626481]],

        [[0.8518089 , 0.46244842, 0.31405382],
         [0.85964016, 0.58996874, 0.74042103],
         [0.22989766, 0.65626481, 0.45009426]],

        [[0.46244842, 0.31405382, 0.32010809],
         [0.58996874, 0.74042103, 0.61283613],
         [0.65626481, 0.45009426, 0.8526749 ]],


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [246]:
from numpy.lib.stride_tricks import sliding_window_view
arr=np.random.rand(16,16)
view=(4,4)
arr2=sliding_window_view(arr,window_shape=view)
arr2.(axis=1)


SyntaxError: invalid syntax (1605374384.py, line 5)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [110]:
arr=np.array([1,2,3,4,5,5,5])
n=3
sorted_indices=np.argsort(arr)
n_largest=sorted_indices[-n:]
arr1=arr[n_largest]
arr1

array([5, 5, 5])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [112]:
arr=np.array([(1,'apple'),(2,'banana')])
arr_record=arr.view(np.recarray)
arr_record

rec.array([['1', 'apple'],
           ['2', 'banana']],
          dtype=<U11)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [146]:
arr=np.array([1,2,3,4,5,5,5], dtype=np.uint8)
arr=np.unpackbits(arr)
arr

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1], dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [115]:
arr=([[1,2,3],[4,4,4],[4,4,4],[10,11,12]])
unique_rows=np.unique(arr,axis=0)
unique_rows

array([[ 1,  2,  3],
       [ 4,  4,  4],
       [10, 11, 12]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [159]:
arr=np.array([1,2,3,4,5,5,5])
arr2=np.array([3,2,6,4,10,12,5])
#arr_prod=arr*arr2[:len(arr)]
#arr_div=arr/arr2[:len(arr)]
arr_prod=np.einsum("i,j->i",arr,arr2)
arr_inner=np.einsum('i,i',arr,arr2)
arr_prod

array([ 42,  84, 126, 168, 210, 210, 210])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
arr=np.array([1,2,3,4,5,5,5])
arr2=np.array([3,2,6,4,10,12,5])


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)