In [44]:
import cv2
import os
import numpy as np

In [24]:
img=cv2.imread('img_1.jpg')
print(img)

[[[13 19 24]
  [13 19 24]
  [13 19 24]
  ...
  [13 19 24]
  [13 19 24]
  [13 19 24]]

 [[13 19 24]
  [13 19 24]
  [13 19 24]
  ...
  [13 19 24]
  [13 19 24]
  [13 19 24]]

 [[13 19 24]
  [13 19 24]
  [12 18 23]
  ...
  [12 18 23]
  [13 19 24]
  [13 19 24]]

 ...

 [[22 33 37]
  [31 42 46]
  [37 48 52]
  ...
  [14 12 11]
  [13 11 10]
  [14 12 11]]

 [[22 33 37]
  [31 42 46]
  [37 48 52]
  ...
  [18 16 15]
  [15 13 12]
  [12 10  9]]

 [[22 33 37]
  [31 42 46]
  [37 48 52]
  ...
  [23 21 20]
  [17 15 14]
  [11  9  8]]]


In [26]:
hsv_img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
print(hsv_img)

[[[ 16 117  24]
  [ 16 117  24]
  [ 16 117  24]
  ...
  [ 16 117  24]
  [ 16 117  24]
  [ 16 117  24]]

 [[ 16 117  24]
  [ 16 117  24]
  [ 16 117  24]
  ...
  [ 16 117  24]
  [ 16 117  24]
  [ 16 117  24]]

 [[ 16 117  24]
  [ 16 117  24]
  [ 16 122  23]
  ...
  [ 16 122  23]
  [ 16 117  24]
  [ 16 117  24]]

 ...

 [[ 22 103  37]
  [ 22  83  46]
  [ 22  74  52]
  ...
  [110  55  14]
  [110  59  13]
  [110  55  14]]

 [[ 22 103  37]
  [ 22  83  46]
  [ 22  74  52]
  ...
  [110  43  18]
  [110  51  15]
  [110  64  12]]

 [[ 22 103  37]
  [ 22  83  46]
  [ 22  74  52]
  ...
  [110  33  23]
  [110  45  17]
  [110  70  11]]]


In [27]:
lower_red1 = np.array([0, 100, 100])
upper_red1 = np.array([10, 255, 255])

In [28]:
lower_red2 = np.array([160, 100, 100])
upper_red2 = np.array([180, 255, 255])


In [29]:
mask1 = cv2.inRange(hsv_img, lower_red1, upper_red1)
mask2 = cv2.inRange(hsv_img, lower_red2, upper_red2)

In [30]:
red_mask = cv2.bitwise_or(mask1, mask2)

In [31]:
kernel = np.ones((5, 5), np.uint8)
red_mask = cv2.morphologyEx(red_mask, cv2.MORPH_OPEN, kernel)
red_mask = cv2.morphologyEx(red_mask, cv2.MORPH_CLOSE, kernel)

In [32]:
white = np.array([255, 255, 255], dtype=np.uint8)

In [33]:
result_img = img.copy()

In [34]:
result_img[red_mask > 0] = white

In [35]:
result_img

array([[[13, 19, 24],
        [13, 19, 24],
        [13, 19, 24],
        ...,
        [13, 19, 24],
        [13, 19, 24],
        [13, 19, 24]],

       [[13, 19, 24],
        [13, 19, 24],
        [13, 19, 24],
        ...,
        [13, 19, 24],
        [13, 19, 24],
        [13, 19, 24]],

       [[13, 19, 24],
        [13, 19, 24],
        [12, 18, 23],
        ...,
        [12, 18, 23],
        [13, 19, 24],
        [13, 19, 24]],

       ...,

       [[22, 33, 37],
        [31, 42, 46],
        [37, 48, 52],
        ...,
        [14, 12, 11],
        [13, 11, 10],
        [14, 12, 11]],

       [[22, 33, 37],
        [31, 42, 46],
        [37, 48, 52],
        ...,
        [18, 16, 15],
        [15, 13, 12],
        [12, 10,  9]],

       [[22, 33, 37],
        [31, 42, 46],
        [37, 48, 52],
        ...,
        [23, 21, 20],
        [17, 15, 14],
        [11,  9,  8]]], dtype=uint8)

In [36]:
cv2.imshow("picture",result_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [49]:
dim_value=[img,hsv_img,mask1,mask2,result_img]
image_title=["Real_img","HSV_img","Mask1_img","Mask2_img","Final_img"]

In [50]:
# os.mkdir("Task jun 25")

In [51]:
foldre="Task jun 25"

In [54]:
for i in range(len(dim_value)):
    cv2.imwrite(image_title[i] + '.jpg', dim_value[i])

In [56]:
imgs=["Real_img.jpg","HSV_img.jpg","Mask1_img.jpg","Mask2_img.jpg","Final_img.jpg"]