# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [6]:
 #%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [7]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [10]:
np. __version__
print(np.show_config())


Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep3179274605568
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:

#### 3. Create a null vector of size 10 (★☆☆)

In [15]:
arr1 = np.arange(10)
arr1.size


10

#### 4. How to find the memory size of any array (★☆☆)

In [16]:
arr1 = np.arange(10)
arr1.nbytes

40

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [17]:
#python -m pydoc numpy.add ---> in cmd

help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [23]:
x = np.zeros(10)
print(x)
x[5] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [24]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [25]:
vector = np.array([1, 2, 3, 4, 5])

reversed_vector = vector[::-1]

print(reversed_vector)

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [51]:
arr = np.arange(9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [43]:
arr = np.array([1,2,0,0,4,0])
idx = np.nonzero(arr)
result = idx
new = []
for i in range(len(arr)):
    if i not in result[0]:
        new.append(i)

#print(result[0])
print(new)

[2, 3, 5]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [54]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [60]:
random_3d_array = np.random.rand(3, 3, 3)
random_3d_array

array([[[0.28392991, 0.15563821, 0.68851998],
        [0.48494557, 0.12844788, 0.90742367],
        [0.43208763, 0.59816912, 0.29471521]],

       [[0.84337878, 0.98842844, 0.0401976 ],
        [0.97954882, 0.41615252, 0.62605891],
        [0.45706284, 0.60071061, 0.55556752]],

       [[0.17575195, 0.25485539, 0.42703808],
        [0.57056113, 0.5803768 , 0.47656731],
        [0.20957423, 0.73630032, 0.98922511]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [66]:
random_array = np.random.rand(10,10)
min_value = np.min(random_array)
max_value = np.max(random_array)
print("10x10 Random Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


10x10 Random Array:
[[2.82480736e-01 6.57719555e-01 6.83718927e-01 1.11037838e-01
  4.19687692e-01 3.18930640e-01 1.06054559e-01 3.78781672e-01
  1.45315703e-01 4.36826767e-01]
 [5.59266017e-01 8.13123704e-01 3.72141122e-01 6.85959509e-01
  4.68882578e-01 8.40355999e-02 9.06936964e-01 6.24034094e-01
  6.21770376e-01 6.79758611e-01]
 [2.72117528e-01 8.44783508e-01 1.77399357e-01 8.08795852e-01
  1.59095406e-01 2.59767831e-01 1.93345031e-01 2.61825560e-02
  3.01143232e-01 7.47223526e-01]
 [7.78460231e-01 3.91599014e-01 8.41480992e-01 6.34598289e-01
  8.19704683e-01 3.97518320e-01 2.84241379e-01 1.22439885e-02
  8.20034871e-01 1.08722308e-01]
 [8.08837476e-02 7.58855559e-02 6.39743199e-01 1.00596908e-01
  4.87198602e-01 8.56589072e-01 6.81095252e-01 5.55208469e-01
  6.78491997e-04 4.12954936e-01]
 [2.17932902e-01 2.59925156e-01 6.01901621e-01 6.09573768e-01
  1.72991037e-01 1.25547241e-01 4.70601367e-01 2.47620640e-01
  1.98290553e-01 8.75909606e-01]
 [2.74986521e-01 9.52627112e-01 2.8521

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [67]:
data = np.arange(30)
average = np.mean(data)
average

14.5

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [69]:
x = np.ones((5, 5))
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [70]:
import numpy as np

original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

padded_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)

print("Original Array:")
print(original_array)
print("\nPadded Array (with zero border):")
print(padded_array)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Padded Array (with zero border):
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [75]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [77]:
values = np.arange(1, 5)

matrix = np.diag(values, k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [78]:
Create a 8x8 matrix and fill it with a checkerboard pattern

SyntaxError: invalid decimal literal (1208180301.py, line 1)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [83]:
print("Checkerboard pattern:")
x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1  
x[::2, 1::2] = 1 

print(x) 

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [84]:
base_tile = np.array([[0, 1],
                      [1, 0]])

checkerboard_matrix = np.tile(base_tile, (4, 4))
print(checkerboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [127]:

nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)

col_means = np.mean(nums, axis=0)


arr_normalized = (nums - col_means) / np.std(nums, axis=0)

print("Original Array:")
print(nums)
print("\nNormalized Array (column-wise):")
print(arr_normalized)

Original array elements:
[[0.73018489 0.68532978 0.33498898 0.06659147 0.50898638]
 [0.24346967 0.96378607 0.40426156 0.514948   0.47653453]
 [0.44484277 0.82855904 0.06084806 0.58875178 0.05266948]
 [0.77618753 0.36585674 0.77319555 0.07865523 0.73975272]
 [0.16500507 0.61344827 0.98638845 0.85905347 0.81407291]]
Original Array:
[[0.73018489 0.68532978 0.33498898 0.06659147 0.50898638]
 [0.24346967 0.96378607 0.40426156 0.514948   0.47653453]
 [0.44484277 0.82855904 0.06084806 0.58875178 0.05266948]
 [0.77618753 0.36585674 0.77319555 0.07865523 0.73975272]
 [0.16500507 0.61344827 0.98638845 0.85905347 0.81407291]]

Normalized Array (column-wise):
[[ 1.04322135 -0.02995163 -0.53856087 -1.15586914 -0.03533246]
 [-0.92292695  1.34491567 -0.32772154  0.30393097 -0.15709366]
 [-0.10945457  0.67723738 -1.37294135  0.54422805 -1.74745963]
 [ 1.22905487 -1.60733758  0.7951729  -1.11659084  0.83051606]
 [-1.23989471 -0.38486385  1.44405086  1.42430096  1.10936969]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [86]:
arr = np.arange(27)
arr.reshape(3,3,3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [88]:
# dates of july  2020
print(np.arange('2016-07', '2016-08',
                dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [90]:
import numpy as np

def compute_in_place(A, B):

  np.add(A, B, out=A)  
  np.divide(A, 2, out=A) 
  np.negative(A, out=A) 
  np.multiply(A, B, out=A) 
  return A


# Example usage:
A = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
B = np.array([5.0, 4.0, 3.0, 2.0, 1.0])

result = compute_in_place(A, B)
print(result) 
print(A)

[-15. -12.  -9.  -6.  -3.]
[-15. -12.  -9.  -6.  -3.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [94]:
x = np.zeros((5,5), dtype = int)
x += np.arange(5)
print("Row values ranging from 0 to 4.")
print(x)


Row values ranging from 0 to 4.
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [95]:
temp_vector = np.linspace(0, 1, 12)
vector = temp_vector[1:-1]
vector

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [106]:
import numpy as np

random_vector = np.random.rand(10)

sorted_vector = np.sort(random_vector)

print("Original Random Vector:")
print(random_vector)
print("\nSorted Vector:")
print(sorted_vector)

Original Random Vector:
[0.10251718 0.33041185 0.14461061 0.43011669 0.53441373 0.37286897
 0.28458682 0.4771704  0.7160101  0.50805444]

Sorted Vector:
[0.10251718 0.14461061 0.28458682 0.33041185 0.37286897 0.43011669
 0.4771704  0.50805444 0.53441373 0.7160101 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [108]:
    my_array = [1, 2, 3, 4, 5]
    total = 0
    for x in my_array:
        total += x
    my_array

[1, 2, 3, 4, 5]

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [109]:
    array_a = [1, 2, 3, 4]
    array_b = [1, 2, 3, 4]
    array_c = [4, 3, 2, 1]

    print(array_a == array_b)
    print(array_a == array_c)  

True
False


#### 43. Make an array immutable (read-only) (★★☆)

In [116]:
A = np.random.randint(0, 10, size=(3, 3))
B = np.random.randint(0, 10, size=(3, 3))

are_equal = np.array_equal(A, B)

print("\nAre arrays A and B equal?", are_equal)


C = np.array([[1, 2], [3, 4]])
D = np.array([[1, 2], [3, 4]])


are_equal_cd = np.array_equal(C, D)
print("Are arrays C and D equal?", are_equal_cd)



Are arrays A and B equal? False
Are arrays C and D equal? True


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [117]:
vector = np.random.rand(10)
max_index = np.argmax(vector)
vector[max_index] = 0
print(vector)

[0.53387965 0.75111387 0.64469977 0.36702221 0.54794797 0.45540584
 0.26068536 0.         0.54631453 0.32462991]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [118]:
def subtract_row_means(matrix):
  row_means = np.mean(matrix, axis=1, keepdims=True)
  return matrix - row_means

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
centered_matrix = subtract_row_means(matrix)
print(centered_matrix)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [122]:
def add_to_indices(array, indices):

    np.add.at(array, indices, 1)
    return array

# Example usage:
my_array = np.zeros(5)
index_vector = np.array([0, 1, 2, 1, 3, 0, 4])
modified_array = add_to_indices(my_array, index_vector)
print(modified_array)  

[2. 2. 1. 1. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [123]:
import numpy as np

arr = np.arange(16).reshape((1, 2, 2, 4))

summed_arr = np.sum(arr, axis=(2, 3))

print(summed_arr)

[[28 92]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [124]:

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
diagonal_elements = np.diag(np.dot(a, b))
print(diagonal_elements)

[19 50]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)