# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
# %run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.26.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
arr = np.array([1, 2, 3])
print(arr.size, arr.itemsize)
arr.size*arr.itemsize

3 8


24

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [10]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [19]:
arr3 = np.zeros(10)
arr3[4] = 1
arr3

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [16]:
arr2 = np.array(range(10,50))
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
arr2[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [32]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [174]:
nums = np.array([1,2,0,0,4,0])
np.where(nums != 0)[0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [33]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [40]:
#np.random.random((3, 3))
np.random.random((3, 3, 3))

array([[[0.87099493, 0.93084024, 0.01457242],
        [0.17966676, 0.27915998, 0.98054499],
        [0.72862227, 0.37832161, 0.69312013]],

       [[0.83659597, 0.33067504, 0.20602661],
        [0.69653027, 0.84090749, 0.60312607],
        [0.34374738, 0.43434625, 0.54811495]],

       [[0.28457713, 0.96865096, 0.34643505],
        [0.21898237, 0.56627913, 0.78409151],
        [0.30130904, 0.66096193, 0.10035473]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [41]:
arr4 = np.random.random((3, 3))
arr4.min(), arr4.max()

(0.1739713960193826, 0.9401815287104105)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [48]:
np.random.rand(20).mean()

0.5237886017943105

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [50]:
arr1 = np.ones((5, 5))
arr1[1:-1, 1:-1] = 0
arr1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [57]:
arr1 = np.ones((5, 5))
np.pad(arr1, pad_width=1, mode='constant', constant_values=0)


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [177]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
print(3*0.1)

nan
False
False
nan
True
False
0.30000000000000004


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [84]:
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [180]:
arr1 = np.ones ((8,8))
arr1[1::2,::2]= 0
arr1[::2, 1::2] = 0
arr1

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [178]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [73]:
arr1 = np.array([[1, 2],
               [3, 4]])
np.tile(arr1, (4, 4))

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [74]:
a=np.random.random((5,5))
a_min,a_max=a.min(),a.max()
normalize=(a-a_min)/(a_max-a_min)
print(normalize)

[[0.08161126 0.6948205  0.93646245 0.39708228 0.35214739]
 [0.50046774 0.35372161 1.         0.69209122 0.92577423]
 [0.6339583  0.30549733 0.         0.31552704 0.68439678]
 [0.09553619 0.69710637 0.39064586 0.78836326 0.06341983]
 [0.93877321 0.32798539 0.92811066 0.86113558 0.04598665]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [78]:
color_rgba_dtype = np.dtype([
    ('R', np.uint8), 
    ('G', np.uint8), 
    ('B', np.uint8),
    ('A', np.uint8) 
])


colors = np.array([
    (255, 0, 0, 255),  
    (0, 255, 0, 128),  
    (0, 0, 255, 0)     
], dtype=color_rgba_dtype)

print(colors)
print(colors['G'])

[(255,   0,   0, 255) (  0, 255,   0, 128) (  0,   0, 255,   0)]
[  0 255   0]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [85]:
np.dot(np.ones((5,3)),np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [86]:
np.ones((5, 3))  # for practice

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [87]:
def negate_elements(arr):
    for i in range(len(arr)):
        if 3 <= arr[i] <= 8:
            arr[i] *= -1
    return arr

arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(negate_elements(arr))

[1, 2, -3, -4, -5, -6, -7, -8, 9, 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [94]:
9
10

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [97]:
print(Z**Z)   # it is valid for only positive numbers
print(2 << Z >> 2)
print(Z <- Z)  # this expression not corrcet
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)   # it is also not correct

NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [98]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_11851/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_11851/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_11851/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [101]:
arr = np.zeros(5)
np.round(arr)

array([0., 0., 0., 0., 0.])

#### 30. How to find common values between two arrays? (★☆☆)

In [104]:
ar1 = np.array([0, 1, 2, 3, 4])
ar2 = [1, 3, 4]

np.intersect1d(ar1, ar2)

array([1, 3, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [147]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday, today, tomorrow)

2025-06-17 2025-06-18 2025-06-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [148]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [145]:
A = np.ones(3)*1
B = np.ones(3)*2
print(np.add(A,B,out=B))
print(np.divide(A,2,out=A))
print(np.negative(A,out=A))
print(np.multiply(A,B,out=A))

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [182]:
arr = np.array([1, 2, 3, 4])

arr.astype(int)

np.trunc(arr)

arr//1

#used loop and convert into int data type

array([1, 2, 3, 4])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [143]:
a=np.zeros((5,5))
a=a+np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [107]:
np.linspace(0,1,12,endpoint=True)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [109]:
ar1=np.random.random(10)
ar1.sort()
ar1

array([0.067245  , 0.07150406, 0.12277907, 0.236962  , 0.31725118,
       0.44462577, 0.44507664, 0.46417643, 0.55635904, 0.89860441])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [110]:
arr = np.array([1, 2, 3, 4, 5])
np.add.reduce(arr)

15

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [152]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(A, B)
equal = np.array_equal(A,B)
print(equal)

[1 0 1 1 1] [1 0 0 1 0]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [113]:
ar1 = np.ones(18)
ar1.setflags(write=False)
ar1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [114]:
ar1 = np.random.random(10)
ar1[ar1.argmax()] = 0
ar1

array([0.46296875, 0.48553277, 0.16061206, 0.51244277, 0.        ,
       0.25871404, 0.57322149, 0.04716085, 0.51345937, 0.0068286 ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [155]:
np.set_printoptions(threshold=float("inf"))
print(np.zeros((10,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [159]:
ar = np.arange(100)
print(ar)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(ar-v)).argmin()
print(ar[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
38.69584803245263
39


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [125]:
points = np.random.random((100, 2))
diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]
distances = np.sqrt(np.sum(diff**2, axis=-1))
distances

array([[0.        , 0.8685979 , 0.89888989, ..., 1.02151673, 0.887441  ,
        0.76454751],
       [0.8685979 , 0.        , 0.14608772, ..., 0.41682236, 0.62700536,
        0.76353115],
       [0.89888989, 0.14608772, 0.        , ..., 0.55846416, 0.77049396,
        0.89586022],
       ...,
       [1.02151673, 0.41682236, 0.55846416, ..., 0.        , 0.32766215,
        0.54488845],
       [0.887441  , 0.62700536, 0.77049396, ..., 0.32766215, 0.        ,
        0.22912888],
       [0.76454751, 0.76353115, 0.89586022, ..., 0.54488845, 0.22912888,
        0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [117]:
ar = np.arange(10, dtype=np.float32)
ar = ar.astype(np.int32)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [127]:
arr = np.array([[1, 2], [3, 4]])
for i, row in enumerate(arr):
    print(f"Row index: {i}, Row: {row}")

Row index: 0, Row: [1 2]
Row index: 1, Row: [3 4]


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [186]:
ar = np.random.rand(5, 10)

ar1 = ar - ar.mean(axis=1, keepdims=True)
ar1

array([[-0.00146447, -0.19959462, -0.09005972, -0.2668653 , -0.12257452,
         0.52413114,  0.03826277, -0.07362662,  0.02896994,  0.1628214 ],
       [ 0.39742943, -0.22277037, -0.15683947, -0.35422149,  0.38419195,
        -0.43529389,  0.30002047, -0.21898054,  0.45752579, -0.15106187],
       [ 0.44341135, -0.29888179,  0.43412417, -0.34762808, -0.3360204 ,
         0.18947857, -0.19519032, -0.12413392,  0.30298317, -0.06814275],
       [ 0.30228447, -0.370496  , -0.31247337, -0.01839542,  0.2248318 ,
        -0.00851865,  0.07481055,  0.09552101,  0.35217149, -0.33973589],
       [-0.22541286, -0.24731871,  0.2113273 ,  0.39302488,  0.39712896,
        -0.25004247,  0.0685629 ,  0.29011206, -0.15567589, -0.48170618]])

#### 59. How to sort an array by the nth column? (★★☆)

In [132]:
nums = np.random.randint(0, 10, (3, 3))
print(nums[nums[:, 2].argsort()])

[[5 5 2]
 [9 3 4]
 [2 8 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [136]:
ar = np.random.randint(0,3,(3,10))
print(ar)
print((~ar.any(axis=0)).any())


[[0 2 1 1 0 1 1 2 1 2]
 [1 2 0 1 1 1 1 1 1 0]
 [2 0 2 0 0 1 2 1 0 1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [135]:
ar = np.random.uniform(0,1,10)
z = 0.5
m = ar.flat[np.abs(ar - z).argmin()]
m

0.6200432504034848

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [188]:
ar = np.ones(10)
I = np.random.randint(0,len(ar),20)
print(I), print(len(I))
ar += np.bincount(I, minlength=len(ar))
ar

[0 0 5 6 4 1 3 9 8 8 7 6 3 1 4 3 1 6 4 0]
20


array([4., 4., 1., 4., 4., 2., 4., 2., 3., 2.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [160]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
F

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [161]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([1.05214668, 0.8539599 , 2.23269044, 1.40963942, 1.2222481 ])

In [191]:
print(np.random.uniform(0,100,(5,5)))
print(np.random.randint(0,100,(5,5)))

[[55.48671206 61.72166155 55.60711486 72.96901247 84.56065893]
 [ 1.2687131  79.58861631 68.71469184 38.91861837 75.17783221]
 [ 5.49343015  1.23353961 27.11085899 22.28871621 65.09627384]
 [ 5.5698931  87.55788039 61.42453879 39.07586869 93.74560438]
 [66.25711352 20.39687293 98.9818413  61.72854446 77.26566358]]
[[ 9 13 96 34 32]
 [70 42 35 34 81]
 [19 35 94  4 21]
 [18 48 47 97  9]
 [96 83  8  6 18]]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [12]:
A = np.random.rand(5, 5, 3)  
B = np.random.rand(5, 5)     

print(B[:, :, np.newaxis])
result = A * B[:, :, np.newaxis]
result

[[[0.77874312]
  [0.66437724]
  [0.63699301]
  [0.85422171]
  [0.51105643]]

 [[0.79263874]
  [0.82660545]
  [0.8972873 ]
  [0.99704958]
  [0.61801828]]

 [[0.59180983]
  [0.54473057]
  [0.55815786]
  [0.25523209]
  [0.52492562]]

 [[0.28956813]
  [0.89824055]
  [0.30694407]
  [0.59625542]
  [0.49767895]]

 [[0.88266151]
  [0.63229121]
  [0.05556994]
  [0.27956541]
  [0.13879415]]]


array([[[2.59872015e-01, 1.65464559e-01, 5.15845132e-01],
        [5.68740043e-01, 1.91095854e-01, 4.23557681e-01],
        [2.50472822e-01, 6.08238985e-01, 2.76261937e-01],
        [2.75232702e-01, 3.36186346e-01, 7.02164595e-02],
        [3.07333298e-01, 3.38134274e-01, 3.08509910e-02]],

       [[1.25357114e-01, 3.48648982e-01, 1.77027795e-01],
        [4.48770282e-02, 5.80726363e-02, 8.01782762e-01],
        [2.38456293e-01, 2.08378977e-01, 3.89201618e-02],
        [7.41041107e-01, 4.06969444e-01, 7.98410317e-01],
        [4.36396006e-01, 4.89200343e-01, 1.08890689e-01]],

       [[8.89768402e-02, 4.75810920e-01, 2.67372939e-02],
        [5.42692462e-01, 2.06391332e-01, 6.62652407e-02],
        [2.02390609e-01, 2.32932832e-01, 5.28779369e-01],
        [2.53572508e-02, 1.33988444e-01, 4.47629496e-02],
        [1.54377296e-01, 1.90761179e-02, 2.75932013e-01]],

       [[1.32594779e-01, 5.89678277e-02, 1.02914776e-01],
        [7.72808137e-01, 8.60072155e-01, 6.17604785e-01],
        

#### 72. How to swap two rows of an array? (★★★)

In [162]:
ar = np.arange(25).reshape(5,5)
print(ar)
ar[[0,1]] = ar[[1,0]]
print(ar)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [163]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [11]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(10)
N = 3

windows = sliding_window_view(Z, window_shape=N)
result = windows.mean(axis=1)
result

array([1., 2., 3., 4., 5., 6., 7., 8.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [10]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
R = sliding_window_view(Z, window_shape=4)

R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★)

In [9]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


rank = np.linalg.matrix_rank(A)
rank

2

#### 83. How to find the most frequent value in an array?

In [166]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[2 2 6 4 8 7 3 0 4 3 1 9 7 2 0 8 2 5 1 1 4 3 2 6 4 3 6 7 4 3 6 6 4 4 9 2 2
 2 7 2 8 4 7 9 8 4 6 7 0 9]
2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [8]:
arr = np.arange(256).reshape(16, 16)

#print(arr)
block_sum = arr.reshape(4, 4, 4, 4)

block_sum

array([[[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11],
         [ 12,  13,  14,  15]],

        [[ 16,  17,  18,  19],
         [ 20,  21,  22,  23],
         [ 24,  25,  26,  27],
         [ 28,  29,  30,  31]],

        [[ 32,  33,  34,  35],
         [ 36,  37,  38,  39],
         [ 40,  41,  42,  43],
         [ 44,  45,  46,  47]],

        [[ 48,  49,  50,  51],
         [ 52,  53,  54,  55],
         [ 56,  57,  58,  59],
         [ 60,  61,  62,  63]]],


       [[[ 64,  65,  66,  67],
         [ 68,  69,  70,  71],
         [ 72,  73,  74,  75],
         [ 76,  77,  78,  79]],

        [[ 80,  81,  82,  83],
         [ 84,  85,  86,  87],
         [ 88,  89,  90,  91],
         [ 92,  93,  94,  95]],

        [[ 96,  97,  98,  99],
         [100, 101, 102, 103],
         [104, 105, 106, 107],
         [108, 109, 110, 111]],

        [[112, 113, 114, 115],
         [116, 117, 118, 119],
         [120, 121, 122, 123],
         [124, 125, 126

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [167]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [172]:
ar = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
reg = np.core.records.fromarrays(ar.T,
    names='col1, col2, col3',
    formats = 'S8, f8, i8')
print(reg)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [170]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.21 s ± 25.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
166 ms ± 964 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
139 ms ± 997 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [169]:
ar = np.random.randint(0,2,(6,3))
print(ar)
np.unique(ar, axis=0)

[[1 1 0]
 [0 0 0]
 [1 1 1]
 [0 0 1]
 [0 0 1]
 [0 1 0]]


array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 1, 0],
       [1, 1, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)