# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
run initialise.py

Exception: File `'initialise.py'` not found.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)


1.26.4


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
x = np.array([1,2,3,4,5])
print(x.size)
print(x.itemsize)
print("Memory size of numpy array in bytes:",
      x.size * x.itemsize)

5
4
Memory size of numpy array in bytes: 20


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
arr = np.arange(1,10)
arr = arr[::-1]
print(arr)

[9 8 7 6 5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
arr = [1,2,0,0,4,0]
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.35972321 0.59502561 0.39852463]
  [0.65853749 0.17400733 0.75769435]
  [0.53686476 0.31393242 0.97209507]]

 [[0.17566557 0.59612121 0.72418542]
  [0.19111943 0.78835494 0.63859594]
  [0.26126958 0.56008238 0.3619279 ]]

 [[0.95764383 0.47389965 0.24433293]
  [0.68129625 0.98979952 0.24098382]
  [0.79369063 0.36567852 0.11176388]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
arr = np.random.random((10,10))
print(arr)
min_value = arr.min()
max_value = arr.max()
print("min_value = ",min_value )
print("max_value = ",max_value )

[[0.9237357  0.73595774 0.75912243 0.89949239 0.92279304 0.79525081
  0.49801374 0.1953306  0.40528961 0.87190229]
 [0.83798372 0.01000641 0.5221554  0.88065706 0.47330299 0.57247759
  0.41645686 0.50537126 0.58291235 0.57895781]
 [0.01322263 0.68261079 0.72661652 0.63422396 0.23113238 0.2124882
  0.18102663 0.67837528 0.1767667  0.31057636]
 [0.00172609 0.79727424 0.86553957 0.49050605 0.25835486 0.17110393
  0.61775902 0.12355694 0.16719185 0.00449691]
 [0.74731152 0.42854369 0.08016971 0.43787129 0.68066401 0.55299949
  0.05385976 0.52165461 0.95667858 0.25967708]
 [0.1000341  0.92318998 0.11007719 0.5974414  0.93306951 0.5589978
  0.45805362 0.76449644 0.26002154 0.98323998]
 [0.57610057 0.93279021 0.69053033 0.24533824 0.44216178 0.43871217
  0.36497895 0.92623412 0.64848363 0.23947967]
 [0.56108128 0.20517329 0.91624604 0.72965068 0.83618246 0.16798374
  0.73616587 0.80813472 0.95208149 0.98052586]
 [0.30654574 0.50631257 0.26929535 0.40897705 0.1989084  0.24512827
  0.27463844 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
arr = np.random.random(30)
print(arr)
mean_of_array= arr.mean()
print("mean_of_array is = ",mean_of_array)

[0.54120923 0.59646618 0.78750121 0.79962275 0.90930259 0.84298774
 0.24553885 0.29298591 0.46095493 0.45508336 0.05873894 0.27732022
 0.90573114 0.74398361 0.96419568 0.87204932 0.92580931 0.13570224
 0.127944   0.21665977 0.82404077 0.63972515 0.6723742  0.02501743
 0.01332166 0.61373691 0.50589178 0.69424726 0.5420235  0.37450502]
mean_of_array is =  0.5354890217750802


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
arr = np.zeros((5,5))
arr[0,:]= 1
arr[-1,:]= 1
arr[:,0]=1
arr[:,-1]=1
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
arr = np.zeros((8,8))
# print(arr)
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
shape = (6, 7, 8)
index = np.unravel_index(99, shape)  # 0-based indexing
print(index)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [25]:
arra = np.array([[0,1],[1,0]])
checkboard = np.tile(arra,(4,4))
print(checkboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [30]:
arr = np.random.rand(5,5)
print(arr)
Z_norm = (arr - np.min(arr))/(np.max(arr)-np.min(arr))
print(Z_norm)

[[0.47362319 0.40880715 0.57519671 0.38333853 0.15111658]
 [0.68573288 0.71805357 0.0099698  0.13621945 0.55983199]
 [0.75950098 0.07236815 0.14807269 0.71252216 0.5484998 ]
 [0.43782043 0.09249709 0.3161323  0.43388608 0.22373881]
 [0.48286485 0.33324779 0.79641978 0.37660609 0.5794136 ]]
[[0.58955229 0.50713632 0.71870675 0.47475203 0.17947331]
 [0.85925754 0.90035449 0.         0.16053107 0.69916994]
 [0.95305638 0.07934179 0.17560289 0.89332109 0.68476065]
 [0.54402777 0.10493648 0.38929685 0.5390251  0.27181514]
 [0.6013034  0.41105982 1.         0.46619149 0.72406868]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [31]:
rgba_dtype = np.dtype([
    ("r", np.uint8),
    ("g", np.uint8),
    ("b", np.uint8),
    ("a", np.uint8)
])

colors = np.array([
    (255, 0, 0, 255),   
    (0, 255, 0, 255),    
    (0, 0, 255, 255)     
], dtype=rgba_dtype)

print(colors)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [47]:
a = np.random.randint(1,10,(5,3))
b = np.random.randint(1,10,(3,2))
c = np.dot(a,b)
print(a)
print(b)
print(c)

[[3 4 6]
 [9 2 7]
 [1 2 6]
 [6 8 6]
 [1 1 5]]
[[1 4]
 [3 1]
 [7 6]]
[[57 52]
 [64 80]
 [49 42]
 [72 68]
 [39 35]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [33]:
Z = np.array([1, 4, 6, 8, 9, 2, 3, 7])
Z[(Z>3) & (Z<8)]*=-1
print(Z)

[ 1 -4 -6  8  9  2  3 -7]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [1]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [35]:
np.array(0) / np.array(0)


C:\Users\PC\AppData\Local\Temp\ipykernel_18436\3272234849.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [36]:
np.array(0) // np.array(0)


C:\Users\PC\AppData\Local\Temp\ipykernel_18436\474058805.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [37]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\PC\AppData\Local\Temp\ipykernel_18436\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [38]:
Z = np.array([1.2, -1.7, 2.5, -2.3, 0.0])

Z_rounded = np.where(Z > 0, np.ceil(Z), np.floor(Z))

print(Z_rounded)


[ 2. -2.  3. -3.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [41]:
arr_1 = np.arange(1,7)
arr_2 = np.arange(2,9)
com_arr = np.intersect1d(arr_1,arr_2)
print(com_arr)

[2 3 4 5 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [43]:
np.seterr(all = "ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [44]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [45]:
today = np.datetime64("today","D")
yesterday = today - np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1,'D')
print(today)
print(yesterday)
print(tomorrow)

2025-06-19
2025-06-18
2025-06-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [58]:
arr = np.arange("2016-07","2016-08",dtype="datetime64[D]")
print(arr)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [61]:
A = np.arange(1,5)
print(A)
B = np.arange(6,10)
B = B+A
A = A* (0-.5)
B = B*A
print(B)

[1 2 3 4]
[ -3.5  -9.  -16.5 -26. ]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [64]:
arr = np.random.uniform(0, 100, 5)
int_part_1 = np.floor(arr).astype(int)
int_part_2 = np.trunc(arr).astype(int)
int_part_3 = arr.astype(int)
print(arr // 1)
print(int_part_1)
print(int_part_2)
print(int_part_3)

[42. 18. 59. 77. 95.]
[42 18 59 77 95]
[42 18 59 77 95]
[42 18 59 77 95]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [65]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [67]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [68]:
vec = np.linspace(0, 1, 12)[1:-1]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [70]:
arr = np.random.rand(10)
sorted_arr = np.sort(vec)
print(arr)
print(sorted_arr)

[0.10809416 0.09471703 0.89623722 0.9079051  0.29348994 0.86640566
 0.91714418 0.27375266 0.99683154 0.17231257]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [71]:
arr = np.array([1, 2, 3, 4, 5])
result = np.add.reduce(arr)
print(result)

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [73]:
A = np.random.rand(5)
B = np.random.rand(5)
are_equal = np.array_equal(A, B)
print(are_equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [76]:
arr = np.array([1, 2, 3, 4, 5])
arr.flags.writeable = False
arr[1] = 5

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [46]:
cartesian = np.random.rand(10, 2)
x = cartesian[:, 0]
y = cartesian[:, 1]

r = np.sqrt(x**2 + y**2)   
theta = np.arctan2(y, x)      

polar = np.column_stack((r, theta))

print("Cartesian:\n", cartesian)
print("Polar:\n", polar)


Cartesian:
 [[0.2292481  0.0383813 ]
 [0.2523536  0.66480977]
 [0.5080911  0.18106322]
 [0.44367629 0.29125163]
 [0.4029351  0.56079577]
 [0.56348509 0.86207832]
 [0.08136902 0.22770581]
 [0.06081986 0.65463692]
 [0.43112331 0.75427879]
 [0.20547736 0.7748103 ]]
Polar:
 [[0.23243885 0.16588404]
 [0.71109378 1.20800966]
 [0.53938897 0.34232925]
 [0.53073172 0.58089665]
 [0.69054224 0.94775793]
 [1.02990023 0.99186956]
 [0.24180747 1.22759514]
 [0.65745612 1.478156  ]
 [0.86879445 1.05154343]
 [0.80159338 1.31156654]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [78]:
vec = np.random.rand(10)
max_index = np.argmax(vec)
vec[max_index] = 0

print("Modified vector:", vec)


Modified vector: [0.34319145 0.567302   0.         0.00461743 0.47320679 0.68431815
 0.21018975 0.51672563 0.19172385 0.07260395]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [47]:
x = np.linspace(0, 1, 3)
y = np.linspace(0, 1, 3)

X, Y = np.meshgrid(x, y)

points = np.array(list(zip(X.ravel(), Y.ravel())), dtype=[('x', float), ('y', float)])

print(points)


[(0. , 0. ) (0.5, 0. ) (1. , 0. ) (0. , 0.5) (0.5, 0.5) (1. , 0.5)
 (0. , 1. ) (0.5, 1. ) (1. , 1. )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [48]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
C = 1 / (X[:, None] - Y[None, :])
print("Cauchy Matrix:\n", C)

Cauchy Matrix:
 [[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [53]:
import numpy as np

for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: min = {info.min}, max = {info.max}")

for dtype in [np.uint8, np.uint16, np.uint32, np.uint64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: min = {info.min}, max = {info.max}")


for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype.__name__}: min = {info.min}, max = {info.max}")


int8: min = -128, max = 127
int16: min = -32768, max = 32767
int32: min = -2147483648, max = 2147483647
int64: min = -9223372036854775808, max = 9223372036854775807
uint8: min = 0, max = 255
uint16: min = 0, max = 65535
uint32: min = 0, max = 4294967295
uint64: min = 0, max = 18446744073709551615
float16: min = -65504.0, max = 65504.0
float32: min = -3.4028234663852886e+38, max = 3.4028234663852886e+38
float64: min = -1.7976931348623157e+308, max = 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [54]:
import numpy as np

arr = np.arange(1000)
np.set_printoptions(threshold=np.inf)
print(arr)


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [55]:
import numpy as np

vec = np.random.rand(10) * 100  # random values between 0–100
target = 45

closest = vec[np.abs(vec - target).argmin()]
print("Vector:", vec)
print("Closest to", target, "is", closest)


Vector: [24.81621604 28.50057632 54.98089434 53.95431492 42.55206492  1.35849395
 83.01753294 16.81724746  2.46922547 44.09435176]
Closest to 45 is 44.094351764888884


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
import numpy as np

dtype = [('position', [('x', float), ('y', float)]),
         ('color',    [('r', float), ('g', float), ('b', float)])]

data = np.array([((1.0, 2.0), (255, 0, 0)),
                 ((3.0, 4.0), (0, 255, 0))],
                dtype=dtype)

print(data)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [56]:
import numpy as np

coords = np.random.rand(100, 2)
diff = coords[:, np.newaxis, :] - coords[np.newaxis, :, :]
distances = np.sqrt((diff ** 2).sum(axis=2))

print("Distance matrix shape:", distances.shape)


Distance matrix shape: (100, 100)


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [57]:
import numpy as np

arr = np.array([1.1, 2.9, 3.7], dtype=np.float32)
arr = arr.astype(np.int32, copy=False)
print(arr)


[1 2 3]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5|
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [62]:
from io import StringIO

data_str = """1, 2, 3, 4, 5|
6,  ,  , 7, 8
 ,  , 9,10,11"""

data_str = data_str.replace('|', '')

data = np.genfromtxt(StringIO(data_str), delimiter=",", dtype=float)

print(data)


[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [63]:
for index in np.ndindex(arr.shape):
    print("Index:", index, "Value:", arr[index])


Index: (0,) Value: 1
Index: (1,) Value: 2
Index: (2,) Value: 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [60]:
import numpy as np

x, y = np.meshgrid(np.linspace(-1, 1, 100), np.linspace(-1, 1, 100))
d = np.sqrt(x*x + y*y)
sigma, mu = 0.4, 0.0
gaussian = np.exp(-((d - mu)**2 / (2.0 * sigma**2)))

print(gaussian.shape)
import numpy as np

(100, 100)


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [59]:
n, m, p = 5, 5, 8  # shape = (5,5), place 8 elements
array = np.zeros((n, m), dtype=int)
indices = np.random.choice(n * m, p, replace=False)
array[np.unravel_index(indices, (n, m))] = 1

print(array)



[[1 1 0 0 1]
 [1 0 0 0 1]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 0 0 1]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [61]:
import numpy as np

A = np.random.rand(4, 5) 
A_centered = A - A.mean(axis=1, keepdims=True)
print(A_centered)


[[-0.18318851 -0.12439526  0.10685486  0.07494906  0.12577985]
 [ 0.14145011  0.09986862  0.13469219 -0.24551808 -0.13049285]
 [-0.15542971 -0.36472341 -0.10674192  0.52661915  0.10027589]
 [-0.00985041 -0.3062397   0.22214297 -0.27712716  0.3710743 ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [49]:
arr = np.array([[1, 4], [3, 1], [2, 5]])
sorted_arr = arr[arr[:, 1].argsort()] 
print("Sorted by 2nd column:\n", sorted_arr)

Sorted by 2nd column:
 [[3 1]
 [1 4]
 [2 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [50]:
A = np.array([[0, 1, 0], [0, 0, 0], [0, 3, 0]])
null_columns = np.all(A == 0, axis=0)
print("Null columns:", null_columns)

Null columns: [ True False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [51]:
arr = np.array([1.2, 3.5, 7.8, 4.4])
target = 5.0
nearest = arr[np.abs(arr - target).argmin()]
print("Nearest value:", nearest)


Nearest value: 4.4


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

ValueError: Iterator operand was NULL, but neither the ALLOCATE nor the VIRTUAL flag was specified

#### 63. Create an array class that has a name attribute (★★☆)

In [65]:
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, data, name="unnamed"):
        obj = np.asarray(data).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, parent):
        if parent is None: return
        self.name = getattr(parent, "name", "unnamed")

X = NamedArray([1, 2, 3], name="my_vec")
print(X, X.name)


[1 2 3] my_vec


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [66]:
vec   = np.zeros(6, int)
index = np.array([0, 1, 1, 4, 4, 4]) 
np.add.at(vec, index, 1)         
print(vec)                       

[1 2 0 0 3 0]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = np.array([10, 20, 30, 40, 50])
I = np.array([0, 1, 1, 2, 0])          
F = np.zeros(3, int)

np.add.at(F, I, X)                     
print(F)                               


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [67]:
img = np.random.randint(0, 256, (200, 300, 3), dtype=np.uint8)
colors = img.reshape(-1, 3)
n_unique = np.unique(colors, axis=0).shape[0]
print("Unique colors:", n_unique)


Unique colors: 59890


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [68]:
A = np.random.rand(5, 4, 6, 7)
out = A.sum(axis=(-2, -1))      
print(out.shape)


(5, 4)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [69]:
D = np.array([5, 7, 1, 6, 9, 3, 8])
S = np.array([0, 0, 1, 1, 1, 2, 2]) 
n_groups   = S.max() + 1
totals     = np.zeros(n_groups, float)
counts     = np.zeros(n_groups, int)

np.add.at(totals,  S, D)
np.add.at(counts, S, 1)
means = totals / counts
print(means)     


[6.         5.33333333 5.5       ]


#### 69. How to get the diagonal of a dot product? (★★★)

In [70]:
A = np.random.rand(100, 50)
B = np.random.rand(50, 100)

diag = (A * B.T).sum(axis=1)     
print(diag.shape)                     


(100,)


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
v  = np.array([1, 2, 3, 4, 5])
out = np.zeros(len(v) * 4 - 3, int)   
out[::4] = v
print(out)                        

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [79]:
arr1 = np.random.rand(5,5,3)
arr2 = np.random.rand(5,5)
print(arr1)
print(arr2)
print("-----------------")
new_arr = arr1 * arr2[:,:,None]
print(new_arr)

[[[0.76194972 0.85538339 0.27209421]
  [0.24260065 0.85803508 0.18714054]
  [0.43950639 0.63791099 0.4108451 ]
  [0.09006003 0.09994745 0.71936588]
  [0.35074236 0.93668989 0.49974934]]

 [[0.46803789 0.12435592 0.56872137]
  [0.36204973 0.7633304  0.75540058]
  [0.62442585 0.52099916 0.51736775]
  [0.43431318 0.33688742 0.33455157]
  [0.23880981 0.63692561 0.82104449]]

 [[0.46066898 0.48550794 0.72659032]
  [0.62471939 0.93720962 0.13058669]
  [0.33373517 0.90771845 0.04827468]
  [0.03357726 0.5409976  0.45184279]
  [0.09486105 0.28146506 0.64305937]]

 [[0.30109974 0.35234047 0.47828365]
  [0.98577669 0.77910396 0.76885593]
  [0.34889087 0.23889619 0.26591558]
  [0.0678186  0.73713986 0.81216687]
  [0.8660187  0.77027662 0.1385036 ]]

 [[0.69503247 0.72353488 0.50660615]
  [0.95593329 0.24411382 0.98461269]
  [0.21405017 0.2031814  0.14681937]
  [0.63289941 0.24453041 0.88322219]
  [0.96988189 0.18777829 0.77529394]]]
[[0.08511738 0.49201308 0.29339659 0.84492806 0.36689829]
 [0.885

#### 72. How to swap two rows of an array? (★★★)

In [86]:
Z = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

Z[[0, 2]] = Z[[2, 0]]


In [87]:
print(Z)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [80]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [88]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
window_size = 3
moving_avg = np.convolve(Z, np.ones(window_size)/window_size, mode='valid')

print(moving_avg)

[2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [89]:
Z = np.array([True, False, True], dtype=bool)
Z[:] = ~Z 
print(Z)

[False  True False]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [83]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
R = np.lib.stride_tricks.sliding_window_view(Z, window_shape=4)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [84]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

rank = np.linalg.matrix_rank(A)

print("Rank of A:", rank)

Rank of A: 2


#### 83. How to find the most frequent value in an array?

In [85]:
Z = np.array([1, 3, 2, 1, 4, 1, 2, 2, 3, 3, 3])
most_frequent = np.bincount(Z).argmax()
print("Most frequent value:", most_frequent)


Most frequent value: 3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [90]:
Z = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6]
])
unique_rows = np.unique(Z, axis=0)

print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)