# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
# %run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)

1.23.5


#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
vector=np.zeros(10)
print(vector.size)

10


#### 4. How to find the memory size of any array (★☆☆)

In [9]:
arr=np.array([[1, 2, 3, 4], [4, 5, 6, 8]])
memory=arr.nbytes
print(memory)

32


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
vector=np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [22]:
vector=np.array(range(10, 50))
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [43]:
vector=np.array([1, 2, 3, 4, 5, 6])
rev=vector[::-1]
print(rev)

[6 5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [25]:
matrix = np.array([[0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]])
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [37]:
arr=np.array([1,2,0,0,4,0])
indices=np.nonzero(arr)
print(indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [28]:
matrix = np.array([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]])
print(matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [47]:
mat=np.random.randint(1, 21 ,size = (3,3,3))
print(mat)

[[[11 17  7]
  [12 18 20]
  [ 9  7 18]]

 [[12  1  6]
  [16 13 19]
  [ 1 13  6]]

 [[ 3 17 13]
  [ 8  4 10]
  [12  7 15]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [51]:
mat=np.random.randint(1, 21, size=(10,10))
mini=np.min(mat)
maxi=np.max(mat)
print(mat, mini, maxi)


[[ 9 16  5 19 19 13  2  4  7 10]
 [12  5  3  2  8 12 12 11 10 13]
 [20  8 10  7  1  7  4 16 11  1]
 [13  8 17  1 13 10  7 17  2  2]
 [14 14 12 18  2  5  4 13 12 13]
 [ 8 13 13  8 15  4  5  8 11  8]
 [10 19  3 20  1 16 20 10 19 16]
 [17  5  6  8  9 17 16 16 16 18]
 [18 17 18 14  5 10 14 11  1 18]
 [ 7 13  4  8 12  3 10  1 17 20]] 1 20


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [32]:
vec=np.random.randint(50, size=(30))
print(np.mean(vec))

22.433333333333334


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [76]:
x=np.ones((5,5))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [80]:
x=np.random.randint(1, 10, size=(3,3))
print(x)
x=np.pad(x, pad_width=1, mode="constant", constant_values=0)
print(x)

[[6 1 2]
 [9 3 7]
 [3 4 4]]
[[0 0 0 0 0]
 [0 6 1 2 0]
 [0 9 3 7 0]
 [0 3 4 4 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [29]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [87]:
x=diag(np.arange(1,5), k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [168]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [169]:
shape = (6, 7, 8)
index_1d = 99  
index_3d = np.unravel_index(index_1d, shape)

print(index_3d)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [171]:
mat=np.random.randint(0, 2, size=(8, 8))
x = np.tile(mat,reps=4)
print(x)

[[1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1]
 [1 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1]
 [1 1 1 0 1 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1 0 1 0]
 [0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1]
 [1 0 0 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 0 0 1 1 1 1]
 [1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 0]
 [0 0 1 0 0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 1 1 1]
 [1 1 0 0 1 1 0 1 1 1 0 0 1 1 0 1 1 1 0 0 1 1 0 1 1 1 0 0 1 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [97]:
x=np.random.randint(1, 10, size=(5,5))
print(x)
mini=np.min(x)
maxi=np.max(x)
normalize=(x-mini)/(maxi-mini)
print(normalize)

[[6 3 6 9 2]
 [5 6 9 4 1]
 [3 7 2 4 9]
 [4 5 6 5 4]
 [6 1 8 6 8]]
[[0.625 0.25  0.625 1.    0.125]
 [0.5   0.625 1.    0.375 0.   ]
 [0.25  0.75  0.125 0.375 1.   ]
 [0.375 0.5   0.625 0.5   0.375]
 [0.625 0.    0.875 0.625 0.875]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [172]:
dtype_rgba = np.dtype([
    ('R', np.uint8),
    ('G', np.uint8),
    ('B', np.uint8),
    ('A', np.uint8)
])
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=dtype_rgba)

print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [103]:
arr1=np.random.randint(1, 10, size=(5,3))
print(arr1)
arr2=np.random.randint(1, 10, size=(3,2))
print(arr2)
print(np.dot(arr1, arr2))

[[3 8 8]
 [3 6 2]
 [3 4 1]
 [9 1 4]
 [2 6 1]]
[[9 8]
 [3 3]
 [6 5]]
[[ 99  88]
 [ 57  52]
 [ 45  41]
 [108  95]
 [ 42  39]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [176]:
arr=np.random.randint(1, 15, size=(8))
print(arr)
for i in range(len(arr)):
    if 3<arr[i]<8:
        arr[i]= -arr[i]

print(arr)

[14  5  3 14  6  9  2 11]
[14 -5  3 14 -6  9  2 11]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [81]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
1j*Z
Z<Z>Z

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [180]:
#np.array(0) / np.array(0)
#np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [184]:
arr=np.array([-2.5, -1.8, 0.3, 1.5, 2.7, -3.0, 4.0])
print(arr)
roundarr=np.where(arr>=0, np.ceil(arr), np.floor(arr)) 
print(roundarr)

[-2.5 -1.8  0.3  1.5  2.7 -3.   4. ]
[-3. -2.  1.  2.  3. -3.  4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [166]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([30, 40, 60, 70, 80])
com=np.intersect1d(arr1, arr2)
print(com)

[30 40]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [165]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [30]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\fujitsu\AppData\Local\Temp\ipykernel_15620\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [164]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print(f"Yesterday: {yesterday}")
print(f"Today: {today}")
print(f"Tomorrow: {tomorrow}")

Yesterday: 2025-06-17
Today: 2025-06-18
Tomorrow: 2025-06-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [107]:
x=np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [123]:
A = np.array([1.0, 2.0, 3.0])
B = np.array([4.0, 5.0, 6.0])

np.add(A, B, out=B)
np.divide(A, 2, out=A) 
np.negative(A, out=A)  
np.multiply(A, B, out=A) 
print(A)

[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [114]:
#Method 1
arr = np.random.randint(-5, 10, size=(3,3))
integer_part = np.floor(arr)
print(integer_part)

#method 2
arr = np.random.randint(-5, 10, size=(3,3))
integer_part = np.trunc(arr)
print(integer_part)
#method 3
arr = np.random.randint(-5, 10, size=(3,3))
integer_part = arr.astype(int)
print(integer_part)

[[ 9. -5. -1.]
 [-5. -3.  6.]
 [ 0. -2.  2.]]
[[ 9.  9.  6.]
 [ 3.  3. -3.]
 [-5.  2.  3.]]
[[-5  0  7]
 [-3  5  3]
 [ 9  2  7]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [121]:
mat=np.zeros((5,5))
print(mat)
mat+=np.arange(5)
print(mat)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [133]:
def generator():
    for i in range(10):
        yield i

arr = np.fromiter(generator(), dtype=int)

print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [134]:
print(np.random.rand(10))

[0.25415745 0.9523613  0.90656939 0.66691365 0.21743166 0.45975544
 0.98541098 0.00598289 0.02812659 0.94535536]



#### 40. Create a random vector of size 10 and sort it (★★☆)

In [139]:
arr=np.random.randint(1, 11, size=(10))
arr=np.sort(arr)
print(arr)

[ 1  1  2  2  3  4  5  7  8 10]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [143]:
import timeit

arr=np.array([1,2,3,4,5])
time_python_sum = timeit.timeit("sum(arr)", globals={'arr': arr}, number=100000)
print(f"Time with Python's sum(): {time_python_sum:.6f} seconds")
time_numpy_sum = timeit.timeit("np.sum(arr)", globals={'arr': arr, 'np': np}, number=100000)
print(f"Time with numpy.sum(): {time_numpy_sum:.6f} seconds")

Time with Python's sum(): 0.423964 seconds
Time with numpy.sum(): 0.791941 seconds


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [149]:
arr1=np.array([1,2,4])
arr2=np.array([2,5,8])
arr3=np.array([1,2,4])
print(np.array_equal(arr1,arr2))
print(np.array_equal(arr1,arr3))

False
True


#### 43. Make an array immutable (read-only) (★★☆)

In [151]:
arr=np.array([1,2,3,4,5])
print(arr)
arr.flags.writeable = False
try:
    arr[1]=20
except ValueError as e:
    print(e)
    
print(arr)

[1 2 3 4 5]
assignment destination is read-only
[1 2 3 4 5]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [154]:
carCo=np.random.randint(1, 10, size=(10, 2))
print(carCo)
x=carCo[:, 0]
y=carCo[:, 1]
print(x)
print(y)
r= np.sqrt(x**2 + y**2)
theta=np.arctan2(y, x)
polCo=np.column_stack((r, theta))
print(polCo)

[[7 6]
 [5 2]
 [8 3]
 [1 4]
 [6 4]
 [4 5]
 [7 8]
 [9 1]
 [1 5]
 [8 7]]
[7 5 8 1 6 4 7 9 1 8]
[6 2 3 4 4 5 8 1 5 7]
[[ 9.21954446  0.70862627]
 [ 5.38516481  0.38050638]
 [ 8.54400375  0.35877067]
 [ 4.12310563  1.32581766]
 [ 7.21110255  0.5880026 ]
 [ 6.40312424  0.89605538]
 [10.63014581  0.85196633]
 [ 9.05538514  0.11065722]
 [ 5.09901951  1.37340077]
 [10.63014581  0.71883   ]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [159]:
arr=np.random.randint(1, 15, size=(10))
print(arr)
arr[arr.argmax()]=0
print(arr)

[ 7  5  3  2 11  1 13  3  8  5]
[ 7  5  3  2 11  1  0  3  8  5]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [161]:
arr=np.random.randint(1, 20, size=(10))
print(arr)

[13  9 16 19  6 18  9  5  2  3]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [162]:
arr= np.array([1,20,3,48,98])
clos=25
diff=np.abs(arr-clos)
closIn=np.argmin(diff)
print(arr[closIn])


20


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [163]:
arr = np.array([[1, 2], [3, 4]])
for index, val in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {val}")

Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (1, 0), Value: 3
Index: (1, 1), Value: 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)