# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [26]:
!python -m initialize.py

C:\Users\ADMIN\miniconda3\envs\ml1\python.exe: Error while finding module specification for 'initialize.py' (ModuleNotFoundError: No module named 'initialize'). Try using 'initialize' instead of 'initialize.py' as the module name.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [12]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [14]:
print(np.__version__)

2.2.5


#### 3. Create a null vector of size 10 (★☆☆)

In [19]:
null_vec = np.zeros(10)
null_vec.size

10

#### 4. How to find the memory size of any array (★☆☆)

In [18]:
print(null_vec.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [20]:
!python -m pydoc numpy.add

Help on ufunc in numpy:

numpy.add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wil

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [21]:
null_vec = np.zeros(10)
null_vec[4] = 1
null_vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [22]:
null_vec = np.array(range(10,50))
null_vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [27]:
rev_vec = null_vec[::-1]
rev_vec

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [82]:
new_vec = np.random.randint(0,9,size=(3,3))
new_vec

array([[1, 7, 4],
       [6, 7, 8],
       [2, 8, 8]], dtype=int32)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [30]:
np_arr = np.array([1,2,0,0,4,0])
np_arr.nonzero()

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [234]:
np_arr = np.eye(3,4)
np_arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [53]:
np.random.randint(1000, size = (3,3,3))

array([[[523, 655, 528],
        [453, 439, 216],
        [478, 324, 110]],

       [[272, 884, 172],
        [642,  82, 189],
        [546, 370, 543]],

       [[222, 548, 954],
        [892, 606, 688],
        [974, 912, 566]]], dtype=int32)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [49]:
vec = np.random.randint(100, size = (10, 10))
print(vec.max())
print(vec.min())
vec

99
0


array([[76, 38, 40, 13, 28, 53, 40, 87, 99, 15],
       [73, 62, 29, 66, 56, 21, 68, 10, 82, 93],
       [55, 70, 98, 59,  9, 14, 92, 84, 43, 35],
       [18, 54, 19, 34, 69, 60, 73, 49, 71, 48],
       [12, 33, 70, 25,  6, 86, 32, 86,  8, 92],
       [43, 56,  4, 92, 75, 59, 49, 76, 53, 59],
       [46, 53, 72, 56,  6, 91, 34, 82, 41, 90],
       [80, 58, 87,  1,  3, 65, 42, 97,  1, 60],
       [62, 14, 41, 56, 52, 83, 82, 42, 32, 79],
       [42, 10, 65, 50, 41,  0, 17, 86,  2,  5]], dtype=int32)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [56]:
vec = np.random.randint(100, size = (30))
np.mean(vec)

np.float64(48.56666666666667)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [240]:
vec = np.zeros((2,2))
vec[0,:] = 1
vec[:,0] = 1
vec[:,-1] = 1
vec[-1,:] = 1
vec

array([[1., 1.],
       [1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [81]:
vec = np.random.randint(500, size=(8,8))
vec[0,:] = 0
vec[:,0] = 0
vec[:,-1] = 0
vec[-1,:] = 0
vec

array([[  0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 369, 155,  25, 380, 342, 395,   0],
       [  0, 403,  51,  12, 216, 446, 355,   0],
       [  0, 202, 136, 230, 346, 322,  16,   0],
       [  0, 298, 423,  62, 213, 391, 311,   0],
       [  0, 320, 127, 195, 392, 229, 489,   0],
       [  0,  52, 264, 133,  37, 228, 275,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0]], dtype=int32)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [249]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
#np.nan in set([np.nan])
0.3 == 3 * 0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [170]:
np.diag(np.arange(1,5), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [159]:
vec = np.ones((8,8))
vec[1::2,::2] = 0
vec[::2,1::2] = 0
vec

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [241]:
np.unravel_index(99, (6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [184]:
mat1 = np.eye(5,3)
mat2 = np.eye(3,2)

print(mat1)
print(mat2)
mat3 = np.matmul(mat1, mat2)
print(mat3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [194]:
print(sum(range(5),-1))

9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [200]:
np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [207]:
A = np.ones(3) * 2
B = np.ones(3) * 7

np.add(A, B, out = B)
np.divide(A, 2, out = A)
np.negative(A, out = A)
np.multiply(A,B, out = A)
print(A)

[-9. -9. -9.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [210]:
arr = np.array([1,2,3,4,5,6])

#Method 1
arr.astype(int) # give int

#Method 2
np.trunc(arr) # convert 133.33 to 133

#Method 3
arr // 1 # floor division, divide then round off

#Method 4
#loop and use int()

array([1, 2, 3, 4, 5, 6])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [198]:
np.random.randint(0,5, size = (5,5))

array([[3, 3, 2, 1, 4],
       [0, 2, 2, 4, 0],
       [1, 1, 4, 1, 0],
       [3, 1, 2, 1, 2],
       [3, 3, 1, 2, 2]], dtype=int32)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [185]:
np.random.rand(10)

array([0.06320713, 0.6052203 , 0.7032114 , 0.35088578, 0.7831691 ,
       0.26274959, 0.41855414, 0.70037669, 0.41536274, 0.96289569])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [186]:
np.sort(np.random.rand(10))

array([0.05099779, 0.10701526, 0.12931514, 0.2272693 , 0.28207879,
       0.36668471, 0.39396449, 0.43214233, 0.55741421, 0.71148584])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [187]:
#use sum
sum([1,2,3,4])

10

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [190]:
arr1 = np.random.randint(5)
arr2 = np.random.randint(5)
print(arr1 == arr2)

#seed was different

False


#### 43. Make an array immutable (read-only) (★★☆)

In [197]:
vec = np.array([1,2,3,4])
vec.flags.writeable = False
vec

array([1, 2, 3, 4])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [216]:
cart_coord = np.random.randint(0,100, size = (10,2))
print(cart_coord)
x = cart_coord[:,0]
y = cart_coord[:,1]

r = np.hypot(x,y)
theta = np.arctan2(y,x)
ans = np.stack((r, theta), axis=-1)

[[ 5 67]
 [13 19]
 [66 53]
 [96 97]
 [21 40]
 [21 63]
 [ 0 94]
 [77 77]
 [45 54]
 [86 71]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [223]:
vec = np.arange(1, 11)
vec = np.sort(vec)
vec[-1] = 0
vec

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [231]:
import sys
vec = np.random.randint(10, size = (3,3))
with np.printoptions(threshold = sys.maxsize):
    print(vec)

[[8 7 3]
 [9 9 5]
 [0 3 2]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [233]:
arr = np.array([10, 25, 30, 42, 55, 60])
scalar_value = 33

absolute_differences = np.abs(arr - scalar_value)
print(absolute_differences)
closest_index = np.argmin(absolute_differences)
print(closest_index)
closest_value = arr[closest_index]

[23  8  3  9 22 27]
2


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [242]:
#import csv 
#csv.reader(file)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
#for i, row in enumerate(arr)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [244]:
arr = np.random.randint(45, size = (3,3))
ans = arr - arr.mean(axis = 1, keepdims = True)
ans

array([[-14.33333333,   7.66666667,   6.66666667],
       [-21.66666667,  10.33333333,  11.33333333],
       [ 14.        ,   6.        , -20.        ]])

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [254]:
A = np.random.randint(0,23,size=(5,5))
B = np.random.randint(0,23,size=(5,5))

np.diag(np.dot(A, B))

array([487, 818, 222, 338, 747], dtype=int32)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [262]:
vec = np.random.randint(10, size= (3,3))
print(vec)
np.roll(vec, 2, axis = 0)

[[1 5 2]
 [3 1 2]
 [7 4 2]]


array([[3, 1, 2],
       [7, 4, 2],
       [1, 5, 2]], dtype=int32)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)