In [2]:
import cv2

In [3]:
a = cv2.imread('img_1.jpg')
print(a)

[[[13 19 24]
  [13 19 24]
  [13 19 24]
  ...
  [13 19 24]
  [13 19 24]
  [13 19 24]]

 [[13 19 24]
  [13 19 24]
  [13 19 24]
  ...
  [13 19 24]
  [13 19 24]
  [13 19 24]]

 [[13 19 24]
  [13 19 24]
  [12 18 23]
  ...
  [12 18 23]
  [13 19 24]
  [13 19 24]]

 ...

 [[22 33 37]
  [31 42 46]
  [37 48 52]
  ...
  [14 12 11]
  [13 11 10]
  [14 12 11]]

 [[22 33 37]
  [31 42 46]
  [37 48 52]
  ...
  [18 16 15]
  [15 13 12]
  [12 10  9]]

 [[22 33 37]
  [31 42 46]
  [37 48 52]
  ...
  [23 21 20]
  [17 15 14]
  [11  9  8]]]


In [13]:
cv2.imshow('Displayed Image', a)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
hsv = cv2.cvtColor(a, cv2.COLOR_BGR2HSV)

In [6]:
print(hsv)

[[[ 16 117  24]
  [ 16 117  24]
  [ 16 117  24]
  ...
  [ 16 117  24]
  [ 16 117  24]
  [ 16 117  24]]

 [[ 16 117  24]
  [ 16 117  24]
  [ 16 117  24]
  ...
  [ 16 117  24]
  [ 16 117  24]
  [ 16 117  24]]

 [[ 16 117  24]
  [ 16 117  24]
  [ 16 122  23]
  ...
  [ 16 122  23]
  [ 16 117  24]
  [ 16 117  24]]

 ...

 [[ 22 103  37]
  [ 22  83  46]
  [ 22  74  52]
  ...
  [110  55  14]
  [110  59  13]
  [110  55  14]]

 [[ 22 103  37]
  [ 22  83  46]
  [ 22  74  52]
  ...
  [110  43  18]
  [110  51  15]
  [110  64  12]]

 [[ 22 103  37]
  [ 22  83  46]
  [ 22  74  52]
  ...
  [110  33  23]
  [110  45  17]
  [110  70  11]]]


In [7]:
cv2.imshow('Displayed Image', hsv)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
import numpy as np
lower_blue = np.array([100, 50, 50])
upper_blue = np.array([130, 255, 255])

In [10]:
mask = cv2.inRange(hsv, lower_blue, upper_blue)

In [11]:
result = cv2.bitwise_and(a, a, mask=mask)

In [12]:
pixel_bgr = a[100, 50]
print(f"BGR value at (100, 50): {pixel_bgr}")

pixel_hsv = hsv[100, 50]
print(f"HSV value at (100, 50): {pixel_hsv}")

BGR value at (100, 50): [107 123 130]
HSV value at (100, 50): [ 21  45 130]


In [37]:
import cv2
import numpy as np

image_path = 'img_1.jpg'
img = cv2.imread(image_path)
if img is None:
    print(f"Error: Could not load image from {image_path}")
else:
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    lower_red1 = np.array([0, 100, 100])
    upper_red1 = np.array([10, 255, 255])
    mask1 = cv2.inRange(hsv, lower_red1, upper_red1)

    lower_red2 = np.array([150, 100, 100])
    upper_red2 = np.array([180, 255, 255])
    mask2 = cv2.inRange(hsv, lower_red2, upper_red2)
    
    red_mask = cv2.bitwise_or(mask1, mask2)
    img[red_mask > 0] = [255, 255, 255] 
    cv2.imwrite('output.jpg', img)
    cv2.imshow('Red Replaced with White', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [38]:
import cv2
import numpy as np

image_path = 'output.jpg'
img = cv2.imread(image_path)
if img is None:
    print(f"Error: Could not load image from {image_path}")
else:
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    lower_red1 = np.array([0, 100, 100])
    upper_red1 = np.array([10, 255, 255])
    mask1 = cv2.inRange(hsv, lower_red1, upper_red1)

    lower_red2 = np.array([150, 100, 100])
    upper_red2 = np.array([180, 255, 255])
    mask2 = cv2.inRange(hsv, lower_red2, upper_red2)
    
    red_mask = cv2.bitwise_or(mask1, mask2)
    img[red_mask > 0] = [255, 255, 255] 
    cv2.imwrite('output.jpg', img)
    cv2.imshow('Red Replaced with White', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()