# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialize.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [6]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)

2.2.0


#### 3. Create a null vector of size 10 (★☆☆)

In [11]:
n = 10
null_vector = np.zeros(n)
print(null_vector)
n = 12
null_vector_integers = np.zeros(n,dtype = int)
print(null_vector_integers)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0]


#### 4. How to find the memory size of any array (★☆☆)

In [40]:
#This is for 1D-Array
array1 = np.array([1,2,3])
print(array1)
print("Size of array1: ",array1.size)
print("Size of every element in bytes: ",array1.itemsize)
print("Memory size of array1: " ,array1.size * array1.itemsize)

[1 2 3]
Size of array1:  3
Size of every element in bytes:  8
Memory size of array1:  24


In [51]:
#This is for 2D-Array
import numpy as np
Two_DArray = np.array([[100, 20, 34],
                       [300, 400, 600]])
print("Size of the array: ",Two_DArray.size)
print("Memory size of one array element in bytes: ", Two_DArray.itemsize)
print("Memory size of numpy array in bytes:",Two_DArray.size * Two_DArray.itemsize)
print(Two_DArray)

Size of the array:  6
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 48
[[100  20  34]
 [300 400 600]]


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [22]:
print(np.info(np. add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [52]:
null_vector1 = np.zeros(10)
print(null_vector1)
null_vector1[4] = 1
print(null_vector1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [37]:
vector1 = np.arange(10,50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [39]:
vector2 = np.arange(1,11)
print(vector2)
print(vector2[::-1])

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [68]:
vector = np.arange(0,9,1)
matrix = vector.reshape(3,3)
print(vector)
print(matrix)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [47]:
arr = np.array([1,2,0,0,4,0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [50]:
identity_matrix = np.identity(3)                  
print(identity_matrix)
identity_matrix1 = np.eye(3)
print(identity_matrix1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [67]:
arr = np.random.rand(3,3,3)
print(arr)

[[[0.17265074 0.18136657 0.82574049]
  [0.96666996 0.20226707 0.73305707]
  [0.56288234 0.30901346 0.30239611]]

 [[0.03773695 0.85541869 0.93647574]
  [0.91395128 0.74618175 0.07391884]
  [0.46989996 0.36172819 0.551248  ]]

 [[0.03026681 0.11777004 0.41866427]
  [0.72570855 0.38634773 0.88607443]
  [0.93626416 0.14105156 0.81264756]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [62]:
arr1 = np.random.rand(10,10)
print(arr1)
print(np.min(arr1))
print(np.max(arr1))

[[0.81761509 0.35425716 0.57857907 0.88959594 0.80626681 0.829821
  0.37151078 0.3220391  0.84508806 0.32136253]
 [0.03117388 0.28096922 0.03336988 0.83228191 0.93129857 0.35027122
  0.11945618 0.93149439 0.27681779 0.95974649]
 [0.03384668 0.24319591 0.97568467 0.23907426 0.16219191 0.38180371
  0.62761526 0.30696508 0.33840925 0.88159495]
 [0.52899804 0.99755808 0.80590141 0.11519311 0.0892145  0.36066247
  0.88110384 0.26879306 0.82564691 0.55313319]
 [0.45472315 0.92620822 0.9302143  0.42967332 0.48172102 0.41700063
  0.48801168 0.665066   0.44987378 0.83007469]
 [0.01994391 0.58306035 0.77210919 0.73599935 0.72712342 0.23973449
  0.78816758 0.43620472 0.67691551 0.96038082]
 [0.63816581 0.96468283 0.04545062 0.95100744 0.11660063 0.54745304
  0.15110993 0.14096044 0.2347241  0.79758972]
 [0.42624437 0.5883177  0.00805961 0.85031619 0.74682717 0.17255332
  0.26658592 0.38943552 0.54878068 0.06146563]
 [0.5305555  0.22160281 0.63482518 0.98845285 0.37986953 0.49051911
  0.856341   0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [104]:
arr3 = np.random.rand(10)
print(arr3)
print(np.mean(arr3))

[0.52897077 0.66054106 0.81372074 0.56378724 0.5833436  0.12413404
 0.08965456 0.3280273  0.23116051 0.99765953]
0.4920999350543422


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [131]:
arr = np.ones((5,5),dtype =int)
arr[1:-1,1:-1] = 0
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [84]:
arr = np.random.randint(1,10,size=(3,3)) #10 is exclusive 
print(arr)
bordered_arr = np.pad(arr,pad_width=1,constant_values=0)
print(bordered_arr)

[[3 6 9]
 [6 5 9]
 [1 5 4]]
[[0 0 0 0 0]
 [0 3 6 9 0]
 [0 6 5 9 0]
 [0 1 5 4 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [86]:
#nan
#False
#False
#nan
#True
#False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [88]:
values = [1,2,3,4]
matrix1 = np.diag(values,k=-1)
print(matrix1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [93]:
checkerboard = np.zeros((8,8),dtype = int)
print(checkerboard)
checkerboard[::2,::2] = 1   #even rows and odd columns
checkerboard[::]

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [100]:
import numpy as np

# Create a 3D array with values from 0 to 335 (total 6*7*8 = 336 elements)
arr = np.arange(336).reshape(6, 7, 8)
# Print the full array (optional, large output)
print(arr)
print("100th element (flat index 99):", arr[1, 1, 1])

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [108]:
arr1 = np.random.rand(5,5)
print(arr1)
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized)

[[0.93439648 0.9474588  0.28484949 0.79483734 0.51787191]
 [0.44698763 0.70003924 0.44242519 0.59355384 0.37069752]
 [0.87106193 0.94653843 0.18335163 0.16874816 0.30213866]
 [0.50523103 0.57180973 0.22054275 0.80042737 0.08958263]
 [0.92834389 0.4800797  0.11518765 0.73363848 0.3308129 ]]
[[[0.         0.00298507 0.00597015 0.00895522 0.0119403  0.01492537
   0.01791045 0.02089552]
  [0.0238806  0.02686567 0.02985075 0.03283582 0.0358209  0.03880597
   0.04179104 0.04477612]
  [0.04776119 0.05074627 0.05373134 0.05671642 0.05970149 0.06268657
   0.06567164 0.06865672]
  [0.07164179 0.07462687 0.07761194 0.08059701 0.08358209 0.08656716
   0.08955224 0.09253731]
  [0.09552239 0.09850746 0.10149254 0.10447761 0.10746269 0.11044776
   0.11343284 0.11641791]
  [0.11940299 0.12238806 0.12537313 0.12835821 0.13134328 0.13432836
   0.13731343 0.14029851]
  [0.14328358 0.14626866 0.14925373 0.15223881 0.15522388 0.15820896
   0.16119403 0.1641791 ]]

 [[0.16716418 0.17014925 0.17313433 0.1761

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [143]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [112]:
start_date = np.datetime64("2016-07-01")
end_date = np.datetime64("2016-08-01")
july_dates = np.arange(start_date,end_date)
print(july_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [129]:
A = np.array([1,2,3])
B = np.array([4,5,6])
A += B   
print(A)
print(A - B)
-A/2 = [-1.0, -2.0]
A*= [-1.0, -2.0]


SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (2096692311.py, line 6)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [149]:
arr = np.random.uniform(0,10,size = 5)
print(arr)
int_part1 = np.floor(arr).astype(int)
print(int_part1)
int_part2 = np.trunc(arr).astype(int)
print(int_part2)
int_part3 = arr.astype(int)
print(int_part3)

[7.22454185 5.87978525 8.03228761 4.84656191 3.30112259]
[7 5 8 4 3]
[7 5 8 4 3]
[7 5 8 4 3]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [151]:
matrix = np.tile(np.arange(5),(5,1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [166]:
vector = np.linspace(0,1,10)[1:-1]
print(vector)

[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [160]:
matrix = np.random.randint(1,10,size = (5))
print(matrix)
print(np.sort(matrix))


[6 8 7 2 5]
[2 5 6 7 8]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [168]:
arr = np.array([1, 2, 3, 4, 5])
result = sum(arr)
print(result)

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [170]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
are_equal = np.array_equal(A, B)
print(are_equal)


False


#### 43. Make an array immutable (read-only) (★★☆)

In [172]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr.flags.writeable = False
arr[0] = 10 


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [173]:
cartesian = np.random.rand(10, 2)
x, y = cartesian[:, 0], cartesian[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar = np.column_stack((r, theta))
print("Polar Coordinates:\n", polar)


Polar Coordinates:
 [[0.07649223 0.0198273 ]
 [0.98510713 1.424378  ]
 [0.64454909 0.377859  ]
 [1.06565802 0.45677253]
 [0.93146624 0.0642882 ]
 [0.55292047 1.04960594]
 [0.98171976 0.80416967]
 [0.24850187 0.93209976]
 [0.49916542 1.44612379]
 [0.64349513 1.4945561 ]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [175]:
vec = np.random.rand(10)
max_index = vec.argmax()
vec[max_index] = 0
print(vec)

[0.13440385 0.         0.59303533 0.40570874 0.22378008 0.53633196
 0.50856838 0.53173059 0.50219537 0.44716277]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [176]:
n = 5
x = np.linspace(0, 1, n)
y = np.linspace(0, 1, n)
xx, yy = np.meshgrid(x, y)
coords = np.zeros((n * n,), dtype=[('x', float), ('y', float)])
coords['x'] = xx.ravel()
coords['y'] = yy.ravel()
print(coords)


[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [177]:
X = np.random.rand(5)
Y = np.random.rand(5)
C = 1.0 / (X[:, np.newaxis] - Y[np.newaxis, :])
print("Cauchy Matrix:\n", C)


Cauchy Matrix:
 [[  1.58529165   1.3126986    1.09023693   7.27440019   7.60509735]
 [-38.34291583   9.5319523    3.84094454  -1.92525834  -1.90335366]
 [ -8.17715726 114.95770308   6.09231653  -1.6243727   -1.6087519 ]
 [ 22.05265263   5.67096735   3.01405378  -2.2322208   -2.20282765]
 [  1.94873421   1.55244705   1.25064615  50.44585058  72.22504197]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)