# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [11]:
%run initialise.py

Exception: File `'initialise.py'` not found.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
np.version.version

'1.26.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [15]:
null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [17]:
print(null_vector.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [21]:
help(np.nbytes)

Help on _typedict in module numpy.core.numerictypes object:

class _typedict(builtins.dict)
 |  Base object for a dictionary for look-up with any alias for an array dtype.
 |
 |  Instances of `_typedict` can not be used as dictionaries directly,
 |  first they have to be populated.
 |
 |  Method resolution order:
 |      _typedict
 |      builtins.dict
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __getitem__(self, obj)
 |      Return self[key].
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from builtins.dict:
 |
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, v

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [23]:
vector = np.zeros(10)
vector[4] = 1 

print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [25]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [27]:

reversed_vector = vector[::-1]

print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [29]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [35]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [39]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [41]:
array = np.random.rand(3, 3, 3)
print(array)

[[[0.70960093 0.58552982 0.95760544]
  [0.72299474 0.47142698 0.284758  ]
  [0.68439788 0.25592133 0.84524152]]

 [[0.50095577 0.33101426 0.41636039]
  [0.35935722 0.10389062 0.66585781]
  [0.06079891 0.73309205 0.94063568]]

 [[0.78115053 0.36180738 0.13223833]
  [0.85784465 0.81233559 0.03386955]
  [0.06025259 0.21701018 0.07851138]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [43]:
array = np.random.rand(10, 10)
min_val = np.min(array)
max_val = np.max(array)
print("Min:", min_val)
print("Max:", max_val)

Min: 0.005805839643577171
Max: 0.9981744628702572


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [45]:
vector = np.random.rand(30)
mean_val = np.mean(vector)
print("Mean:", mean_val)

Mean: 0.4778708321213757


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [51]:
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [72]:
a = np.ones((3, 3))
a = np.pad(a, 1)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [57]:
print(0 * np.nan)                  
print(np.nan == np.nan)          
print(np.inf > np.nan)           
print(np.nan - np.nan)           
print(np.nan in set([np.nan]))    
print(0.3 == 3 * 0.1)             

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [121]:
matrix = np.diag([1, 2, 3, 4], k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [67]:
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [69]:
index = np.unravel_index(100, (6, 7, 8))
print(index)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [123]:
checkerboard = np.tile([[0, 1], [1, 0]], (4, 4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [88]:
matrix = np.random.rand(5, 5)
normalized = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
print(normalized)

[[0.4352737  0.09810784 0.69542222 1.         0.43999592]
 [0.         0.03994344 0.85296599 0.95963737 0.42446052]
 [0.89098866 0.08312022 0.20935224 0.66508312 0.63767586]
 [0.95622982 0.57432732 0.28680156 0.55764438 0.67301819]
 [0.85666552 0.15159808 0.01518861 0.90661487 0.05409045]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [309]:
color_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [96]:
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)

product = np.dot(a, b)
print(product)

[[1.05153162 0.61478602]
 [1.12230654 1.21693184]
 [0.64464112 0.69942454]
 [0.89725432 0.32261354]
 [1.29633711 0.84586147]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [108]:
arr = np.arange(11)
print(arr)
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [117]:
# 9  # is uses pyhton sum and sub -1 from the total
# 10  # uses numpy sum and add till last axis means full vaector till last index

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [315]:
#True
#True
#False
#True
#True
#False

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [319]:
Z = np.array([-1.5, -0.2, 0.2, 1.5])
rounded = np.copysign(np.ceil(np.abs(Z)), Z)
print(rounded)

[-2. -1.  1.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [323]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
common = np.intersect1d(a, b)
print(common)

[3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [329]:
np.seterr(all='ignore')
# or 
import warnings
warnings.filterwarnings('ignore')
np.seterr(all='ignore')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [331]:
# False why? because np.sqrt(-1) return NaN number an np.emath.sqrt(-1) return 1j) acomplex number 

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [334]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [138]:
dates = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [148]:
A = np.ones(3) 
B = np.ones(3)

A += B 
A *= -A / 2
print(A)

[-2. -2. -2.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [191]:
arr = np.random.uniform(0, 10, 5)

int_part1 = arr.astype(int)
int_part2 = np.floor(arr).astype(int)
int_part3 = np.trunc(arr).astype(int)
int_part4 = np.array(list(map(int, arr)))

print(arr)
print(int_part1)
print(int_part2)
print(int_part3)
print(int_part4)

[8.60849905 7.18654439 3.53115064 5.93297556 7.82138307]
[8 7 3 5 7]
[8 7 3 5 7]
[8 7 3 5 7]
[8 7 3 5 7]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [146]:
matrix = np.tile(np.arange(5), (5,1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [151]:
vector = np.linspace(0, 1, 12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [160]:
vector = np.random.random(10)
vector.sort()
print(vector)

[0.0757072  0.1071915  0.25308674 0.25737047 0.43180382 0.46567271
 0.50167044 0.61758075 0.68247789 0.81297051]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [162]:
arr = np.arange(10)
total = np.add.reduce(arr) # it doesnt do dtype check and axis part which np.sum do 
print(total)

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [178]:
A = np.random.rand(5)
B = np.random.rand(5)
C = np.ones(5)
D = np.ones(5)
equal1 = np.array_equal(A, B)
equal2 = np.array_equal(C, D)

print(equal1, equal2)


False True


#### 43. Make an array immutable (read-only) (★★☆)

In [180]:
array = np.array([1, 2, 3, 4, 5])
array.flags.writeable = False

array[0]= 100

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [184]:
vector = np.arange(10)
vector[vector.argmax()] = 0
print(vector)

[0 1 2 3 4 5 6 7 8 0]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [208]:

array = np.arange(100)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [234]:
vec = np.arange(0,100,5)
target = 42

closest = vec[np.abs(vec - target).argmin()]
print(closest)

40


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [236]:
arr = np.array([1.5, 2.3, 3.9], dtype=np.float32)
arr = arr.astype(np.int32, copy=False)
print(arr)

[1 2 3]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [244]:
import numpy as np

data = np.genfromtxt(fname=["1, 2, 3, 4, 5", "6,  ,  , 7, 8", " ,  , 9,10,11"],delimiter=",",dtype=float)

print(data)


[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [254]:
arr = np.array([[10, 20], [30, 40]])

for index, value in np.ndenumerate(arr):
    print(index, value)
    

(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [280]:
arr = np.zeros((5, 5), dtype=int)
arr.flat[np.random.choice(arr.size, 10, replace=False)] = 1

print(arr)

[[1 0 0 1 0]
 [0 1 0 1 0]
 [1 0 0 1 0]
 [0 1 0 0 0]
 [0 1 1 1 0]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [266]:
X = np.random.rand(5, 10)
print(X)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.86368818 0.451475   0.4659478  0.59036178 0.18978434 0.12042477
  0.17820583 0.50626984 0.44851192 0.05016545]
 [0.19389412 0.73122121 0.39752479 0.88026116 0.58135196 0.65862644
  0.94001771 0.68471292 0.53068625 0.58785507]
 [0.40380301 0.38821574 0.59203435 0.88264168 0.23242093 0.88679177
  0.28305631 0.90948389 0.26515614 0.27775324]
 [0.01504404 0.45523059 0.79828063 0.08521528 0.56985582 0.95630566
  0.96323311 0.6639617  0.70054955 0.3481783 ]
 [0.81699641 0.38600689 0.450221   0.67648348 0.6889752  0.99884165
  0.58969162 0.8114744  0.70963254 0.80067482]]
[[ 0.47720469  0.06499151  0.07946431  0.20387829 -0.19669915 -0.26605872
  -0.20827766  0.11978635  0.06202843 -0.33631804]
 [-0.42472104  0.11260604 -0.22109037  0.26164599 -0.03726321  0.04001128
   0.32140255  0.06609775 -0.08792891 -0.03076009]
 [-0.1083327  -0.12391996  0.07989864  0.37050597 -0.27971478  0.37465607
  -0.2290794   0.39734819 -0.24697957 -0.23438247]
 [-0.54054143 -0.10035488  0.24269516 -0.47037018

#### 59. How to sort an array by the nth column? (★★☆)

In [268]:
arr = np.random.randint(0, 100, (5, 5))
sorted_arr = arr[arr[:, 2].argsort()]

print(sorted_arr)

[[45 16 22 46 76]
 [10 73 24 68 10]
 [10 48 38 53 58]
 [97 10 64 56 48]
 [38 57 94 49 53]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [270]:
arr = np.array([
    [1,   np.nan, 3],
    [4,   np.nan, 6],
    [7,   np.nan, 9]
])

null_columns = np.all(np.isnan(arr), axis=0)
print(null_columns)

[False  True False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [278]:
arr = np.arange(0,50,5) 
target = 17

nearest = arr[np.abs(arr - target).argmin()]
print(nearest)

15


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [288]:
array = np.random.rand(2, 3, 4, 5)
result = array.sum(axis=(-2, -1))

print(result)

[[ 9.55610201  9.26210036  6.83613048]
 [ 9.06944866  9.57088427 10.01510647]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [303]:
A = np.random.rand(3, 4)
B = np.random.rand(4, 3)

dot = np.dot(A, B)
diag = np.diag(dot)

print (diag)

[1.04338097 0.95272322 1.26023419]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [293]:
vec = np.array([1, 2, 3, 4, 5])
result = np.zeros(len(vec) * 4 - 3, dtype=int)
result[::4] = vec
print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [295]:

arr = np.array([[1, 2], [3, 4], [5, 6]])
arr[[0, 1]] = arr[[1, 0]]
print(arr)

[[3 4]
 [1 2]
 [5 6]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [297]:

bool_arr = np.array([True, False, True])
bool_arr ^= True

float_arr = np.array([1.0, -2.0, 3.0])
float_arr *= -1

print(bool_arr)
print(float_arr)

[False  True False]
[-1.  2. -3.]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [307]:
matrix = np.random.rand(4, 4)
rank = np.linalg.matrix_rank(matrix)
print(rank)

4


#### 83. How to find the most frequent value in an array?

In [299]:

arr = np.array([1, 2, 2, 3, 3, 3, 4])
most_frequent = np.bincount(arr).argmax()
print(most_frequent)

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [301]:

arr = np.array([1, 3, 5, 7, 2, 9, 4])
n = 3
largest = np.sort(arr)[-n:]
print(largest)

[5 7 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)